### ISSUE TITLE
Bug in Sampler code

### ISSUE THREAD

**Issue by devinsba** [DataDog/dd-trace-java#1018]
While reading the code I came across what seems like a bug:

https://github.com/DataDog/dd-trace-java/blob/9771a6c90fd2ce8d0a9cee28e38b9e32b759b2d4/dd-trace-ot/src/main/java/datadog/trace/common/sampling/RateByServiceSampler.java#L118...L120

It would seem to me that, unless you mean disable sampling (record/report) everything, that this should be 0

EDIT:

after reading the code some more it seems that the DD perspective is that in the case of misconfiguration (would have to come from DD servers) the app should send everything to DD. Assuming this is the context for that line of code I will close this issue, though maybe that log line could use a bit of tweaking since not all developer/operators (people who would see that log) will understand the nuance of the `disable sampler` vs `disable samples` idea, and I can 🤦‍♂ for not reading it that way myself

**Comment by dougqh** [comment]
I think both interpretations (either no samples or no sampling) could make sense.  But yes, right now, this is working as we intended.
