### ISSUE TITLE
Add Quartz Instrumentation

### ISSUE THREAD

**Issue by randomanderson** [DataDog/dd-trace-java#1057]
Add instrumentation for Quartz scheduler.  This feature request has been extracted from #605 .

**Comment by soerenBoisen** [comment]
I have to admit, I was a bit disappointed discovering that Datadog does not provide easy out-of-the-box monitoring of Quartz scheduler. AFAIK this is the most used scheduler for the Java platform and job scheduling is something that really really needs monitoring, since there's no UI.

**Comment by codylerum** [comment]
This should encompass the Java EE EJB `@Schedule`

Currently a method annotated like below is not traced in Wildfly 18

`@javax.ejb.Schedule(second = "30", minute = "30", hour = "*", persistent = false)`

**Comment by patrickbray** [comment]
This would be great for us as well. I will add this manually via the @Trace / Open tracing instrumentation but would be keen to understand if this is on the roadmap at all? Thanks

**Comment by randomanderson** [comment]
@patrickbray This is scheduled for next quarter

**Comment by randomanderson** [comment]
#2222
