### ISSUE TITLE
Allow wildcard method instrumentation

### ISSUE THREAD

**Issue by randomanderson** [DataDog/dd-trace-java#1058]
Allow method instrumentation to accept wildcards.  For instance: `org.springframework.jms.core.JmsTemplate[*]` for all public methods on `JmsTemplate`.

This feature request has been extracted from #605.

**Comment by Psynbiotik** [comment]
This feature would be very useful, the explicit method currently supported can get unmanageable fast

**Comment by tyrcho** [comment]
I'd also like the wildcard to accept all classes in a package like
`com.colisweb.*`

would match any method in `com.colisweb.package1.Class1`
