### ISSUE TITLE
NoSuchMethodError: isHealthMetricsEnabled

### ISSUE THREAD

**Issue by JJonesAtAvaya** [DataDog/dd-trace-java#1087]
I'm linking with 
io.opentracing-api (0.33.0)
dd-trace-ot (0.36.0)
dd-trace-java (0.36.0) 
and getting this error at runtime: 

java.lang.NoSuchMethodError: datadog.trace.api.Config.isHealthMetricsEnabled()

This is happening when I pass dd-java-agent.jar (version 0.37.0) on the command line.

If I pass in dd-java-agent.jar version 0.36.0 on the startup line, then the error goes away

**Comment by randomanderson** [comment]
A new config parameter was added in the 0.37.0 results in an incompatibiloity when you try to use older versions simultaneously.

In general, you should use the same version for all libraries.  IE:

```
dd-trace-ot 0.36.0
dd-trace-java 0.36.0
dd-java-agent 0.36.0
```

**OR**

```
dd-trace-ot 0.37.0
dd-trace-java 0.37.0
dd-java-agent 0.37.0
```

**Comment by JJonesAtAvaya** [comment]
What about mixing opentracing with dd-trace?  The current version of io.opentracing is 0.33?
https://github.com/opentracing/opentracing-java/releases

Thank you

**Comment by randomanderson** [comment]
**Versions < 0.35.0:** only OpenTracing 0.31 is supported
**Versions >= 0.35.0:** OpenTracing 0.31 and 0.32 supported
**Versions >= 0.37.0:** OpenTracing 0.31, 0.32, and 0.33 supported
