### ISSUE TITLE
cannot instrument redis 3.0+ 

### ISSUE THREAD

**Issue by changjiang2016** [DataDog/dd-trace-java#1114]
In currrent version(0.38), the redis instrument work well with redis client under 3.0.When redis upgrade 3.0+,the redis  instrument no longer has any effect.The argument of method od sendCommand has change into redis.clients.jedis.Protocol$ProtocolCommand from redis.clients.jedis.Protocol$Command.How can I compatible with jedis client 3.0+?

**Comment by dougqh** [comment]
Thank you very much for the report -- especially, the details on the API change.
We'll look into making a fix soon.
