### ISSUE TITLE
URLAsResourceName decorator does not preserve API versions that follow format of `v1beta`

### ISSUE THREAD

**Issue by bruce-au** [DataDog/dd-trace-java#1116]
We have a API that contains versioning with the following formats: `v1beta`, `v1alpha`. We've noticed that when our resources are processed, it's collapsing the versioning path into a `?` rather than preserving it. We've noticed that it does have a whitelist for `v1`, `v2`, etc, so this behaviour is not intended.

**Comment by tylerbenson** [comment]
@bruce-au could you explain a bit what framework you are using for routing?  Ideally we should be able to get a better resource name from that.

For example, if you're using JAX-RS, we recently discovered a bug in our instrumentation around annotation inheritance: #1098 . If you're using JAX-RS, this might improve naming better than your proposed PR.

(if you'd like to chat about this you can also reach me in our slack: https://chat.datadoghq.com/)

**Comment by randomanderson** [comment]
https://github.com/DataDog/dd-trace-java/pull/1117#issuecomment-634263857
