### ISSUE TITLE
inconsistency between impl and document about DD_PROPAGATION_STYLE_INJECT

### ISSUE THREAD

**Issue by fujigon** [DataDog/dd-trace-java#1121]
- `DD_PROPAGATION_STYLE_INJECTION` accoding to 
 https://docs.datadoghq.com/ja/tracing/setup/java/#b3-headers-extraction-and-injection
- `DD_PROPAGATION_STYLE_INJECT` accoding to https://github.com/DataDog/dd-trace-java/blob/e548e11da0ff11bb7cb59a9c891b0a89e33ca37d/dd-trace-api/src/test/groovy/datadog/trace/api/ConfigTest.groovy#L64

**Comment by randomanderson** [comment]
`DD_PROPAGATION_STYLE_INJECT` is correct.  Documentation will be updated shortly
