### ISSUE TITLE
Exclude function/class from tracing

### ISSUE THREAD

**Issue by Flo354** [DataDog/dd-trace-java#1124]
Hi there,

Is it possible to exclude a particular function from tracing?
Actually, I have a class which is mainly used for health check. Each minute it does some SQL/Redis queries. I would like not to trace these queries.

Thanks,

**Comment by dougqh** [comment]
Other than setting a low priority, I don't believe we currently have an exclusion mechanism.

From your description, it sounds like the spans you'd like to exclude are from the SQL & Redis auto-instrumentation; correct?

But I suspect it would be nicer if you could exclude at the level of the health check.
Perhaps, if we supported setting a priority with `@Trace` annotation and then the annotation could be applied to the health check class.

**Comment by Flo354** [comment]
> From your description, it sounds like the spans you'd like to exclude are from the SQL & Redis auto-instrumentation; correct?

Yes, you are right

> Perhaps, if we supported setting a priority with `@Trace` annotation and then the annotation could be applied to the health check class.

Hmm, I'm not sure to understand what you want to say. Could you explain a little bit more?

Thanks,

**Comment by dougqh** [comment]
From your original description, it sounded like you have something like the pseudo-code below...

class HealthService {
  public void dbCheck() {
    dbConn.execute("SELECT * FROM DUAL;");
  }

  public void redisCheck() {
    redisConn... 
  }
}

If that's true, I thought we could suppress at higher level via an annotation - like...

@Trace(priority=Priority.DROPPED)
class HealthService {
  ...
}

**Comment by randomanderson** [comment]
Related to #453

**Comment by tylerbenson** [comment]
You can exclude specific resources at the agent level:
https://docs.datadoghq.com/security/tracing/#resource-filtering

If that doesn't help, go ahead and reopen the issue.

**Comment by kstittleburg-bw** [comment]
This would be useful for us as we have datadog agents running on Kubernetes hosts and the team that manages that ideally don't want application specific configuration at that level.  If it were a something like `@trace(priority=Priority.DROPPED)` mentioned above, it'd let developers have easy control over this.

**Comment by randomanderson** [comment]
@kstittleburg-bw Another solution is to use the OpenTracing API and the manual drop tag:

```java
import datadog.trace.api.DDTags;
import io.opentracing.Span;
import io.opentracing.Tracer;
import io.opentracing.util.GlobalTracer;
...

Tracer tracer = GlobalTracer.get();
Span span = tracer.activeSpan();
if (span != null) {
  span.setTag(DDTags.MANUAL_DROP, true);
}
...
```

NOTE: that only works if the sampling priority hasn't been set yet.  Sampling priority could have already been set if the trace is part of a a distributed trace.

**Comment by rr-paras-patel** [comment]
Here is PR for this documentation for `DD_TRACE_CLASSES_EXCLUDE ` Usage: https://github.com/DataDog/documentation/pull/10164/files#r604416079
