### ISSUE TITLE
Add the posibility to customize default decorators

### ISSUE THREAD

**Issue by tomasherman** [DataDog/dd-trace-java#1143]
Hi! 

We are running into trouble with dd-trace-ot ... we don't want the protection against 404 spam because we do make that protection somewhere else and dd-trace implementation messes up our traces. Would you be open to adding the option to customize default decorators? 

I'm ok with making the PR. Thanks!

**Comment by tylerbenson** [comment]
I think we are open to this.

Would you mind describing how you'd implement this, or would you rather show with a PR and be open to alternate ways of implementing?

**Comment by tomasherman** [comment]
I pushed proposed change, i tried to minimise the impact - let me know if it works for you

**Comment by tylerbenson** [comment]
Does #1152 address your issue adequately?

**Comment by tomasherman** [comment]
yep, LGTM 👍
