### ISSUE TITLE
4xx exceptions are being reported as 500

### ISSUE THREAD

**Issue by iagodvsantos** [DataDog/dd-trace-java#1166]
I've noticed that 4xx status code exceptions thrown by the application are being mapped as 500 by DD 

Doing some research I found a similar issue on dd-trace-rb which has been fixed:
https://github.com/DataDog/dd-trace-rb/issues/103

**Comment by tylerbenson** [comment]
I think we're going to need more info from you on how to reproduce this.  I suggest opening a ticket: support@datadoghq.com.  If they're unable to solve the problem, we can reopen this issue.
