### ISSUE TITLE
Lettuce integration dropping trace

### ISSUE THREAD

**Issue by aarya123** [DataDog/dd-trace-java#1178]
We're currently using Lettuce version 5.2 and are finding that the trace is being dropped somewhere in RedisPublisher. I'm still trying to figure out where exactly, but wanted to file this issue while I continue to dig.
I've attached the debug logs from the datadog agent running on the latest build from master.
[agent.log.zip](https://github.com/DataDog/dd-trace-java/files/4067227/agent.log.zip)

**Comment by andrewsouthard1** [comment]
Thanks @aarya123 - if you could open a support ticket that will be the best place for us to take a look into this.

**Comment by aarya123** [comment]
Done
