### ISSUE TITLE
Unable to fetch dd-java-agent.jar LATEST

### ISSUE THREAD

**Issue by surendrand** [DataDog/dd-trace-java#1183]
We were downloading dd-trace-agent LATEST from 
https://repo1.maven.org/maven2/com/datadoghq/dd-java-agent/LATEST/dd-java-agent-LATEST.jar
But jar with LATEST version is not available. Was it removed intentionally or it's a bug?

**Comment by randomanderson** [comment]
This is a result of maven.org changing their behavior.  We updated the documentation a few months ago with a more reliable link at: https://repository.sonatype.org/service/local/artifact/maven/redirect?r=central-proxy&g=com.datadoghq&a=dd-java-agent&v=LATEST
