### ISSUE TITLE
StackOverFlowError on regexp in TraceConfigInstrumentation

### ISSUE THREAD

**Issue by Blikingor** [DataDog/dd-trace-java#1191]
When passing a very large list of classes and methods to trace using **dd.trace.methods** a StackOverFlowError occurs in TraceConfigInstrumentation [on line 54](https://github.com/DataDog/dd-trace-java/blob/660041636aa80f3d9ad1829151f5ef46987d9cb3/dd-java-agent/instrumentation/trace-annotation/src/main/java/datadog/trace/instrumentation/trace_annotation/TraceConfigInstrumentation.java#L54). According to [this SO answer](https://stackoverflow.com/a/7510006), this issue is common to repetitive regular expressions.

**Comment by Blikingor** [comment]
One way to fix would be to split on ; and validate each individual class rather than the full string, basically replacing the regexp check with a small validation function:

`private boolean validateConfigString(String configString) {
    for (String clazz : configString.split(";")) {
      if (!clazz.matches(CONFIG_FORMAT)) {
        return false;
      }
    }
    return true;
  }`

I can do a PR for this if you agree on the solution.

**Comment by dougqh** [comment]
That solution sounds good to me.  Thank you for contributing.

**Comment by Blikingor** [comment]
@dougqh - all right, PR submitted and tests are passing.
