### ISSUE TITLE
Add Keycloak Instrumentation

### ISSUE THREAD

**Issue by knokio** [DataDog/dd-trace-java#1194]
Add native support for Keycoak projet - https://www.keycloak.org/

Currenty the default APM traces report only an "endpoint".
This API has several endpoints.

Any other workarounds?

**Comment by jeremy-lq** [comment]
@knokio Please open a [support ticket](https://www.datadoghq.com/support/) for this feature request, so we can properly track and notify you when it's completed. Thanks.
