### ISSUE TITLE
Issues since upgrading to 0.41.0

### ISSUE THREAD

**Issue by mackoftrack** [DataDog/dd-trace-java#1195]
We recently upgraded from 0.40.0 to 0.41.0. Since then we have seen a huge increase in reported requests and a huge drop in latency. I'm guessing this is due to https://github.com/DataDog/dd-trace-java/pull/1165 
We are tracing a Spring MVC application.

Our traffic has been stable, but DD is reporting some major differences:
![image](https://user-images.githubusercontent.com/3811209/73400075-426d9d00-429d-11ea-83e0-973f5a3fb2ca.png)

Specifically, I can attribute it to a JSP resource:
![image](https://user-images.githubusercontent.com/3811209/73400099-4f8a8c00-429d-11ea-830e-f5d433227344.png)

Any idea? Why is it considering the JSP as an "endpoint"? Can this feature be disabled?

**Comment by devinsba** [comment]
Can you check the component tag on a span from that endpoint to make sure we definitely look at the right module, it doesn't hurt to create a support ticket either support@datadoghq.com

**Comment by mackoftrack** [comment]
component: `java-web-servlet`

I will open a ticket as well, thanks

**Comment by mackoftrack** [comment]
Can I disable this feature in the current version? `dd.integration.servlet-filter.enabled` ?

**Comment by mackoftrack** [comment]
We downgraded to 0.40.0 and the issue went away. But we would still like to know why this happened and if there is a solution.

**Comment by tylerbenson** [comment]
Thanks so much for reporting this issue.  We have identified the problem and are working on a fix.  If you want, you should be able to disable the `"servlet-dispatcher"` instrumentation to resolve the issue until we get the fix released.

**Comment by tylerbenson** [comment]
@mackoftrack any chance you'd be willing to try [a snapshot build](https://40824-89221572-gh.circle-artifacts.com/0/home/circleci/dd-trace-java/libs/dd-java-agent-0.42.0-SNAPSHOT.jar) to confirm the fix?  We'd like to include this in our release tomorrow, so please let us know ASAP.

**Comment by mackoftrack** [comment]
@tylerbenson we only run the APM in our production environment, so I'd rather not. but once the release goes out I will deploy it in our next release cycle.

**Comment by mackoftrack** [comment]
@devinsba @tylerbenson the issue appears to be fixed after deploying the 0.42.0 release. One question though - it appears that the endpoints are now grouped differently. E.g. before there was an entry `GET /lists/view.*` and now it seems to be broken up into individual `GET /lists/?/xxxx`. It doesn't seem to be problematic, I just wanted to confirm that this is the expected behavior.

**Comment by devinsba** [comment]
@mackoftrack Are you seeing more, or less, resource names than you were before? ie: is the cardinality higher?

I would theorize that the interaction between these spans and the `datadog.opentracing.decorator`'s is slightly different than before

**Comment by mackoftrack** [comment]
It seems there are more resource names than before. But we are also getting restarted pods

![image](https://user-images.githubusercontent.com/3811209/73758400-660e6880-471f-11ea-9ad8-fad658fce8ea.png)

Seems to be OOM restarts. Is dd-trace-java using more RAM than before?

**Comment by tylerbenson** [comment]
Thanks for the update.  If you happen to have a heap dump, please file a support ticket so you can provide that directly to us.

**Comment by dougqh** [comment]
> Seems to be OOM restarts. Is dd-trace-java using more RAM than before?
Alas, there's not a simple answer to that question.

In version 0.42, we reduced the size of an internal cache to reduce the JVM's live set size.
However, when things are evicted from the cache, we might end up reloading them which can lead to additional churn especially in young gen.

In our experiments, this approach performs better in terms of memory and CPU when the heap is tightly constrained.  However, if the heap max is larger than physical memory or the container limit, this can lead to problems.

Unfortunately, many older JVMs don't have good defaults particularly for containerized environments.

**Comment by mackoftrack** [comment]
@dougqh for the deployment that was restarting, we have the following settings:
```
        resources:
          limits:
            cpu: "8"
            memory: 10Gi
          requests:
            cpu: "2"
            memory: 10Gi
```

and the JVM has the following args:

```
-Xms8g -Xmx8g -Djava.security.egd=file:/dev/./urandom -XX:+UseG1GC -X:+UseStringDeduplication
```

We'd like to be upgrade to the latest version of `dd-trace-java` but now we're nervous about any further upgrades due to the recent instability. Do you have different recommendations for the JVM settings?

**Comment by dougqh** [comment]
@mackoftrack 
> We'd like to be upgrade to the latest version of dd-trace-java but now we're nervous about any further upgrades due to the recent instability. Do you have different recommendations for the JVM settings?
Yes, that's completely understandable.

At first glance, an 8GiB heap with 10GiB memory limit seems quite reasonable.
And in most cases, 2GiB is more than enough left over for native memory usage of the JVM.

Does your app happen to use a lot of native memory?  The usual culprits are...
- direct buffers 
- high thread count
- generated classes
One good way to check is with -XX:NativeMemoryTracking=detail, but it does come with some overhead.
