### ISSUE TITLE
NPE on Elasticsearch TransportActionListener 

### ISSUE THREAD

**Issue by liborio7** [DataDog/dd-trace-java#1210]
https://github.com/DataDog/dd-trace-java/blob/032f22f5a6a55752ab32b7b7401c0f4ee858b47f/dd-java-agent/instrumentation/elasticsearch/transport-2/src/main/java/datadog/trace/instrumentation/elasticsearch2/TransportActionListener.java#L79

I'm using dd-java-agent 0.42.0 and Elasticsearch 2.4.4.
In reference to `TransportActionListener.onResponse() method`, when the response is a `BaseNodesResponse`, the method call `resp.failures()` return null and this will cause a `NullPointerException`.
I faced this issue for `ClusterStatsResponse` and `NodesStatsResponse`.

**Comment by tylerbenson** [comment]
@liborio7 interested in submitting a PR to fix it?

**Comment by liborio7** [comment]
@tylerbenson https://github.com/DataDog/dd-trace-java/pull/1215

**Comment by randomanderson** [comment]
Released with 0.44.0
