### ISSUE TITLE
 reference manual of "dd.trace.global.tags" is wrong 

### ISSUE THREAD

**Issue by nabedge** [DataDog/dd-trace-java#1222]
https://docs.datadoghq.com/ja/tracing/guide/adding_metadata_to_spans/?tab=java

## wrong
```
java -javaagent:<DD-JAVA-AGENT-PATH>.jar \
     -Ddd.trace.global.tags='env:dev,<TAG_KEY>:<TAG_VALUE>' \
```

if "single quotation" exists, the tags should not be override.

## correct
```
java -javaagent:<DD-JAVA-AGENT-PATH>.jar \
     -Ddd.trace.global.tags=env:dev,<TAG_KEY>:<TAG_VALUE> \
```

**Comment by cecile75** [comment]
Hey,
This is now fixed in our documentation. Thanks for your feedback
