### ISSUE TITLE
How to manually invoke span.setResourceName()

### ISSUE THREAD

**Issue by jstnlef** [DataDog/dd-trace-java#1230]
We have a homegrown RPC protocol I have instrumented using `dd-trace-java` which is currently working quite well. However, I would now like to be able to separate the resource name from the operation name in generated spans and I'm not quite sure how to go about doing that based on the current documentation. My hope was that I could do something like 
```
var span = childSpan.start
    span = span match {
      case s: DDSpan =>
        resourceName.map(rn => s.setResourceName(rn)).getOrElse(s).setOperationName(operationName)
      case s => s
    }
```
to access the setResourceName() method on the implemented span but it seems as though `datadog.opentracing.DDSpan` is shadowed to `datadog.trace.agent.ot.DDSpan` at runtime, disallowing me from pattern matching against it to call the implementation's method. To that end, 2 questions.

1. Why are the paths being shadowed? It seems as though datadog has added interesting functionality which would be nice to use in the event that our `javaagent` is set to the datadog agent (but only then).
2. Is there another way to specify and use `DDTracer` and `DDSpan` directly in our calling code since we're not very likely to ever use anything else?

**Comment by tylerbenson** [comment]
You can set the resource name like so:
```
span.setTag(DDTags.RESOURCE_NAME, "some-name");
```

**Comment by jstnlef** [comment]
Ah I see. That tag has special handling? I'll give it a go. Thanks!
