### ISSUE TITLE
Akka Http2 dsl

### ISSUE THREAD

**Issue by Marcus-Rosti** [DataDog/dd-trace-java#1271]
I figured out my akka app wasn't showing any metrics.
I was using
```scala
import akka.http.scaladsl.Http2
    Http2().bindAndHandleAsync(...)
```

but the supported classpath is
```scala
import akka.http.scaladsl.Http
    Http().bindAndHandleAsync(...)
```

**Comment by tylerbenson** [comment]
Related: #1271 #1105 #2012

**Comment by andrewsouthard1** [comment]
@Marcus-Rosti - we have added support for bindAndHandle in akka-http in 0.68.0 of the java tracer - please try the latest and confirm whether you still have this issue.

**Comment by devinsba** [comment]
In case someone else gets to this first: given that the classes are almost exactly the same this should just require adding another class to the instrumentation list (`akka.http.scaladsl.Http2`) and adding tests to validate

**Comment by bantonsson** [comment]
The innards of `Http2` is very bare bones in comparison to `Http`, and instrumenting `Http2().bindAndHandleAsync(...)` would mean pulling out the code for the old `Http().bindAndHandleAsync(...)` instrumentation and applying that instead.

**Comment by bm1549** [comment]
This has been supported as of [v0.72.0](https://github.com/DataDog/dd-trace-java/releases/tag/v0.72.0). Note that the current version is [v1.24.1](https://github.com/DataDog/dd-trace-java/releases/tag/v1.24.1)
