### ISSUE TITLE
"Sharing is only supported for boot loader classes because bootstrap classpath has been appended" when running with java 13

### ISSUE THREAD

**Issue by PedroHReis22** [DataDog/dd-trace-java#1294]
Hi, I am getting the following warning when tracing my java 13 application: 

> OpenJDK 64-Bit Server VM warning: Sharing is only supported for boot loader classes because bootstrap classpath has been appended

 Even though this is just a warn, it does pollute the logs and I think would be nice to get 'fixed'.

 My current stack is:
- Java 13
- Spring boot 2.2.5
- dd-java-agent 0.44.0

**Comment by tylerbenson** [comment]
What JVM startup arguments are you using?

**Comment by PedroHReis22** [comment]
Hi @tylerbenson , it is `-javaagent:/datadog.jar`. I think it does not matter, but running over docker image `openjdk:13`

**Comment by tylerbenson** [comment]
ok... I wasn't sure if you had any additional JVM parameters besides the `javaagent` flag.

**Comment by zhiweipeng** [comment]
we have the same issue, after removed -javaagent:dd-java-agent-0.44.0.jar then no more such warning message so it's very clear it is related to dd-java-agent-0.44.0.jar .  we are using openjdk 13 as well.

**Comment by randomanderson** [comment]
"Application Class-Data Sharing" is an optimization where users can record class load metadata into a "class-data archive".  Launching your application again reads from the archive so that the application starts faster.

As of Java 12, OpenJDK based JDKs have a class-data archive for JDK classes.  Because the Datadog agent appends to the bootstrap classpath, the class-data archive is incorrect for the system class loader.

The warning is telling you that the class data optimization is partially turned off.

The only way to get rid of the warning is to turn the optimization off fully with "-Xshare:off".  However, this could potentially worsen the startup performance of your application.

**Comment by PedroHReis22** [comment]
Hi @randomanderson , thanks for elaborating on this. 

Would it be possible to dd-agent to somehow bypass this warning somehow? I agree that `-Xshare:off` works, but it seems like I have to resign the performance introduced by JDK to get rid of the warning.

I guess Application Class-Data Sharing could play an important role in serverless applications.

**Comment by NatBob** [comment]
How does one get to dd-agent and -xshare?

**Comment by randomanderson** [comment]
@NatBob, I'm not sure what you're asking.  Do you mean how to add VM arguments?  It depends on how your application is started.  For instance, if your commandline was:

```
java -jar myApplication.jar
```

it becomes

```
java -javaagent:/path/to/dd-java-agent.jar -Xshare:off -jar myApplication.jar
```

Different applications have different approaches.  For instance, you might set `JAVA_TOOL_OPTIONS` or create a `setEnv.sh`

**Comment by randomanderson** [comment]
@PedroHReis22 I don't think there's another way to get rid of the warning.  In adding support for read only filesystems, we are reducing the amount of times we add to the bootstrap.  In the future, I believe you'll only get the warning once per startup.

**Comment by lavanyayangala** [comment]
OpenJDK 64-Bit Server VM warning: Sharing is only supported for boot loader classes because bootstrap classpath has been appended

#can anyone help with this?

**Comment by mcculls** [comment]
Hi @lavanyayangala - as explained in https://github.com/DataDog/dd-trace-java/issues/1294#issuecomment-597869917 this is an informational warning which you can safely ignore, the behaviour of your application shouldn't be affected.

**Comment by yhojann-cl** [comment]
Any way for supress warning from build.gradle file or other?

**Comment by randomanderson** [comment]
@yhojann-cl
Here is the actual code that prints this warning:

https://github.com/openjdk/jdk/blob/99ea8bf2b962011e57d02a93217d65d7259e8f80/src/hotspot/share/classfile/classLoaderExt.cpp#L61

There are 2 options to not print the warning:
- Disable the class data optimization fully ( with `-Xshare:off` )
- Disable warnings from being printed completely ( with `-XX:-PrintWarnings` )

As explained in https://github.com/DataDog/dd-trace-java/issues/1294#issuecomment-597869917 , this is a warning that can be safely ignored.

**Comment by dabaus** [comment]
> "Application Class-Data Sharing" is an optimization where users can record class load metadata into a "class-data archive". Launching your application again reads from this archive so that the application starts faster.
> 
> As of Java 12, OpenJDK based JDKs have a class-data archive for JDK classes. Because the Datadog agent appends to the bootstrap classpath, the class-data archive is incorrect for the system class loader.
> 
> The warning is telling you that the class data optimization is partially turned off.
> 
> The only way to get rid of the warning is to turn the optimization off fully with "-Xshare:off". However, this could potentially worsen the startup performance of your application.

What a useless warning. What where they thinking? I have this all over the place in all tools.

**Comment by va1m** [comment]
I have tested several JDKs 17 and found out that only 3 of them don't show this message:

* IBM Semeru 17.0.9
* JetBrains Runtime 17.0.9
* JetBrains Runtime (JCEF) 17.0.9

The JDKs have been downloaded in IDEA's "Project settings / SDKs / + / Download JDK..." tool
IBM Semeru also can be downloaded classic way, from IBM web site.

**Comment by MakraGitHub** [comment]
Java HotSpot(TM) 64-Bit Server VM warning: Sharing is only supported for boot loader classes because bootstrap classpath has been appended
I can't to config it
