### ISSUE TITLE
Add support for instrumentation of ElasticSearch client(s) 7.x

### ISSUE THREAD

**Issue by bentster** [DataDog/dd-trace-java#1321]
We recently upgraded our elasticsearch clients to 7 and noticed that all instrumentation and flame graphs of elasticsearch in APM vanished. It would be great if the agent could support instrumenting the newer versions of the client as well.

**Comment by go-ive** [comment]
We would also require this feature.

**Comment by go-ive** [comment]
Is this feature planned at all and is there an ETA on it? 

It's currently very inconvenient for us as we are running a SaaS application with several business customers and have no clear indication of which ES calls are performing slow. This makes issue analysis harder than it needs to be.

**Comment by randomanderson** [comment]
@go-ive There is an open pull request #2022 .  This will be in either the next release or the release after that.

**Comment by mcculls** [comment]
Update: I've just merged #2022 so it will be available in the next release (0.67.0)
