### ISSUE TITLE
Error while sending X of X+2 traces to the DD agent

### ISSUE THREAD

**Issue by joaquin386** [DataDog/dd-trace-java#1352]
We are constantly getting this error:
`
[dd.tracing.agent - 2020-04-03 12:20:57:995 +0000] [dd-trace-writer] WARN datadog.trace.agent.common.writer.DDApi - Error while sending 2 of 4 traces to the DD agent. java.io.IOException: unexpected end of stream on Connection{XXXXX:8126, proxy=DIRECT hostAddress=/XXXXXXX:8126 cipherSuite=none protocol=http/1.1} (going silent for 5 minutes)
`

How can that error/warn be avoided or removed from the logs?

Starting the application via:
java -javaagent:/apps/datadog/dd-java-agent.jar -jar service.jar

**Comment by ismailseyfi** [comment]
I had this happen to me as well. if you're agent is running in a docker container, and your services are running in other containers or possibly your local machine, you want to make sure DD_APM_NON_LOCAL_TRAFFIC is set to true. At least that did it for my set up.

**Comment by randomanderson** [comment]
The "unexpected end of stream" issues should be mostly fixed from the tracer side.  IOException occur when:
- the datadog agent is not reachable
- the datadog agent can't keep up with tracer traffic 

Please upgrade to the latest agent and the latest tracer as there has been substantial work done to improve connectivity and reduce dropped traces.

---
Not recommended, but you can completely suppress the log message if desired.  Internally, dd-java-agent uses the [slf4j simplelogger](http://www.slf4j.org/api/org/slf4j/impl/SimpleLogger.html) but we relocate the package to `datadog.slf4j.simplelogger`.  You can use any of the config at the link with the relocated package. `-Ddatadog.slf4j.simplelogger.log.datadog.trace.agent.common.writer.DDApi=off` to turn that particular log message off.

Please continue to comment or reopen if you have more questions

**Comment by qgicup** [comment]
@randomanderson  we're using datadog/agent:7-jmx and still have those warnings showing up all the time. Which release fixes that? Also, how to check the tracer, since that one is normally part of Datadog platform ? Thanks a lot

**Comment by afonsomatos** [comment]
We're getting this all the time as well.
