### ISSUE TITLE
What exactly does the @Trace annotation do?

### ISSUE THREAD

**Issue by olayinkasf** [DataDog/dd-trace-java#1401]
The javadoc says

> Set this annotation to a method so the dd-java-agent considers it for tracing.

Is it considered for tracing only if there was a started trace? or 

Does it starts a new trace regardless if there was an existing trace or not?

**Comment by randomanderson** [comment]
It creates a new span.  If a trace is ongoing, it'll be part of that trace.  Otherwise the span will be the root span of a new trace.  The `dd.trace.methods` property works identically.

In all cases, it only works with dd-java-agent running with your application.

**Comment by olayinkasf** [comment]
Thanks @randomanderson
