### ISSUE TITLE
traceid in the logs 

### ISSUE THREAD

**Issue by daparthi001** [DataDog/dd-trace-java#1452]
I have integrated the datadog with openam,openidm and ds stores ,but i am not seeing transaction id with in the logs how can i get that part of the logs ?

**Comment by randomanderson** [comment]
Directions for log injection is [here](https://docs.datadoghq.com/tracing/connect_logs_and_traces/java/?tab=slf4jlogback).  Essentially, you have to set `dd.logs.injection=true` and update you logging patterns

**Comment by randomanderson** [comment]
Closing as answered.  Feel free to add more comments if you need more help.
