### ISSUE TITLE
apm support for java 11 http client

### ISSUE THREAD

**Issue by rajbirsinghk** [DataDog/dd-trace-java#1478]
can we please have apm to include support for java 11 http client, we are unable to see external URL endpoints via tracing

**Comment by gokhanoner** [comment]
Any plan on this feature? and/or are you guys open for contribution?

**Comment by gokhanoner** [comment]
pinging again to see if you guys are open for contributions?

**Comment by richardstartin** [comment]
Hi @gokhanoner we are absolutely open for contributions

**Comment by oryband** [comment]
Any updates on this issue? New Relic supports it.

**Comment by lior-amberflo-io** [comment]
Hi, Will be happy to know if there is an update for this issue

**Comment by tylerbenson** [comment]
Looks like someone made an attempt: #3639

**Comment by maksymgendin** [comment]
We would also highly appreciate this feature 🙏

**Comment by mcculls** [comment]
Hi sorry for the lack of update - support for the JDK HttpClient was added back in [1.11.0](https://github.com/DataDog/dd-trace-java/releases/tag/v1.11.0)

Note the current release is [1.21.0](https://github.com/DataDog/dd-trace-java/releases/tag/v1.21.0)
