### ISSUE TITLE
Akka HTTP client request traces mixed with server request traces

### ISSUE THREAD

**Issue by balagez** [DataDog/dd-trace-java#1531]
I have a Play (2.8.x) service that uses Akka HTTP as the underlying HTTP client for AWS SDK (replacing the default Netty client). Since Play 2.8.x is not officially supported at the moment (and support doesn't seem to work), this service is being instrumented as an Akka HTTP application, reporting trace metrics to the `trace.akka_http` metric key (as Play uses Akka HTTP server as its underlying HTTP server). This very same key seems to be used by the Akka HTTP client instrumentation. The problem is that HTTP requests made by the service to AWS are now mixed with the requests served by the service itself.

This is not only wrong because it is more difficult to tell these apart on the APM service page but latency measurements are completely off. Because of the way the AWS SDK works, for instance, to poll SQS the SDK keeps repeating the same HTTP request in a loop, keeping the connection open for a specified amount of time, say 2 seconds. Now because of this, my service looks like it has a constant 2-second latency even though the requests the service actually receives respond in a few milliseconds:

![Screenshot 2020-06-03 17 09 44](https://user-images.githubusercontent.com/862067/83689503-210b1d80-a5bd-11ea-8a89-224e3f76cbc6.png)

The trace spans are in fact correctly tagged like this:
* Akka HTTP server: `component:akka-http-server`, `span.kind:server`
* Akka HTTP client: `component:akka-http-client`, `span.kind:client`

But the APM does not make a distinction based on any of these tags and and just mixes everything together.

It would be probably best to report traces from the Akka HTTP client into a separate metric key, like `trace.akka_http.client` (just like Netty that reports client calls to `trace.netty.client`) or `trace.akka_http_client`.

Or is there maybe a way to manually change this key in the code where the Akka HTTP client is instantiated?

Datadog Java agent version: 0.50.0

**Comment by devinsba** [comment]
Thanks for reporting this. You are right that the client span is named incorrectly.
