### ISSUE TITLE
Support for Play Framework 2.8.x

### ISSUE THREAD

**Issue by balagez** [DataDog/dd-trace-java#1544]
We have Play 2.8.x applications that are currently being detected and instrumented as Akka HTTP services by the Datadog Java agent. If I explicitly disable the Akka HTTP integration and explicitly enable Play integration (`DD_INTEGRATION_AKKA_HTTP_ENABLED=false DD_INTEGRATION_PLAY_ENABLED=true`), the agent will stop sending any traces.

Instrumenting these apps as Akka HTTP services more or less work (we do see traces coming in) but there is a serious shortcoming when it comes to detecting parameters in endpoint paths: the Akka HTTP instrumentation does not recognize certain parameters in the routes. For example, this Play route:

```http
GET /api/comments/qa/answers/:sort/$starterId<[0-9]+>
```

will be displayed by the APM like this:

```
resource_name:"GET /api/comments/qa/answers/desc/?"
```

The `sort` parameter is not recognized at all, and while `starterId` is recognized as a parameter, its name is not reported. It would be much better to see something like this (like node.js instrumentation is able to recognize and report parameter names):

```
resource_name:"GET /api/comments/qa/answers/:sort/:starterId"
```

The biggest issue with this shortcoming is that aggregation by endpoint is impossible and the `resource_name` tag is polluted with all observed values for each parameters.

Thanks!

**Comment by randomanderson** [comment]
There's a draft PR in progress to get Play 2.8 support: https://github.com/DataDog/dd-trace-java/pull/1521

**Comment by devinsba** [comment]
Correct me if I'm wrong, you are asking for the play routes to be
