### ISSUE TITLE
Ability to turn trace and metrics reporting on/off at runtime

### ISSUE THREAD

**Issue by balagez** [DataDog/dd-trace-java#1557]
Most of our services have an initial warmup period when, instead of real traffic, they're getting artificial traffic in order to warm up the JVM, initialize database connections, populate caches, etc.

During this time it would be great if we could pause reporting ALL metrics and traces to Datadog because the increased amount of traffic, potential errors, the JVM's initially suboptimal performance skews measurements of production nodes getting real traffic, and potentially triggers latency or RPS monitors during deploys or when the cluster is scaling up.

A simple public API method that allows us to pause and resume all reporting (integrations, JMX, etc.) at once would be the best, but I think any other solution, like being able to change the Datadog Agent's host name or port or the `env` tag at runtime would be just as good, any solution that can divert measurements away from `env:prod` until we decide that the application is ready for reporting.

(For the record, I experimented with changing JVM properties and environment variables at runtime but the Java agent doesn't seem to pick up those changes.)

Thanks a lot!

**Comment by randomanderson** [comment]
Thinking about this, I believe you can accomplish what you want with a `TraceInterceptor`.  See documentation [here](https://docs.datadoghq.com/tracing/custom_instrumentation/java/#extending-tracers).

For example, if you wanted to drop traces:

```java
public Collection<? extends MutableSpan> onTraceComplete(
         Collection<? extends MutableSpan> trace) {

     if (warmupFinished) {
         return trace;
     } else {
         return new ArrayList<>();
     }
}
```

Or, if you wanted to change the environment:

```java
public Collection<? extends MutableSpan> onTraceComplete(
         Collection<? extends MutableSpan> trace) {

     if (!warmupFinished) {
         for (MutableSpan span : trace) {
             span.setTag("env", "warmup");
         }
     }
     return trace;
}
```

What do you think?

**Comment by randomanderson** [comment]
Closing this issue as a solution has been posted.  Feel free to comment and the issue will be reopened
