### ISSUE TITLE
java.lang.NoClassDefFoundError when adding a context reference

### ISSUE THREAD

**Issue by pcasaes** [DataDog/dd-trace-java#1566]
When building a span with a reference context we get a NoClassDefFoundError

```
tracer.buildSpan("test-span")
                    .ignoreActiveSpan()
                    .addReference(References.FOLLOWS_FROM, context)
```

```
java.lang.NoClassDefFoundError: datadog/trace/agent/core/propagation/ExtractedContext
    	at datadog.trace.instrumentation.opentracing31.OTTracer$OTSpanBuilder.addReference(OTTracer.java:101)
```    	

This does not happen on 0.53.0, only 0.54.0. It doesn't matter if it's opentracing 0.31 or 0.32.

A simple test project that highlights this issue
https://github.com/pcasaes/datadog-opentracing-test

**Comment by tylerbenson** [comment]
Would you mind validating the fix with this snapshot from master: https://oss.jfrog.org/artifactory/oss-snapshot-local/com/datadoghq/dd-java-agent/0.55.0-SNAPSHOT/dd-java-agent-0.55.0-SNAPSHOT.jar

Thanks!

**Comment by pcasaes** [comment]
I can give it a try tomorrow.

**Comment by pcasaes** [comment]
Fixed!

**Comment by tylerbenson** [comment]
Thanks for the report.  We'll get a release out early next week.
