### ISSUE TITLE
IDE intergration to allow click from trace to code

### ISSUE THREAD

**Issue by toefel18** [DataDog/dd-trace-java#1597]
It would be nice if we could click on methods in a the trace and open them in the IDE or github to see the implementation of that method. This could speed up debugging a lot. 

This could be realized via URL's that the IDE can open, but it could also mean that we can copy the whole distributed trace as something like a stacktrace and copy that in our IDE.

**Comment by andrewsouthard1** [comment]
Hey @toefel18 - thanks for this feature request. While we don't have immediate plans for this integration - it'd be great if you can reach out to support@datadoghq.com as a feature request and we can keep you updated should this become closer to development.
