### ISSUE TITLE
Kafka instrumentation breaks log compaction

### ISSUE THREAD

**Issue by zersetz-end** [DataDog/dd-trace-java#1621]
Hello,

I realized that the Kafka producer instrumentation realizes tracing through a number of additional headers for the produced record. The problem I see with this concept is that [log compaction](https://kafka.apache.org/documentation/#compaction) relies on `null`-payloads for "tombstones" and the payload is composed of headers and value. So although it shouldn't break the services on the consumer side as they still receive a null value, which they can handle as tombstone, the record is never deleted in the Kafka itself.

Best Regards,
Dimitri

**Comment by ebrard** [comment]
@richardstartin Where did you see that payload = value + headers, in most of the Kafka sources I've checked, the tombstone detection is based on the value only.

**Comment by zersetz-end** [comment]
> 
> 
> @richardstartin Where did you see that payload = value + headers, in most of the Kafka sources I've checked, the tombstone detection is based on the value only.

I learned it trhough

**Comment by zersetz-end** [comment]
> 
> 
> @richardstartin Where did you see that payload = value + headers, in most of the Kafka sources I've checked, the tombstone detection is based on the value only.

I learned it by including business relevant headers and noticing the topic not being compacted in regards to tombstones. But I agree that the Kafka documentations aren't really clear on the matter, as every architectural documentation talks about "key" and "payload" or in some cases even "value" and the API documentations have to concept of headers, which also include record metadata like timestamps. But if you dive into the producer code you'll notice that "custom" headers are written into the payload, which I've never seen being mentioned anywhere.

**Comment by ebrard** [comment]
I haven't looked in the producer code yet, but I guess I'll need to because the KIP about Kafka headers ([KIP-82](https://cwiki.apache.org/confluence/display/KAFKA/KIP-82+-+Add+Record+Headers)) is really ambiguous around this topic.

**Comment by ebrard** [comment]
The [online documentation](https://kafka.apache.org/documentation/#messageformat) of the Kafka message (on disk) suggests that the headers are a separate element from the actual value payload, at least in the most recent versions.
Are you sure headers were the reason compaction didn't happen? Could it be just segment size, max lag,... topic or broker level configuration?

**Comment by ebrard** [comment]
So I double check with a little script, pushing a tombstone with some headers and I can confirm that compaction happened nevertheless, so I think this PR was not needed. Here after is the script:

```python
from kafka import KafkaProducer
from string import ascii_lowercase
import os

producer = KafkaProducer(bootstrap_servers='localhost:9091')

for i in range(10):
	producer.send('compacted', key='c'.encode('utf-8'), value='Hello key c'.encode("utf-8"), headers=[('Hello', 'Moto'.encode("utf-8"))])
	producer.flush()

for c in ascii_lowercase:
	if c == 'c':
		continue
	producer.send('compacted', key=c.encode('utf-8'), value="hello".encode("utf-8"))
	producer.flush()

producer.send('compacted', key='c'.encode('utf-8'), value=None, headers=[('Hello', 'Moto'.encode("utf-8"))]) # Tombstone with headers
#producer.send('compacted', key='c'.encode('utf-8'), value=None) # Tombstone without headers

producer.flush()

# We need the data and the snapshots to get delete (dirty part of the log) so we push on different keys

for c in ascii_lowercase:
	if c == 'c':
		continue
	producer.send('compacted', key=c.encode('utf-8'), value="hello".encode("utf-8"))
	producer.flush()

for c in ascii_lowercase:
	if c == 'c':
		continue
	producer.send('compacted', key=c.encode('utf-8'), value="hello".encode("utf-8"))
	producer.flush()

for c in ascii_lowercase:
	if c == 'c':
		continue
	producer.send('compacted', key=c.encode('utf-8'), value="hello".encode("utf-8"))
	producer.flush()
```
If you run it, you may need to push some additional keys to actually see the tombstone disappear from your available messages (or if you set your segment size to be more or less 1 message you can just observe the file being deleted, as well as its snapshot).
```
echo "x:SomeText" | kafkacat -b localhost:9091 -t compacted -Z -K:
```
