### ISSUE TITLE
Kafka consumer not using the same trace id for other trace

### ISSUE THREAD

**Issue by wilkinsleung0712** [DataDog/dd-trace-java#1633]
Hi guys, my app is kafka consumer to do stream processing. The kafka consumer has different trace id then the other traces in the same application. That leads to they not showing under the same flame Graph. Is there any way to work around this?

**Comment by richardstartin** [comment]
@wilkinsleung0712 which version of the tracer are you using?

**Comment by wilkinsleung0712** [comment]
@richardstartin 

im using 0.55.1 of dd-trace-java
Kafka consumer span link correctly to producer spans.

So i have below function
kafka.aggreate(functionA).mapValues(functionB))

@Trace functionA {}
@Trace functionB {}

Im expect the span in A and B use the same trace id so that i can see from the datadog flame graph.
Currently, span A has the same trace id as kafka consumer. (As i have configure app to use service.name mapping). And in flame graph, span A show under kafka consumer. 
However, span b is show under an independent flame graph, and i believe its due to different trance id.

**Comment by bm1549** [comment]
@wilkinsleung0712 can you try updating to the latest version of the tracer ([v1.24.1](https://github.com/DataDog/dd-trace-java/releases/tag/v1.24.1)) and setting the following system property or environment variable? If the issue still persists, please open up a support ticket for us to best help you

System property
```
-Ddd.kafka.legacy.tracing.enabled=false
```

Environment variable
```
DD_KAFKA_LEGACY_TRACING_ENABLED=false
```
