### ISSUE TITLE
NoSuchMethodError

### ISSUE THREAD

**Issue by sbly** [DataDog/dd-trace-java#1692]
Hi. I am using `dd-trace-ot` and `dd-trace-api`, both versions `0.57.0`. The code compiles fine, but when I actually run it, I get a bunch of errors, either `NoSuchMethod` or `NoClassDefFound`, e.g. `java.lang.NoSuchMethodError:datadog.trace.api.Config.getAgentTimeout()I`

Looking at the code, I see the [offending line](https://github.com/DataDog/dd-trace-java/blob/58ba1f8d8d903a8ce357856faa618f822826b7a4/dd-trace-core/src/main/java/datadog/trace/core/CoreTracer.java#L509). The `getAgentTimeout` method doesn't exist in the same version in the same repo. I'm not sure how the code is even compiling in the first place. This bug is preventing me from integrating with Datadog Tracing

**Comment by lpriima** [comment]
Method is generated from lambook annotation:
https://github.com/DataDog/dd-trace-java/blob/58ba1f8d8d903a8ce357856faa618f822826b7a4/dd-trace-api/src/main/java/datadog/trace/api/Config.java#L277

Could you please provide stack trace or more information ?

**Comment by sbly** [comment]
@tylerbenson Thank you! It turns out I was using a different version of the `dd-java-agent` which I didn't realize. I didn't know they had to match. Changing the version fixed it. Marking as closed
