### ISSUE TITLE
DefaultLogHandler should follow OpenTracing spec

### ISSUE THREAD

**Issue by jfklingler** [DataDog/dd-trace-java#1696]
According to the [OpenTracing spec](https://github.com/opentracing/specification/blob/master/semantic_conventions.md#logged-application-level-errors), the presence of the `message` field in a log event does not necessarily indicate an error. However, the [DefaultLogHandler](https://github.com/DataDog/dd-trace-java/blob/58ba1f8/dd-java-agent/instrumentation/opentracing/src/main/java/datadog/trace/instrumentation/opentracing/DefaultLogHandler.java#L37-L44) sets the `ERROR_MSG` tag on the span if the `message` field is present. This causes otherwise successful requests that include a `message` to include and display an "error" message in APM
```json
{
  "error": {	
    "message": "whatever message"
  }
}
```

I believe the logger should only set `ERROR_MSG` to the value of `message` if `span.isError()` is true.

**Comment by jfklingler** [comment]
What I was thinking was something along the lines of

```java
  private boolean isErrorSpan(final Map<String, ?> map, final AgentSpan span) {
    return (map.get(EVENT) instanceof String && map.get(EVENT).equals("error")) || span.isError();
  }
  
  private void extractError(final Map<String, ?> map, final AgentSpan span) {
    if (map.get(ERROR_OBJECT) instanceof Throwable) {
      final Throwable error = (Throwable) map.get(ERROR_OBJECT);
      span.addThrowable(error);
    } else if (isError(map, span) && map.get(MESSAGE) instanceof String) {
      span.setTag(ERROR_MSG, (String) map.get(MESSAGE));
    }
  }
```

**Comment by tylerbenson** [comment]
Would you mind giving some examples of where/how this is problematic?

**Comment by jfklingler** [comment]
If any message is added to span, it appears under the error tag
![image](https://user-images.githubusercontent.com/1284075/88221376-06067280-cc2a-11ea-8927-016c7401b4c2.png)
even though the status of the call is "OK"
![image](https://user-images.githubusercontent.com/1284075/88221412-13bbf800-cc2a-11ea-9ad4-b10370c16286.png)
While nothing is technically broken, it's confusing to see the `error.message` tag when nothing went wrong.
