### ISSUE TITLE
Add MDC instrumentation for Jboss Logging

### ISSUE THREAD

**Issue by pcasaes** [DataDog/dd-trace-java#1946]
We'd like to add trace data to logs on application using Jboss Logging (Quarkus and Wildfly). Right now it seems that the trace agent only instruments the slf4j with logback, and log4j MDCs.

Is it possible to also instrument jboss logging (jboss logmanager)?

**Comment by randomanderson** [comment]
This is a highly requested feature and is on our radar to add.
