### ISSUE TITLE
Log Tag Injection causes MDC swapping

### ISSUE THREAD

**Issue by sdwr98** [DataDog/dd-trace-java#1983]
There appears to be a serious issue with at least the slf4j+logback MDC when DD agent < 0.61.0 is being used *or* if DD agent > 0.61.0 is being used and `dd.logs.mdc.tags.injection` is set to `true`. 

I'm working on a smaller reproducible test case, but the short version is this: 

We have a Spring Boot web app that takes an HTTP header and sticks it in the MDC. We use this for log message correlation as well as some business logic.   With DD Agent 0.60.0, we found that some requests were getting their MDCs *mixed up*.   I put code in a servlet filter to log the value of the MDC entry at the beginning and the end of the request.  The code looks vaguely like this: 

```
    // Get the Unique ID at the start of the request
    final String uniqueIdAtStart = MDC.get(MDC_UNIQUE_ID_KEY);
    if (LOGGER.isDebugEnabled()) {
      LOGGER.debug("Unique ID at start of request: {}", uniqueIdAtStart);
    }

    try {
      chain.doFilter(request, response);
    } finally {
      final String uniqueIdAtEnd = MDC.get(MDC_UNIQUE_ID_KEY);
      if (LOGGER.isDebugEnabled()) {
        LOGGER.debug("Unique ID at end of request: {}", uniqueIdAtEnd);
      }
      if (!StringUtils.equals(uniqueIdAtStart, uniqueIdAtEnd)) {
        LOGGER.warn(
            "ALERT: Unique ID changed during request. At start: {}, at end: {}",
            uniqueIdAtStart,
            uniqueIdAtEnd);
      }
```

With DD agent 0.60.0 *and* with DD agent 0.64.0 plus `dd.logs.mdc.tags.injection=true`, I get the alert that the unique IDs changed when I put some load on the service.  If use version 0.64.0 and leave that property off, I do not get the alert. 

This is a huge issue and caused us some serious production bugs - so I think some sort of alert in the documentation would be really valuable until this gets fixed.

**Comment by sdwr98** [comment]
Also - here are the log messages from a sample request.  You can see that not only do our unique IDs change, the DD trace and span IDs get swapped out as well:

```
{"@timestamp":"2020-10-13T21:00:06.433Z","@version":"1","message":"ALERT: Unique ID changed during request. At start: bb8ee132-0a1b-4d35-8fda-092f2a0b9dfc, at end: 75fb9486-3d3d-448b-835d-f03a2597eba5","logger_name":"com.crsinc.util.context.filter.ContextFilter","thread_name":"http-nio-8080-exec-7","level":"WARN","level_value":30000,"dd.service":"jobservice","dd.env":"dev","dd.span_id":"3671839375636104182","X-UNIQUE-ID":"75fb9486-3d3d-448b-835d-f03a2597eba5","dd.trace_id":"4235672721744365225","dd.version":"datadog-test1","X-SESSION-ID":"571AAD528123C0623566F6246B98FF6C","SESSION_ID":"571AAD528123C0623566F6246B98FF6C"}
{"@timestamp":"2020-10-13T21:00:06.434Z","@version":"1","message":"172.19.0.12 - - [2020-10-13T21:00:06.434Z] \"POST /jobservice/thrift/json HTTP/1.1\" 404 -1","method":"POST","protocol":"HTTP/1.1","status_code":404,"requested_url":"POST /jobservice/thrift/json HTTP/1.1","requested_uri":"/jobservice/thrift/json","remote_host":"172.19.0.12","content_length":-1,"elapsed_time":15,"request_headers":{"accept":"*/*","accept-encoding":"gzip, deflate","content-length":"75","cookie":"JSESSIONID=6C9491DCACE4AC0048939D774930E8E1","host":"jobservice.srankin-local.motusclouds.com","user-agent":"python-requests/2.23.0","x-forwarded-for":"10.0.2.2","x-forwarded-host":"jobservice.srankin-local.motusclouds.com","x-forwarded-port":"80","x-forwarded-proto":"http","x-forwarded-server":"656760840b41","x-real-ip":"10.0.2.2","x-unique-id":"bb8ee132-0a1b-4d35-8fda-092f2a0b9dfc"}}
{"@timestamp":"2020-10-13T21:00:06.435Z","@version":"1","message":"Unique ID at start of request: bb8ee132-0a1b-4d35-8fda-092f2a0b9dfc","logger_name":"com.crsinc.util.context.filter.ContextFilter","thread_name":"http-nio-8080-exec-7","level":"DEBUG","level_value":10000,"dd.service":"jobservice","dd.env":"dev","dd.span_id":"2226851670007781316","X-UNIQUE-ID":"bb8ee132-0a1b-4d35-8fda-092f2a0b9dfc","dd.trace_id":"4235672721744365225","dd.version":"datadog-test1","X-SESSION-ID":"6C9491DCACE4AC0048939D774930E8E1","SESSION_ID":"6C9491DCACE4AC0048939D774930E8E1"}
{"@timestamp":"2020-10-13T21:00:06.435Z","@version":"1","message":"Unique ID at end of request: 75fb9486-3d3d-448b-835d-f03a2597eba5","logger_name":"com.crsinc.util.context.filter.ContextFilter","thread_name":"http-nio-8080-exec-8","level":"DEBUG","level_value":10000,"dd.service":"jobservice","dd.env":"dev","dd.span_id":"7553136907421326336","X-UNIQUE-ID":"75fb9486-3d3d-448b-835d-f03a2597eba5","dd.trace_id":"2472783096953429214","dd.version":"datadog-test1","X-SESSION-ID":"571AAD528123C0623566F6246B98FF6C","SESSION_ID":"571AAD528123C0623566F6246B98FF6C"}
```

**Comment by lpriima** [comment]
1. DD trace and span IDs will be injected by `dd.logs.injection=true` . This is documented option.
1. `dd.logs.mdc.tags.injection` is undocumented option yet. Please don't set it to true.  Here is the discussion why it's set to false by default: https://github.com/DataDog/dd-trace-java/issues/1753#issuecomment-683344565

**Comment by sdwr98** [comment]
Fair enough, but that code is active in 0.60.0 and causing production problems - so I thought you might want to know that there's a serious bug in it even in 0.64.0.

**Comment by ericjmooney** [comment]
Agreed.  For anybody using the MDC for...I guess, well, anything in a multithreaded environment, you're going to have a bad time, and your values are going to get swapped out from under you.  Feels like there should be at least some warning text in the docs about this.

**Comment by lpriima** [comment]
@sdwr98 thanks for letting me know. I'm still working on that. Do you have any problems on latest release when you don't touch undocumented `dd.logs.mdc.tags.injection` flag ?

**Comment by sdwr98** [comment]
No, 0.64.0 works fine out of the box, as a result of #1808 - but we were running 0.60.0 in production and that version does have the problem with the default configuration.  That's why I wanted to alert you - maybe to put a Known Issues section in the release notes for 0.60 or something.

**Comment by andrewsouthard1** [comment]
Hey @sdwr98 - thanks for note here. We've updated our release notes for 0.60.0 with this as a known issue. Please reach out with any additional concern!
