### ISSUE TITLE
WARN datadog.trace.bootstrap.config.provider.ConfigConverter - Invalid config for tags

### ISSUE THREAD

**Issue by pratul** [DataDog/dd-trace-java#1999]
```
[dd.trace 2020-10-16 16:06:12:480 +0000] [main] WARN datadog.trace.bootstrap.config.provider.ConfigConverter - Invalid config for tags: 'dyno:web.1 dynotype:web buildpackversion:dev appname:******'. Must match 'key1:value1,key2:value2'.
```

I'm seeing the above line show up every time I deploy my app. Unsure if there's something I can do to fix the issue? Regardless, I thought I should report it. 

### Environment
I'm running a JVM service on Heroku (stack heroku-18: https://devcenter.heroku.com/articles/heroku-18-stack)

**Comment by richardstartin** [comment]
@pratul it's suggesting that you change `dyno:web.1 dynotype:web buildpackversion:dev appname:******`
to `dyno:web.1,dynotype:web,buildpackversion:dev,appname:******`

**Comment by pratul** [comment]
Yes, that makes sense... except I’m not setting these values manually anywhere myself. I’m not sure what part of the Datadog APM setup for Heroku causes this to happen. Any ideas? Happy to try my hand at a PR.

**Comment by richardstartin** [comment]
@pratul thanks for the report - this will be fixed in one of the next two releases of the tracer.
