### ISSUE TITLE
Ignore resources not working 

### ISSUE THREAD

**Issue by feguiguren** [DataDog/dd-trace-java#2000]
Hi, I'm trying to exclude health checks from generating traces. 
I found out 2 different docs that explain how to do it.

1: https://docs.datadoghq.com/agent/kubernetes/apm/?tab=helm

DD_APM_IGNORE_RESOURCES | Configure resources for the Agent to ignore. Format should be comma separated, regular expressions. i.e. GET /ignore-me,(GET\|POST) /and-also-me.
-- | --

Which I configured as:
`- name: DD_APM_IGNORE_RESOURCES`
`          value: "GET /health/v1, POST /"`

This does not seem to be working. 

2: https://docs.datadoghq.com/tracing/custom_instrumentation/agent_customization/?tab=kubernetes

>  @param ignore_resources - list of strings - optional
 A list of regular expressions can be provided to exclude certain traces based on their resource name.
 All entries must be surrounded by double quotes and separated by commas.
 ignore_resources: ["(GET|POST) /healthcheck","API::NotesController#index"]

Which I configured as:
`- name: DD_APM_IGNORE_RESOURCES`
`          value: '["GET /health/v1", "POST /"]'`

But that is not working either. 

Is this not working or am I screwing up the syntax? 
Also tested:
`- name: DD_APM_IGNORE_RESOURCES`
`          value: '["GET /health/v1.*", "POST /"]'`
and
`- name: DD_APM_IGNORE_RESOURCES`
`          value: "GET /health/v1, POST /"

Thanks !

**Comment by andrewsouthard1** [comment]
Hey @feguiguren - are you setting this on the Datadog Agent or the Java Tracer configuration? This is Agent configuration - if you are still having issues the best place to troubleshoot would be to open a support ticket at support@datadoghq.com
