### ISSUE TITLE
Akka-http bindAndHandleAsync is deprecated

### ISSUE THREAD

**Issue by Daenyth** [DataDog/dd-trace-java#2012]
It looks like `bindAndHandleAsync` is the only thing that the agent instruments, https://github.com/DataDog/dd-trace-java/blob/b3b69e6fa04dab18674b0bb81761f56f5cc79b4d/dd-java-agent/instrumentation/akka-http-10.0/src/main/java/datadog/trace/instrumentation/akkahttp/AkkaHttpServerInstrumentation.java#L62-L77

but that method is deprecated in the latest akka-http, meaning that if the deprecation warning is cleaned, APM won't work

**Comment by tylerbenson** [comment]
Related: #1271 #1105 #2012

**Comment by randomanderson** [comment]
This is resolved by #2050
