### ISSUE TITLE
Apache Camel support

### ISSUE THREAD

**Issue by tfactor2** [DataDog/dd-trace-java#2064]
Hi,
We are using DataDog java agent with out-of-the-box frameworks integrations. It satisfies most of our needs except the ability to conveniently trace Apache Camel routes.
It's a blocker for us, so we have to do custom development and integrate opentracing into the application.

Is there any plan to add the support of Apache Camel?
According to traces mentioned in the issue https://github.com/DataDog/dd-trace-java/issues/433 the demand is there:
```
[main] DEBUG datadog.trace.agent.tooling.AgentInstaller$LoggingListener - Transformed class io.undertow.servlet.handlers.DefaultServlet -- sun.misc.Launcher$AppClassLoader@7e72c127
[Camel Thread #0 - LRUCacheFactory] DEBUG datadog.trace.agent.tooling.AgentInstaller$LoggingListener - Transformed class java.util.concurrent.ForkJoinPool -- null
[Camel Thread #0 - LRUCacheFactory] DEBUG datadog.trace.agent.tooling.AgentInstaller$LoggingListener - Transformed class java.util.concurrent.ForkJoinTask -- null
[Camel Thread #0 - LRUCacheFactory] DEBUG datadog.trace.agent.tooling.AgentInstaller$LoggingListener - Transformed class java.util.concurrent.ForkJoinTask$RunnableExecuteAction -- null
[Camel Thread #0 - LRUCacheFactory] DEBUG datadog.trace.agent.tooling.AgentInstaller$LoggingListener - Transformed class java.util.concurrent.ForkJoinTask$AdaptedCallable -- null
[main] DEBUG datadog.trace.agent.tooling.AgentInstaller$LoggingListener - Transformed class org.apache.camel.component.jetty.CamelContinuationServlet -- sun.misc.Launcher$AppClassLoader@7e72c127
```

**Comment by orange-buffalo** [comment]
Current workaround seems to be to use [Open Tracing integration](https://docs.datadoghq.com/tracing/setup_overview/open_standards/java):
* Enable [Camel Open Tracing](https://camel.apache.org/components/latest/others/opentracing.html).
* That's it?

**Comment by tfactor2** [comment]
Any news?

**Comment by nedemon** [comment]
Any updates here, guys?

**Comment by onyxraven** [comment]
Also looking for an update.

**Comment by devinsba** [comment]
For those asking for support, what would that look like to you? Part of the difficulty here is deciding where to create spans, how to handle workflow steps, how to handle fan-out, etc.

Ideas on what you would want these traces to end up looking like would be great. If you could include sample code defining a workflow with your ideas that would be even better

**Comment by onyxraven** [comment]
I have spent some time and have a first pass at an adapter and setup example that I can share once I get internal approval. It uses camel-opentracing and sets up the right strategy. This is all provided by the opentracing library, and may work with the opentelemetry one too (assuming the agent injects the right providers?)

I've also created a prototype decorator that can use the `_datadog` header like the serverless tracing bits, for integrating microservice and serverless. It's a little weird due to some of the limitations of various layers. I've got some other opinions about this that are for another forum.

**Comment by onyxraven** [comment]
Hey ya'll - so this is supported "out of the box" and works pretty well. This is thanks to opentracing. [The documentation on the camel site works](https://camel.apache.org/components/3.16.x/others/opentracing.html), and the following has the couple of additions.

## camel context setup

To get the full effect (propagation, and automatic per-processor spans) you need to use the `OpenTracingTracingStrategy` as mentioned in the documentation (but not well mentioned how to apply it). You need to give it a Tracer instance (in this case, I'm using spring to get it auto injected)

```kotlin
package com.mypackage.config

import org.apache.camel.CamelContext
import org.apache.camel.ExtendedCamelContext
import org.apache.camel.opentracing.OpenTracingTracer
import org.apache.camel.opentracing.OpenTracingTracingStrategy
import org.apache.camel.spring.boot.CamelContextConfiguration
import org.springframework.context.annotation.Bean
import org.springframework.context.annotation.Configuration


@Configuration
class CamelConfig(
    private val tracer: OpenTracingTracer
) {

    @Bean
    fun contextConfiguration(): CamelContextConfiguration {
        return object : CamelContextConfiguration {
            override fun beforeApplicationStart(context: CamelContext) {
                context.adapt(ExtendedCamelContext::class.java).addInterceptStrategy(OpenTracingTracingStrategy(tracer))
            }

            override fun afterApplicationStart(camelContext: CamelContext) {
                // noop
            }
        }
    }
}
```

**Comment by RuslanHryn** [comment]
any update?
Support of openTracing was removed in Camel 4. Therefore we need to migrate from openTracing to OpenTelemetry. That's why it will be nice to have support of Camel in dd java agent in order to avoid migration to openTelemetry

**Comment by dougqh** [comment]
We don't have any immediate plans to add support for Camel.

However, we did add support for OpenTelemetry APIs recently.

**Comment by bm1549** [comment]
[Camel is now supported in Beta](https://docs.datadoghq.com/tracing/trace_collection/compatibility/java/#networking-framework-compatibility) via our [OpenTelemetry API support](https://docs.datadoghq.com/tracing/trace_collection/otel_instrumentation/java/)

If you notice any issues, please reach out to support so that we can look into them properly
