### ISSUE TITLE
Can trace http request / response?

### ISSUE THREAD

**Issue by juyeonyu-nomad** [DataDog/dd-trace-java#2236]
My company use datadog Java Trace Agent.

Can trace http request / response?

I can't manual at that.

**Comment by randomanderson** [comment]
I'm not sure I understand the question.  We trace requests to and from supported http clients and servers.  The list of supported frameworks is at https://docs.datadoghq.com/tracing/setup_overview/compatibility_requirements/java/ .

If you're asking if we support adding the request body or response body to a tag, we don't do that automatically.

**Comment by juyeonyu-nomad** [comment]
> I'm not sure I understand the question. We trace requests to and from supported http clients and servers. The list of supported frameworks is at https://docs.datadoghq.com/tracing/setup_overview/compatibility_requirements/java/ .
> 
> If you're asking if we support adding the request body or response body to a tag, we don't do that automatically.

Sorry my question is ambiguous.

I want to say http request / response headers and body payload text.

**Comment by randomanderson** [comment]
For headers, you can use the `dd.trace.header.tags` system property or `DD_TRACE_HEADER_TAGS` environment variable to automatically set specific headers as tags.  See [Configuration Options](https://docs.datadoghq.com/tracing/setup_overview/setup/java?tab=containers#configuration)

We don't support automatically adding the body to traces

**Comment by juyeonyu-nomad** [comment]
> For headers, you can use the `dd.trace.header.tags` system property or `DD_TRACE_HEADER_TAGS` environment variable to automatically set specific headers as tags. See [Configuration Options](https://docs.datadoghq.com/tracing/setup_overview/setup/java?tab=containers#configuration)
> 
> We don't support automatically adding the body to traces

Thank you your answer.

**Comment by izavadynskyi** [comment]
> For headers, you can use the `dd.trace.header.tags` system property or `DD_TRACE_HEADER_TAGS` environment variable to automatically set specific headers as tags. See [Configuration Options](https://docs.datadoghq.com/tracing/setup_overview/setup/java?tab=containers#configuration)
> 
> We don't support automatically adding the body to traces

@randomanderson , is there a way to manually enable the possibility adding the body to traces in Datadog?
