### ISSUE TITLE
Stopped seeing traces from Jetty after v0.67.0

### ISSUE THREAD

**Issue by jvia** [DataDog/dd-trace-java#2299]
Since v0.67.0 our Jetty 9 app has stopped showing up under the services list in the APM tab. We still received traces from other parts of the code base like the JDBC calls and also saw the data from the continuous profiler.

Rolling back to v0.66.0 has resolved the issue for the time being.

Let me know if you need any more details.

**Comment by bm1549** [comment]
If this is still an issue in the latest release of the tracer, please open up a support ticket at https://www.datadoghq.com/support/
