### ISSUE TITLE
Kafka consumer / producer spans get attributed to a synthetic 'kafka' service, rather than the actual host service

### ISSUE THREAD

**Issue by benweint** [DataDog/dd-trace-java#2353]
## Summary

The Kafka consumer instrumentation appears to record spans under a synthetic service name 'kafka', rather than using the name of the actual DataDog service in which the consumption is happening. The result is a confusing experience in the UI when trying to find associated traces.

It's possible to 'fix' this behavior using a trace interceptor, but the default seems wrong to me. Is there a reason behind the current behavior?

## Details

I'm not sure whether this is a bug or an intentional design decision, but it took me a while to figure out what was going on with it, so I'm filing it here to get some feedback.

I have a Java service (let's call it `mysvc`) that contains a Kafka consumer. The service is instrumented with `dd-java-agent` 0.72.0 and also includes `dd-trace-api` 0.72.0.

Upon seeing the built-in support for instrumenting Kafka consumers, I expected to see traces with operation=`kafka.consume` (or similar) show up associated with `mysvc` in APM. That did not happen, so I tried manually instrumenting a method within my service that is responsible for handling a single consumed Kafka message via a `@Trace` annotation from the `dd-trace-api` package. However, still no Kafka spans (either with operation `kafka.consume` or `trace.annotation`) appeared in APM for `mysvc`.

It turns out that the consumer spans *were* being reported, but they were being associated with a 'dummy' service called `kafka`, which made them impossible to find from the APM page of the actual service in which the consumption was happening. From what I can gather of [this code](https://github.com/DataDog/dd-trace-java/blob/a472a2cd0e3209e14ea4bb1de8b497914546fd30/dd-java-agent/instrumentation/kafka-clients-0.11/src/main/java/datadog/trace/instrumentation/kafka_clients/KafkaDecorator.java#L60-L63), this behavior is not configurable.

Once I implemented the following trace interceptor to re-tag spans with the correct service, they started showing up in APM:

```java
public class KafkaConsumerTraceInterceptor implements TraceInterceptor {
    private final String serviceName;

    public KafkaConsumerTraceInterceptor(String serviceName) {
        this.serviceName = serviceName;
    }

    @Override
    public Collection<? extends MutableSpan> onTraceComplete(Collection<? extends MutableSpan> spans) {
        for (var span : spans) {
            if (span.getOperationName().equals("kafka.consume")) {
                span.setServiceName(serviceName);
            }
        }
        return spans;
    }

    @Override
    public int priority() {
        return 0;
    }
}
```

**Comment by benweint** [comment]
It sounds like https://github.com/DataDog/dd-trace-java/issues/1633 might be the same issue, but there's not quite enough detail there for me to tell for sure.

**Comment by randomanderson** [comment]
This is the expected behavior.  Historically, certain things were considered a separate service even if it was running in the same process.  You can see this behavior in multiple integrations.

It is possible to override without a `TraceInterceptor` using the service mappings.

`-Ddd.service.mapping=kafka:mysvc`

or using an environment variable:

`DD_SERVICE_MAPPING=kafka:mysvc`

See full configuration options [here](https://docs.datadoghq.com/tracing/setup_overview/setup/java/?tab=containers#configuration)

**Comment by benweint** [comment]
Ah, `DD_SERVICE_MAPPING` seems like just the thing I need - thanks for pointing that out @randomanderson!

I'll close this out.
