### ISSUE TITLE
Aerospike traces that are "Not found" do not appear as traces

### ISSUE THREAD

**Issue by Marcus-Rosti** [DataDog/dd-trace-java#2363]
in 0.72 I noticed that when records are not found, datadog doesn't record a trace. I think it's because the java library for aerospike returns `null` :yikes: and it's filtered out somewhere.

**Comment by richardstartin** [comment]
hi @Marcus-Rosti thanks for the bug report - we will prioritise fixing this.

**Comment by bm1549** [comment]
@Marcus-Rosti if this is still a problem, please open up a support ticket at https://www.datadoghq.com/support/
