### ISSUE TITLE
High memory usage in ExecutorInstrumentationUtils

### ISSUE THREAD

**Issue by agourlay** [DataDog/dd-trace-java#2366]
Hi :wave: 

Using the `Continuous Profiler` web interface I found some interesting results regarding the memory consumption of this library.

Namely I was able to observe on the heap several Gigabytes allocated by:
- `java.lang.Class.getEnclosingMethod0()`
- `java.lang.Class.getEnclosingMethodInfo()`

Both calls originate from `shouldAttachStateToTask` in [ExecutorInstrumentationUtils](https://github.com/DataDog/dd-trace-java/blob/master/dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/java/concurrent/ExecutorInstrumentationUtils.java#L32)

![dd](https://user-images.githubusercontent.com/606963/106623295-c32c3c80-6574-11eb-9db5-2dcf5c13e57b.png)

I was wondering if it could be possible to avoid recomputing this information over and over again by using some form of caching.

**Comment by bantonsson** [comment]
Hi @agourlay, thanks a lot for the find and detailed description. It's an old piece of code that can be moved to the `ExcludeFilter` where it won't be recomputed. I'll take a look at it right away.

**Comment by agourlay** [comment]
@bantonsson Thank you very much for the fast turnaround :pray:
