### ISSUE TITLE
Limit the granularity of a Trace

### ISSUE THREAD

**Issue by NicklasWallgren** [DataDog/dd-trace-java#2383]
This is rather a question than an issue.

Is it possible to limit the granularity of a trace, in Spring Boot? Lets say I only want to trace the time for a batch job, and not every single span/query to the database. 

Thanks.

**Comment by randomanderson** [comment]
From the Datadog agent:
- you can use `DD_APM_IGNORE_RESOURCES` to ignore specific resources such as queries you do not want to be sent to the Datadog backend.

From the tracer:
- you can disable specific integrations, eg `-Ddd.integration.jdbc.enabled=false` (see [full list of integrations](https://docs.datadoghq.com/tracing/setup_overview/compatibility_requirements/java/)
- you can create a `TraceInterceptor` that drops the spans you don't want

However, it's recommended that you send everything.  You can always filter to specific spans or metrics through the UI

**Comment by NicklasWallgren** [comment]
Thanks, I might go with the `TraceInterceptor` option, since I only want to limit the number of spans for some particular batchjobs.
