### ISSUE TITLE
Spans reported independently not in a single Trace

### ISSUE THREAD

**Issue by grv0908** [DataDog/dd-trace-java#242]
I have 3 sprint boot microservices (A, B, C) running on separate servers. My request flow is A -> B-> C

Now this is a single request call hitting multiple servers. I should get 3 spans stacked in a trace but spans are reported as 3 separate traces each containing only single spans. how can i correlate all spans together in one trace?

**Comment by tylerbenson** [comment]
This depends heavily on propagating the trace correctly between services.  Supported http frameworks should do this already. If you're not using one of these frameworks, you can manually propagate using OpenTracing's inject and extract API.

**Comment by tylerbenson** [comment]
@grv0908 @n0mer, perhaps you could clarify what frameworks you are using that isn't propagating properly?

**Comment by n0mer** [comment]
@tylerbenson spring-boot 2, grpc-java (netty), spring-webflux, spring-web 5

Actually, i'm still wondering how to see any trace at all for service marked as @datadog.trace.api.Trace or `Scope scope = tracer.buildSpan("my-span")`. Should i set startActive to `true` or `false` :) ?

**Comment by tylerbenson** [comment]
Thanks for the clarification on frameworks. We do have work to do on the async frameworks. 

For your question, if you set to false, you must manually close the span in addition to closing the scope.

**Comment by tylerbenson** [comment]
@grv0908 @n0mer, are you aware of any publicly available sample apps that we could run to simulate your environment?

**Comment by n0mer** [comment]
@tylerbenson i've started using `true` for startActive, it solved my isssue.

**Comment by tylerbenson** [comment]
Oh great. Does that mean this issue can be closed?

**Comment by tylerbenson** [comment]
I'm going to close this.  Happy to discuss further if you need additional help.

**Comment by n0mer** [comment]
@tylerbenson all data is in DataDog already, hence no need to simulate if you can look at baremetal
