### ISSUE TITLE
Opentracing 0.33.0 integration

### ISSUE THREAD

**Issue by nicolas-vivot** [DataDog/dd-trace-java#2421]
I'm currently moving my project stack (spring boot) to quarkus with smallrye opentracing support and i figured they are using 0.33.0.

I'm using dd-tracer API & OT, providing a scope listener as [mentioned here](https://github.com/DataDog/dd-trace-java/issues/2066) to get trace & span id injected on logs.

It works great until dd tracer start to call 'activeSpan()' method which has been removed on opentracing 0.33.0.
![image](https://user-images.githubusercontent.com/79290619/108461879-e79b4f00-72be-11eb-8111-cff304f1edb2.png)

My question is:
- Do you have plans to integrate opentracing 0.33+ ?
- If yes, how fast would it be ?

**Comment by nicolas-vivot** [comment]
PS: i know i can force dependencies to 0.32, and then everything works.

I'm just wondering when it's going to be upgraded, 0.33.0 has been released more than 2 years ago.

**Comment by tylerbenson** [comment]
`activeSpan()` was not removed in `0.33.0`, `active()` was.

`dd-trace-ot` is compiled against `0.32.0` which is compatible with other code compiled against `0.31.0`-`0.33.0`, but the minimum runtime supported version is `0.32.0` (this is declared in the pom) so you should be running with at least that version.

Looking at the stacktrace, it seems that `GlobalTracer.java:148` lines up with version `0.31.0`, so I'm not sure how you're getting that version.  Please ensure you have at least `0.32.0` as a runtime dependency.

**Comment by nicolas-vivot** [comment]
I see, thank you for your feedback.

**Comment by tylerbenson** [comment]
I'm going to close this issue.  Please feel free to reopen if you still have questions or concerns.
