### ISSUE TITLE
DD trace integration interferes with AWS metrics publisher for Java AWS SDK v2

### ISSUE THREAD

**Issue by ceven** [DataDog/dd-trace-java#2431]
I am trying to upgrade the AWS java sdk of an application from V1 to V2, more precisely from 1.11.799 to 2.16.3. 
Datadog tracing works fine for aws services and cloudwatch metrics get correctly published with the SDK V1 when running my service along with dd-trace-java.

When upgrading to V2, AWS tracing and metrics silently fail (even a custom metrics publisher, such as a simple logger as outlined in https://aws.amazon.com/blogs/developer/using-the-new-client-side-metrics-feature-in-the-aws-sdk-for-java-v2/ , does not log anything).

If I disable integration (DD_INTEGRATIONS_ENABLED=false), then metrics work fine (previous metrics logger is fine, metrics get published to cloudwatch).

I've noticed Datadog is intercepting classes from SDK V2 (e.g. https://github.com/DataDog/dd-trace-java/blob/032b90d449912add1c54f8a7d2f7219ef42834cb/dd-java-agent/instrumentation/aws-java-sdk-2.2/src/main/java/datadog/trace/instrumentation/aws/v2/AwsHttpClientInstrumentation.java#L38-L45 ), which may be related to this issue?

**Comment by richardstartin** [comment]
Hi @ceven thanks for reporting the issue. Which version of the tracer are you using?

**Comment by ceven** [comment]
Hi @richardstartin , I am running the application as a packaged jar with the argument -javaagent:/opt/dd-java-agent.jar. The datadog java agent is downloaded from https://dtdg.co/latest-java-trace

**Comment by mcculls** [comment]
This should be fixed by #2539 which will be part of the 0.77.0 release

**Comment by mcculls** [comment]
You can upgrade to the latest release to pick up the fix  - let us know if you encounter further issues, thanks
