### ISSUE TITLE
[Question] DD headers extraction & injection

### ISSUE THREAD

**Issue by emirot** [DataDog/dd-trace-java#2434]
Hey there,

What I'm trying to accomplish is to uniform traces across different services.
Let's say my application is receiving http headers containing x-b3-traceid from some services and/or X-Datatdog-traceid from others, when this application will emit another call I would like to only send x-b3-traceid and not have a mix of X-datadog and/or x-b3-trace-id.
I thought I could accomplish that by using https://docs.datadoghq.com/tracing/setup_overview/setup/java/?tab=containers#b3-headers-extraction-and-injection
But after trying many different configurations, it looks like I'm still sending headers containing X-Datadog-... only, not matter the configuration
My questions are:
- Can I accomplish what I'm trying to do with -Ddd.propagation.style.extract or inject if so how ?
- How can I know that this extract or inject is using x-b3 or DD and know that the configuration is picked up?

**Comment by randomanderson** [comment]
Yes you can use the extract/inject config flags.  A word on nomenclature:
*inject* is for requests leaving your service.  The context is _injected_ into outgoing requests.
*extract* is for requests received by your service.  The context is _extracted_ from incoming requests.

What you want is to accept everything and only emit B3?  If so:
```
-Ddd.propagation.style.extract=Datadog,B3
-Ddd.propagation.style.inject=B3
```

If you enable debug logging with `-Ddd.trace.debug=true` (warning very verbose), you will see `PropagationStylesToExtract=[xxxxx]` and `PropagationStylesToInject=[xxxxx]` in the log.

**Comment by emirot** [comment]
Hey @randomanderson,

Thank you for the help.

So, I do see this app in datadog web console.

My entrypoint is like so:
```
`ENTRYPOINT ["java","-javaagent:/dd-java-agent.jar", "-jar", "/app/app.jar", "-Ddd.propagation.style.extract=Datadog,B3", "-Ddd.propagation.style.inject=B3", "-Ddd.trace.debug=true"]`
```

But, I don't see propagation in the log or in this configuration log:
```
 [main] INFO datadog.trace.agent.core.StatusLogger - DATADOG TRACER CONFIGURATION {\"version\":\"0.75.0~e75ffb95d\",\"os_name\":\"Linux\",\"os_version\":\"4.14.209-160.339.amzn2.x86_64\",\"architecture\":\"amd64\",\"lang\":\"jvm\",\"lang_version\":\"14.0.2\",\"jvm_vendor\":\"Oracle Corporation\",\"jvm_version\":\"14.0.2+12-46\",\"java_class_version\":\"58.0\",\"http_nonProxyHosts\":\"null\",\"http_proxyHost\":\"null\",\"enabled\":true,\"service\":\"nolan-java\",\"agent_url\":\"http://10.32.144.151:8126\",\"agent_error\":false,\"debug\":false,\"analytics_enabled\":false,\"sampling_rules\":[{},{}],\"priority_sampling_enabled\":true,\"logs_correlation_enabled\":true,\"profiling_enabled\":false,\"dd_version\":\"0.75.0~e75ffb95d\",\"health_checks_enabled\":true,\"configuration_file\":\"no config file present\",\"runtime_id\":\"a6f6a235-6c92-403e-a6f7-dd9f415755e5\",\"logging_settings\":{\"levelInBrackets\":false,\"dateTimeFormat\":\"'[dd.trace 'yyyy-MM-dd HH:mm:ss:SSS Z']'\",\"logFile\":\"System.err\",\"configurationFile\":\"simplelogger.properties\",\"showShortLogName\":false,\"showDateTime\":true,\"showLogName\":true,\"showThreadName\":true,\"defaultLogLevel\":\"INFO\",\"warnLevelString\":\"WARN\",\"embedException\":false}}\n"}
```

**Comment by devinsba** [comment]
Java requires that system properties are defined before the jar name. Try:

```
ENTRYPOINT ["java","-javaagent:/dd-java-agent.jar", "-Ddd.propagation.style.extract=Datadog,B3", "-Ddd.propagation.style.inject=B3", "-Ddd.trace.debug=true", "-jar", "/app/app.jar"]
```

The `-jar` can go anywhere but I think it's more readable right before the jar name

**Comment by emirot** [comment]
Indeed it works better like that... 🤦  thank you @devinsba 

I was testing and so here is what I was doing:

Request from my browser to nolan-java.test.com -> k8s -> istio (creates x-b3-headers) then from that java application I call an external endpoint which is the python server shown above returning the request header received.

The spring controller is like so :

```java
    @GetMapping("/testtracing")
    public String okHttp(@RequestHeader Map<String, String> headers) {
        String s = "";
        for (Map.Entry<String,String> entry : headers.entrySet())
            s += entry.getKey() + ":" + entry.getValue() + "\n";
        String url = "https://mycloudfunction.com/pythonheaders";
        OkHttpClient client = new OkHttpClient();
        Request request = new Request.Builder()
                .url(url)
                .build();

            try (Response response = client.newCall(request).execute()) {
                return s + "===>SENDING HEADERS:" +response.body().string();
            } catch (IOException e) {
                e.printStackTrace();
            }
            return "FAILED";
    }

```

So the header received by calling the java app I get `x-b3-traceid:7d6dca4f71ddf6c160b4ba22bfebfb24` but then in the same function I call the python web server it's receiving only a part of the trace like so` X-B3-Traceid: 60b4ba22bfebfb24` , and also the casing changed?

How can I make sure that traces are correctly carried over services and calls ?
My understand is that the trace should be carried over all calls and at each call a span-id is created and parent-id is created referencing the caller.

**Comment by devinsba** [comment]
So, Datadog only supports 64 bit trace IDs, the source system is using 128 bit IDs. So we truncate the trace ID to what is allowed by Datadog. If you can ensure all of your systems use 64 bit IDs instead then you should get correct traces.

As far as the casing, http headers are case insensitive so it shouldn't be an issue.

**Comment by emirot** [comment]
@devinsba Is that something that could change in the near future?
This 64 bits is for all Datadog APM?

**Comment by bantonsson** [comment]
@emirot The 64 bit id limit is for all of Datadog APM. I can't comment on timelines but we are definitely looking at ways to make the interoperability with other tracers better.

**Comment by emirot** [comment]
@bantonsson @devinsba I was reading through https://docs.datadoghq.com/tracing/setup_overview/open_standards/
If I use the Open telemetry data collector and add a datadog export would it solve this issue or not?

**Comment by bantonsson** [comment]
@emirot The Datadog OpenTelemetry Exporter will also truncate all the IDs to 64 bits since that is what the Datadog APM backend expects. I recently made fix to the B3 encoding/decoding here #2626 that will ensure that the original 128 bit trace ID is being used in the B3 headers for outgoing requests.

**Comment by emirot** [comment]
@bantonsson awesome thank you!! Please let me know when it will be release? in 0.79?

**Comment by bantonsson** [comment]
@emirot Yes, it will be in `0.79.0` which should be released this week 🤞
