### ISSUE TITLE
Labels 404s as a separate resource

### ISSUE THREAD

**Issue by Marcus-Rosti** [DataDog/dd-trace-java#2472]
When using the java agent 0.75 (and older versions as well) datadog labels 404 as a separate resource or endpoint from the one being called. 

So I'd see GET /my/endpoint?withStuff
and also a separate resource 404 with the "errors" form the above endpoint

akka-http 10.2.4
scala 2.13.5
dd-trace-java 0.75.0

**Comment by richardstartin** [comment]
Hi @Marcus-Rosti this is something which is actively being worked on and we will update this issue some progress has been made.

**Comment by cb-narayanan-krishnamurthy** [comment]
Hi @richardstartin , Anything on when we can expect this? Any workaround we can apply on our side to handle this.

**Comment by luca147** [comment]
@richardstartin any news about this?

**Comment by granbestiapop** [comment]
@richardstartin
Any status about this issue?

**Comment by luca147** [comment]
@cb-narayanan-krishnamurthy @Marcus-Rosti I found a solution, I inspect the code in more detail and I found when the reassign of the resource name take place... Only setting this property `-Ddd.trace.Status404Rule.enabled=FALSE` disable this behaviour

**Comment by bm1549** [comment]
Thanks for providing the solution @luca147 !

**Comment by valerauko** [comment]
@bm1549 is there a way to disable that without a JVM option? 

in my case I'm not in control of the JVM's startup, so adding a -D option is not feasible
