### ISSUE TITLE
Configuration inconsistent with other APM languages

### ISSUE THREAD

**Issue by praseodym** [DataDog/dd-trace-java#250]
While setting up APM for a Java project I naively copied the environment configuration from a Python project. However, it turns out the environment variable names are different: for example, the Java APM agent uses `DD_AGENT_HOST` to configure the agent host, whereas the [Python trace client](http://pypi.datadoghq.com/trace/docs/#get-started) expects to find the agent host in `DATADOG_TRACE_AGENT_HOSTNAME`. 

To prevent configuration mistakes, it would be great to have these basic configuration options named consistent across all supported APM languages.

**Comment by tylerbenson** [comment]
Thanks for the report.  That is certainly something we should work on.  I'll see what we can do.

**Comment by randomanderson** [comment]
Python has been changed to use `DD_AGENT_HOST`. Configuration is not consistent
