### ISSUE TITLE
Disable automatic kafka consumer/producer instrumentation when using java-agent

### ISSUE THREAD

**Issue by vg-vaibhav** [DataDog/dd-trace-java#2503]
Hey.
We are using java agent for automatic instrumentation. Our app uses kafka consumer and producer APIs as well runs a Grpc server in background. We are trying to monitor only our grpc traces and not kafka.
Is there any flag or config available where we can disable automatic instrumentation and use only custom traces?

**Comment by richardstartin** [comment]
Hi @vg-vaibhav yes, you can set `-Ddd.integration.kafka.enabled=false` or the environment variable `DD_INTEGRATION_KAFKA_ENABLED=false`.

**Comment by vg-vaibhav** [comment]
Thank you @richardstartin (:  It worked. I wish I could have found this in the documentation.
Thank you for the help. Closing this.

**Comment by richardstartin** [comment]
@vg-vaibhav for future reference, instructions to disable integrations are [here](https://docs.datadoghq.com/tracing/setup_overview/compatibility_requirements/java/#disabling-integrations)
