### ISSUE TITLE
how to sperate dd-trace-java jmxfetch log from host java program?

### ISSUE THREAD

**Issue by KatePang13** [DataDog/dd-trace-java#2504]

**Comment by mcculls** [comment]
Hi, you can use this system property to send the dd-trace-java logging to a separate file:
```
-Ddatadog.slf4j.simpleLogger.logFile=<NEW_LOG_FILE_PATH>
```

**Comment by KatePang13** [comment]
> Hi, you can use this system property to send the dd-trace-java logging to a separate file:
> 
> ```
> -Ddatadog.slf4j.simpleLogger.logFile=<NEW_LOG_FILE_PATH>
> ```

Thanks,  it work.
