### ISSUE TITLE
dd-trace-api 0.76.1 is not released to maven repos

### ISSUE THREAD

**Issue by subash89** [DataDog/dd-trace-java#2557]
When trying to upgrade to dd-trace-ot 0.76.1 it fails to download dd-trace-api 0.76.1. When looked at https://mvnrepository.com/artifact/com.datadoghq/dd-trace-api  it does not have 0.76.1. Looks like this is missed while releasing  ? 

Also the release notes says 0.76 has a known high CPU issue.  (reason for trying 0.76.1). Do you know since which version that high CPU know issue exists   ?(so that we can downgrade to avoid the missing 0.76.1)

**Comment by richardstartin** [comment]
Hi @subash89 the issue was introduced in 0.76.0, but only if your trace agent is older than v7.26.0.

**Comment by subash89** [comment]
Can you please specify which dependency (groupid/artifactid) you talking about as trace agent v7.26.0 ? Because I don;t see any such version for dd-java-agent ?

**Comment by richardstartin** [comment]
@subash89 traces sent from your application back to Datadog are sent via the _trace agent_ which is a Go application deployed on your infrastructure. dd-java-agent 0.76.0 has a performance problem for versions of the trace agent less than 7.26.0. This performance problem does no exist in 0.75.0 of dd-java-agent, however.

**Comment by subash89** [comment]
@richardstartin  thanks for the response. Make sense. Will revert back to 0.75 until the 0.76.1 usable via maven.(because of my original query, dd-trace-api  does not have a released 0.76.1).

**Comment by bantonsson** [comment]
@subash89 The release has been updated and even though the Maven Repository search page doesn't show it, the `0.76.1` artifacts are now on maven central https://repo1.maven.org/maven2/com/datadoghq/dd-trace-api/0.76.1/
