### ISSUE TITLE
AWS Lambda Traces are metrics are sometimes printed in a single line

### ISSUE THREAD

**Issue by Otanikotani** [DataDog/dd-trace-java#2613]
We use AWS Lambda Datadog Forwarder to send traces, logs, and metrics to Datadog. We noticed that sometimes logs in Datadog contain traces messages:
![dd](https://user-images.githubusercontent.com/1468666/114917455-f81a0280-9df3-11eb-9239-761fa3fcf4c6.png)
The ones that start with `{"lambda"` are not actually logs, they are trace messages incorrectly interpreted as logs. 

This happens because when Datadog Forwarder parses Cloudwatch events the logic is as following:
```python
for event in events:
        metric = extract_metric(event)
        trace_payload = extract_trace_payload(event)
        if metric:
            metrics.append(metric)
        elif trace_payload:
            trace_payloads.append(trace_payload)
        else:
            logs.append(event)
```
If the trace fails to be extracted then the trace is added as a log message. The extraction code for traces in Datadog Forwarder:
```python
def extract_trace_payload(event):
    """Extract trace payload from an event if possible"""
    try:
        message = event["message"]
        obj = json.loads(event["message"])
        if not "traces" in obj or not isinstance(obj["traces"], list):
            return None
        return {"message": message, "tags": event[DD_CUSTOM_TAGS]}
    except Exception:
        return None
```
So, if the received Cloudwatch log event "message" field is not a valid json (the `json.loads` fail to parse it) - then the message will be treated as a log, not as a trace. 

Now, in most cases, the JSON in the Cloudwatch log event "message" field is valid. However, for some reason, in some cases, the log event "message" field looks like:

![cloudwatch](https://user-images.githubusercontent.com/1468666/114918095-b047ab00-9df4-11eb-8d62-2d14d40f7e9a.png)

This is not a valid JSON because it has two roots. I am not sure what is the exact reason why this happens but it looks like the trace and the `aws.lambda.enhanced.invocations` messages are _sometimes_ flushed as a single log line into Cloudwatch.

For us it causes following issues:
1. Some of the traces are not properly treated as traces (but as logs) and hence are lost.
2. Some of the metrics are similarly lost.
3. There are log messages in the Datadog console that are not actual log messages. 

# Version/Configuration:
## Datadog Forwarder: 
Version: 3.28.3
Configuration:
```
DD_	datadoghq.com
DD_API_KEY_SECRET_ARN	123
DD_ENHANCED_METRICS	false
DD_FETCH_LAMBDA_TAGS	true
DD_S3_BUCKET_NAME	123
DD_SITE	datadoghq.com
DD_TAGS_CACHE_TTL_SECONDS	300
DD_USE_PRIVATE_LINK	false
DD_USE_VPC	false
EXCLUDE_AT_MATCH	((START|REPORT|END) RequestId: [a-zA-Z0-9]{8}-[a-zA-Z0-9]{4}-[a-zA-Z0-9]{4}-[a-zA-Z0-9]{4}-[a-zA-Z0-9]{12}.+|RequestId: [a-zA-Z0-9]{8}-[a-zA-Z0-9]{4}-[a-zA-Z0-9]{4}-[a-zA-Z0-9]{4}-[a-zA-Z0-9]{12} Process exited before completing request)
```
## Datadog lambda layer:
Version: arn:aws:lambda:us-east-1:464622532012:layer:dd-trace-java:2
Configuration:

DD_JMXFETCH_ENABLED | false
-- | --
DD_LOGS_INJECTION | true
DD_TRACE_ENABLED | true
JAVA_TOOL_OPTIONS | -javaagent:"/opt/java/lib/dd-java-agent.jar" -Dlog4j.logLevel=INFO -DDD_ENV=123 -DDD_SERVICE=123 -DDD_VERSION=123

**Comment by bantonsson** [comment]
Thanks for the bug report @Otanikotani. The traces and metrics should not be logged in the same line. It looks like the `PrintingWriter` that is used by AWS Lambda is not forcing new-lines properly.

**Comment by bantonsson** [comment]
Opened this #2616
