### ISSUE TITLE
Empty dd.env and dd.version in logs for 0.78.3

### ISSUE THREAD

**Issue by kiakimov** [DataDog/dd-trace-java#2653]
Hi!

After upgrade to 0.78.3 we see empty dd.env and dd.version tags in our logs, I suppose they should not be populated if it was not set up for the service, we provided only the DD_SERVICE env variable.
I guess this bug is similar to this https://github.com/DataDog/dd-trace-rb/issues/1003.

Our log record looks like this (LogstashEncoder applied)
```
{
    "@timestamp": "2021-04-23T06:09:13.422Z",
    "@version": "1",
    "message": "xxxxxxx",
    "logger_name": "yyyyyy",
    "thread_name": "zzzzzz",
    "level": "ERROR",
    "level_value": 40000,
    "dd.service": "OUR_SERVICE_NAME_FROM_ENV",
    "dd.env": "",
    "dd.version": ""
}
```

Thank you!

**Comment by bantonsson** [comment]
Hi @kiakimov thanks for the report. You are correct that it's similar to the ruby issue. We should omit the tags if they are empty.

**Comment by kiakimov** [comment]
previous was 0.73.0, env was taken from root datadog agent, set up in properties since it was not overwritten by log records

**Comment by bantonsson** [comment]
Thank you.

**Comment by bantonsson** [comment]
I've opened a PR that avoids injecting empty tags into the logging MDC #2656
