### ISSUE TITLE
Reported requests per second just halved after datadog update

### ISSUE THREAD

**Issue by JoaoHL** [DataDog/dd-trace-java#2703]
So, my team is using Datadog to monitor a Spring Boot application. This week, we made the following updates:
Datadog: 0.46.0 -> 0.79.0
Java: 11 -> 16
Spring boot: 2.4.2 -> 2.4.4

We noticed the graph of the requests per second just halved just right after the deployment, between 9:30 AM and 10 AM:

![Captura de tela de 2021-05-07 09-39-04](https://user-images.githubusercontent.com/5323327/117450816-1c12c480-af18-11eb-9526-cb93d0c47114.png)

The requests/sec are now coincidentally half we were getting before the updates deployment.

I just wonder if we could have broke something with these updates other than the Datadog agent update itself. After some reading, I saw there was a fix in v0.52.0 (https://github.com/DataDog/dd-trace-java/pull/1440) regarding double counting traces. Would that affect this statistic?

**Comment by tylerbenson** [comment]
Closing this in favor of the support ticket discussion.
