### ISSUE TITLE
Trace HTTP client split duplicating services

### ISSUE THREAD

**Issue by fabioaraujopt** [DataDog/dd-trace-java#2809]
When using the parameter 

`DD_TRACE_HTTP_CLIENT_SPLIT_BY_DOMAIN: true`

Datadog creates a new service view for each consumed external api call, which is the intended behaviour.

However when the same external api is an own service for example in a microservices architecture, where each server talks with each other, it **duplicates the services**.

For eg. 
ServiceA --> google.com
Service A --> Service B

Services shown:

- Service A
- Service B
- google.com
- api.serviceB.com

Is that any way to remove/link serviceB and client serviceB?

**Comment by tylerbenson** [comment]
I know it's not a great solution, but the best I can come up with for now is using `dd.service.mapping` found in [config](https://docs.datadoghq.com/tracing/setup_overview/setup/java/?tab=containers#configuration) to map `api.serviceB.com` back to `Service B`.

**Comment by fabioaraujopt** [comment]
Well I tried that, by doing 
```
DD_SERVICE_MAPPING: api.serviceB.com:epace-ps
```
But still it doesn't work. 
Is that anyway of whitelisting a few services?

**Comment by tylerbenson** [comment]
That should work... Can you file a ticket for this with support@datadoghq.com so we can dig into it deeper?
