### ISSUE TITLE
x-b3-headers are not sent as tag to datadog apm

### ISSUE THREAD

**Issue by suresh-naik-tfs** [DataDog/dd-trace-java#2831]
Hi ,

We have the Datadog APM enabled, and we are trying to send http request headers as tag, what we found is some of the headers are not sent.

`dd.trace.header.tags=cookie:cookie,x-b3-traceid:traceid`

the `cookie` header has been sent successfully, but  `x-b3-traceid` has not been sent, is there any limitation on headers ? or any specific headers alone be sent as tag ? 

any help is appreciated 

Thanks,
Suresh

**Comment by lpriima** [comment]
1. Could you please share the full command line how you run your app ? What's the value of `dd.propagation.style.extract` did you set ?
( https://docs.datadoghq.com/tracing/setup_overview/custom_instrumentation/java/#b3-headers-extraction-and-injection )

1. Do you use any kind of proxy ? Does this proxy have instrumentation as well ?

**Comment by suresh-naik-tfs** [comment]
@lpriima  - thanks for responding , her is the list of configs

```
dd.trace.analytics.enabled=true
dd.trace.header.tags=x-b3-traceid:x-b3-traceid,cookie:cookie
dd.http.client.tag.query-string=true
dd.http.server.tag.query-string=true
dd.propagation.style.extract=B3
dd.propagation.style.inject=B3
```

**Comment by devinsba** [comment]
@suresh-naik-tfs so because you are using B3 as your propagation format, if you update to `0.80.0` then the trace ID will automatically be added as a tag: https://github.com/DataDog/dd-trace-java/pull/2690

The way we read the headers we actually don't allow the propagated headers to also be tagged. Once you update to 0.80.0 you can remove the header tags configuration related to the b3 trace ID header

**Comment by suresh-naik-tfs** [comment]
This is one sample request that has x-b3-traceid

```
{
timestamp: "2021-06-17T14:01:20.415Z",
request: {
method: "GET",
uri: "http://xxxxxx",
headers: {
content-length: [
"2"
],
x-datadog-sampling-priority: [
"1"
],
cookie: [
"locale=en_US; pciChecked=Y"
],
x-b3-sampled: [
"1"
],
x-datadog-trace-id: [
"1893214804626039448"
],
x-cuid: [
""
],
x-datadog-sampled: [
"1"
],
x-csid: [
""
],
accept: [
"application/json"
],
x-datadog-parent-id: [
"4502588474897539997"
],
x-b3-spanid: [
"37b22ccbe0c220a6"
],
x-b3-traceid: [
"37b22ccbe0c220a6"
]
}
```

**Comment by suresh-naik-tfs** [comment]
Thank you @devinsba , I will upgrade the version and update this thread with my findings.

**Comment by suresh-naik-tfs** [comment]
@devinsba  - It worked, thanks again.
