### ISSUE TITLE
Adding the request body to the traces 

### ISSUE THREAD

**Issue by suresh-naik-tfs** [DataDog/dd-trace-java#2839]
Referring to the below comment, I understand the trace agent doesn't do it automatically, does it mean there is another way or settings  or workaround to send the request body in the traces ? 

For headers, you can use the `dd.trace.header.tags` system property or `DD_TRACE_HEADER_TAGS` environment variable to automatically set specific headers as tags.  See [Configuration Options](https://docs.datadoghq.com/tracing/setup_overview/setup/java?tab=containers#configuration)

We don't support automatically adding the body to traces

_Originally posted by @randomanderson in https://github.com/DataDog/dd-trace-java/issues/2236#issuecomment-750927159_

**Comment by mcculls** [comment]
Hi @suresh-naik-tfs - are you able to share why you need the request body in the traces? There might be another way to get similar information that doesn't involve the overhead of adding the entire request body (which could be sizeable.)

**Comment by shayn1234** [comment]
@suresh-naik-tfs how can I add manually the full request/response body to datadog traces?
