### ISSUE TITLE
OpenTracing  - FollowsFrom support

### ISSUE THREAD

**Issue by afriedrichsen-cal** [DataDog/dd-trace-java#2846]
Seeing various reports that dd-trace-java does not support FollowsFrom from the OpenTracing API?

Are there any plans to support this or would it be possible to PR-in additional support for References as per the [OpenTracing API specification for Message/Message Bus Scenarios](https://opentracing.io/docs/best-practices/)? Use case would be for message bus or "fan-out" request scenarios, specifically SQS.

Have been able to use dd-trace-java and OpenTracing to successfully propagate context across systems like SQS (even though auto-instrumentation is not officially supported). Running into a situation where parent span is not carried across a distributed trace even though the context is carried across. In my screenshot, you can see spans in a distributed trace which would imply that the context is getting passed across correctly (can provide code or pseudo code to show how I am propagating context from datadog in my SQS messages)

![image](https://user-images.githubusercontent.com/59487332/122814672-24417c00-d29a-11eb-8ed0-378a061f0d0b.png)

Is there something being missed with respect to how Datadog thinks about context propagation? Is the use case described supporting using this library? If not, I am wondering on the ability to [refactor the DDTracer code to support references](https://github.com/DataDog/dd-trace-java/blob/6fd4cc2c6ae17bee332375fb9d34f2d239111bb3/dd-trace-ot/src/main/java/datadog/opentracing/DDTracer.java#L427).

**Comment by devinsba** [comment]
It looks to me like the consumer span (I assume the one on the right) ended up with the top-most trace annotation span as it's parent, which is probably the issue you are referring to. Which span would you want as its parent?

For me both follows-from and parent-child work fine in this scenario so I don't think we would need to support that concept here.

**Comment by afriedrichsen-cal** [comment]
So that's correct. But ideally that's what I want. The topmost span's context is passed from distributed function to function and finished only once processed by the last step.

So my question is why the top-most span doesn't extend over the far right spans? From the pure OpenTracing perspective context propagation seems to be working correctly and my code has the recommend pieces to pass the trace headers from datadog where they need to go to. The far right spans receive their trace context from an SQS message but the idea is that it should be a separate child under the top parent.

![image](https://user-images.githubusercontent.com/59487332/122965835-4268b400-d34e-11eb-89e2-d9091eec33f8.png)

**Comment by afriedrichsen-cal** [comment]
Resolved...silly mistake with try/catch blocks being wrong on spans (of course!). Sorry to trouble!
