### ISSUE TITLE
Insecure Hash Algorithm

### ISSUE THREAD

**Issue by buddyp450** [DataDog/dd-trace-java#2936]
Using `SHA` [here](
https://github.com/DataDog/dd-trace-java/blob/master/dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/context/asm/SerialVersionUIDAdder.java#L427) over something like `SHA-256` is widely considered as insecure for not being as collision-resistant.

```java
/**
   * Returns the SHA-1 message digest of the given value.
   *
   * @param value the value whose SHA message digest must be computed.
   * @return the SHA-1 message digest of the given value.
   */
  // DontCheck(AbbreviationAsWordInName): can't be renamed (for backward binary compatibility).
  protected byte[] computeSHAdigest(final byte[] value) {
    try {
      return MessageDigest.getInstance("SHA").digest(value);
    } catch (NoSuchAlgorithmException e) {
      throw new UnsupportedOperationException(e);
    }
  }
```

[OWASP](https://owasp.org/www-project-top-ten/OWASP_Top_Ten_2017/Top_10-2017_A3-Sensitive_Data_Exposure)
[CWE](https://cwe.mitre.org/data/definitions/327.html)

**Comment by mcculls** [comment]
The use of SHA here is necessary to match the JDK computation of `serialVersionUID` - if a different digest was used then the value wouldn't match the one generated by the JDK, leading to serialization failures.

**Comment by mcculls** [comment]
From the official spec: https://docs.oracle.com/javase/8/docs/platform/serialization/spec/class.html

> If not specified by the class, the value returned is a hash computed from the class's name, interfaces, methods, and fields using the Secure Hash Algorithm (SHA) as defined by the National Institute of Standards
