### ISSUE TITLE
dd-trace-ot doesn't depend on dogstatsd from 0.83 throws ClassNotFound

### ISSUE THREAD

**Issue by nhoughto** [DataDog/dd-trace-java#2949]
It appears from version 0.83 onwards the dependencies for `dd-trace-ot` have been tweaked with `dogstatsd-client` being removed, this is obviously required for the Tracer to function. I expect that the majority of users are using the Tracer via automatic instrumentation via the java-agent and thus aren't using `dd-trace-ot` directly, the java-agent obviously bundles everything appropriately.

Version 0.82 and earlier had correct dependencies to allow using the Tracer without a java agent which is our setup, it would be good if dependencies could be correct to allow this to continue going forward. Otherwise we will have to manually specify the dependencies and risk diverging from what the package is actually expecting.

**Comment by mcculls** [comment]
This has been fixed by #2937 which will be in the next release

In the meantime you can add these dependencies to your `pom.xml` as a temporary workaround:
```
  <dependency>
    <groupId>com.squareup.moshi</groupId>
    <artifactId>moshi</artifactId>
    <version>1.9.2</version>
  </dependency>
  <dependency>
    <groupId>com.datadoghq</groupId>
    <artifactId>java-dogstatsd-client</artifactId>
    <version>2.13.0</version>
  </dependency>
```
