### ISSUE TITLE
DD Trace Java sometimes prints two metrics as a single message.

### ISSUE THREAD

**Issue by Otanikotani** [DataDog/dd-trace-java#2952]
This is a re-appearance of https://github.com/DataDog/dd-trace-java/issues/2613. We noticed that sometimes the Cloudwatch log message with traces for lambdas is intersecting another similar message. It looks like this:

```json
{
    "traces": [
        [
            ...
            {
                "service": "java-aws-sdk",
                "name": "aws.http",
                "resource": "Kinesis.PutRecord",
                "trace_id": "dsf",
                "span_id": "sfgsdfg",
                "parent_id": "sdfgsdf",
                "start": 123,
                "duration": 123,
                "type": "http",
                "error": 0,
                "metrics": {},
                "meta": {
                    "aws.service": "AmazonKinesis",
                    "aws.stream.name": "secret-stream-name",
                    "http.ur{"
                    m
                    ":"
                    name-of-the-metric-super-secret
                    ","
                    v
                    ":1.0,"
                    t
                    ":[],"
                    e
                    ":12354}

```

^ this is a cloudwatch log message we see for some lambdas. I applied formatting to it to make it human readable rather than be a single line (and also omitted names and ids there). You can see that at `"http.ur{"` - the first cloudwatch log message intersects with another one. 

This makes the traces (and metrics) not to be treated correctly when they are forwarded to Datadog. 

We use `arn:aws:lambda:${AWS::Region}:464622532012:layer:dd-trace-java:3` as a lambda layer.

**Comment by bm1549** [comment]
@Otanikotani if this is still an issue, please open up a support ticket at https://www.datadoghq.com/support/

**Comment by Otanikotani** [comment]
@bm1549 sounds good, thank you!
