### ISSUE TITLE
Illegal reflective access by datadog.trace.instrumentation.java.concurrent.NewTaskFor to method java.util.concurrent.AbstractExecutorService.newTaskFor(java.lang.Runnable,java.lang.Object)

### ISSUE THREAD

**Issue by jframeMustaevT** [DataDog/dd-trace-java#2986]
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by datadog.trace.instrumentation.java.concurrent.NewTaskFor to method java.util.concurrent.AbstractExecutorService.newTaskFor(java.lang.Runnable,java.lang.Object)
WARNING: Please consider reporting this to the maintainers of datadog.trace.instrumentation.java.concurrent.NewTaskFor
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

How to hide warning "Illegal reflective access"?

**Comment by mcculls** [comment]
Hi @jframeMustaevT the `NewTaskFor` class mentioned above was removed in 0.70.0 so if you upgrade to at least 0.70.0 (or ideally the latest version) then this warning will disappear.

Also note that this warning doesn't affect the tracing data, so you can ignore it if you don't want to upgrade right now.

**Comment by jframeMustaevT** [comment]
@mcculls  my version 0.75 and still those warnings didn't go away. Anyway, thanks for the information.

**Comment by mcculls** [comment]
I double-checked dd-java-agent-0.75.0.jar and it doesn't contain the `datadog.trace.instrumentation.java.concurrent.NewTaskFor` class

Do you have the startup line from the same log containing the `Illegal reflective access` ?

**Comment by mcculls** [comment]
Thanks, that shows the Java tracer version is 0.67.0 - if you upgrade that to at least 0.70.0 those warnings will disappear

**Comment by jframeMustaevT** [comment]
<dd-trace.version>0.75.0</dd-trace.version>

**Comment by mcculls** [comment]
I don't know where you're setting that version or how it's being used by your deployment process, all I can say is that the actual version of the Java tracer used above is 0.67.0 which is why you're seeing the illegal access warnings

**Comment by jframeMustaevT** [comment]
@mcculls  fieldPath: metadata.labels['tags.datadoghq.com/version']  The default version 0.67 must have been pulled from somewhere because I don't set the version anywhere.

**Comment by jframeMustaevT** [comment]
Can I install a version this way?
template:
  metadata:
    labels:
      tags.datadoghq.com/version: "<0.70.0>"
  containers:
  -  ...
     env:
          - name: DD_VERSION
            valueFrom:
              fieldRef:
                fieldPath: metadata.labels['tags.datadoghq.com/version']

**Comment by mcculls** [comment]
`tags.datadoghq.com/version` is not which version of Java tracer to use - it's used to set the version of the service being traced, for example when using autodiscovery: https://docs.datadoghq.com/getting_started/tagging/unified_service_tagging/?tab=kubernetes

**Comment by jframeMustaevT** [comment]
logs: "dd_version":"0.67.0~9daf9ffe6"

**Comment by jframeMustaevT** [comment]
Picked up JAVA_TOOL_OPTIONS: -javaagent:/usr/local/lib/dd-java-agent.jar -XX:TieredStopAtLevel=1 -Ddatadog.slf4j.simpleLogger.defaultLogLevel=info
[dd.trace 2021-08-05 13:52:11:873 +0000] [main] INFO datadog.trace.agent.tooling.AgentInstaller - Class instrumentation installed
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by datadog.trace.instrumentation.java.concurrent.NewTaskFor to method java.util.concurrent.AbstractExecutorService.newTaskFor(java.lang.Runnable,java.lang.Object)
WARNING: Please consider reporting this to the maintainers of datadog.trace.instrumentation.java.concurrent.NewTaskFor
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[dd.trace 2021-08-05 13:52:12:507 +0000] [main] INFO datadog.trace.agent.core.StatusLogger - DATADOG TRACER CONFIGURATION {"version":"0.67.0~9daf9ffe6","os_name":"Linux","os_version":"5.4.0-1051-azure","architecture":"amd64","lang":"jvm","lang_version":"11.0.9","jvm_vendor":"Azul Systems, Inc.","jvm_version":"11.0.9+11-LTS","java_class_version":"55.0","http_nonProxyHosts":"null","http_proxyHost":"null","enabled":true,"service":"","agent_url":"http://10.222.9.51:8126","agent_error":false,"debug":false,"analytics_enabled":false,"sampling_rules":[{},{}],"priority_sampling_enabled":true,"logs_correlation_enabled":true,"profiling_enabled":false,"dd_version":"0.67.0~9daf9ffe6","health_checks_enabled":true,"configuration_file":"no config file present","runtime_id":"54a24eb3-c8f8-4ffd-a61c-21c103e33fae"}
Importing keystore /opt/avaya/javaapp/store.p12 to /opt/avaya/javaapp/keyStore.pkcs12...
Picked up JAVA_TOOL_OPTIONS: -javaagent:/usr/local/lib/dd-java-agent.jar -XX:TieredStopAtLevel=1 -Ddatadog.slf4j.simpleLogger.defaultLogLevel=info
[dd.trace 2021-08-05 13:52:15:772 +0000] [main] INFO datadog.trace.agent.tooling.AgentInstaller - Class instrumentation installed
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by datadog.trace.instrumentation.java.concurrent.NewTaskFor to method java.util.concurrent.AbstractExecutorService.newTaskFor(java.lang.Runnable,java.lang.Object)
WARNING: Please consider reporting this to the maintainers of datadog.trace.instrumentation.java.concurrent.NewTaskFor
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[dd.trace 2021-08-05 13:52:16:477 +0000] [main] INFO datadog.trace.agent.core.StatusLogger - DATADOG TRACER CONFIGURATION {"version":"0.67.0~9daf9ffe6","os_name":"Linux","os_version":"5.4.0-1051-azure","architecture":"amd64","lang":"jvm","lang_version":"11.0.9","jvm_vendor":"Azul Systems, Inc.","jvm_version":"11.0.9+11-LTS","java_class_version":"55.0","http_nonProxyHosts":"null","http_proxyHost":"null","enabled":true,"service":"","agent_url":"http://10.222.9.51:8126","agent_error":false,"debug":false,"analytics_enabled":false,"sampling_rules":[{},{}],"priority_sampling_enabled":true,"logs_correlation_enabled":true,"profiling_enabled":false,"dd_version":"0.67.0~9daf9ffe6","health_checks_enabled":true,"configuration_file":"no config file present","runtime_id":"ef0d7617-e0ca-41da-9878-39e542029e26"}
Certificate was added to keystore
IMPORT_TRUSTSTORE=/usr/java/lib/security/cacerts
importing well known CAs into the truststore
Picked up JAVA_TOOL_OPTIONS: -javaagent:/usr/local/lib/dd-java-agent.jar -XX:TieredStopAtLevel=1 -Ddatadog.slf4j.simpleLogger.defaultLogLevel=info
[dd.trace 2021-08-05 13:52:20:013 +0000] [main] INFO datadog.trace.agent.tooling.AgentInstaller - Class instrumentation installed
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by datadog.trace.instrumentation.java.concurrent.NewTaskFor to method java.util.concurrent.AbstractExecutorService.newTaskFor(java.lang.Runnable,java.lang.Object)
WARNING: Please consider reporting this to the maintainers of datadog.trace.instrumentation.java.concurrent.NewTaskFor
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[dd.trace 2021-08-05 13:52:20:613 +0000] [main] INFO datadog.trace.agent.core.StatusLogger - DATADOG TRACER CONFIGURATION {"version":"0.67.0~9daf9ffe6

at intervals like these!

**Comment by mcculls** [comment]
Yes, those are all from the 0.67.0 Java Tracer - you need to use version 0.70.0 of the Java Tracer or later to avoid those warning

**Comment by mcculls** [comment]
ie. you need to replace the `/usr/local/lib/dd-java-agent.jar` file with a later version - ideally the latest [0.84.0](https://github.com/DataDog/dd-trace-java/releases/download/v0.84.0/dd-java-agent-0.84.0.jar) release

**Comment by jframeMustaevT** [comment]
right here
javaArgs:
    - "-javaagent:/usr/local/lib/dd-java-agent.jar"
    - "-XX:TieredStopAtLevel=1"
    - "-Ddatadog.slf4j.simpleLogger.defaultLogLevel=info"

**Comment by jframeMustaevT** [comment]
Okay, I got it.
