### ISSUE TITLE
dd.service.mapping concatenating next -D param in label

### ISSUE THREAD

**Issue by pulkitsethi** [DataDog/dd-trace-java#2992]
I am having an issue with `-Ddd.service.mapping`. When there is another -D param afterwards, it will concat with it's own string.

Example:
`-Ddd.service.mapping=mysql:web-mysql -Ddd.version=fa65f2de9837829r8236a4d5677c59cefbbf4926` translates to `web-mysql_Ddd.version=fa65f2de9837829r8236a4d5677c59cefbbf4926`

If `dd.service.mapping is the last -D param, it works as expected. I think there is an issue with parsing of -D params for dd.service.mapping.

**Comment by charliegracie** [comment]
Hi, what version of the Java Tracer are you using? A quick test with the latest version seems to work correctly for me. Thanks

**Comment by mcculls** [comment]
Also could you provide more details about how you're starting the JVM and how you're passing those options in?

For example if there happens to be a stray quote in whichever deployment script/file you're using then the shell could pass `-Ddd.service.mapping=mysql:web-mysql -Ddd.version=fa65f2de9837829r8236a4d5677c59cefbbf4926` as a single option into the JVM, in which case the solution would involve removing the stray quote

**Comment by pulkitsethi** [comment]
@charliegracie DD Agent Version: 7.28.1

@mcculls 
Here is the output from `ps aux`:
```java -server -Xmx2000m -javaagent:/usr/share/datadog/dd-java-agent.jar -Ddd.service.name=web-api -Ddd.service.mapping=mysql:web-mysql -Ddd.version=fa65f2de9837829r8236a4d5677c59cefbbf4926 -Dlog4j.configuration=file:/opt/app/configs/app.log4j.properties -cp /opt/app/lib/* com.company.Server -profile /opt/app/configs/app.properties```

The JAVA_OPTS variable in the sysconfig file looks this:
`JAVA_OPTS="-Xmx2000m -javaagent:/usr/share/datadog/dd-java-agent.jar -Ddd.service.name=web-api -Ddd.service.mapping="mysql:web-mysql" -Ddd.version=fa65f2de9837829r8236a4d5677c59cefbbf4926"`

Which is then used in a startup command template like so:
`ExecStart=sudo -u appuser -g appuser java -server $JAVA_OPTS $LOGGING -cp $CLASSPATH $APP_OPTS`

A slight difference between the output of `ps aux` and the `JAVA_OPTS`, is that parenthesis is included in JAVA_OPTS around the service mapping, but doesn't show up in the output. I don't think that matters, as the Datadog documentation examples don't have it.

When I use all the same commands, but switch the order to make dd.service.mapping as the last dd param, it works properly.

**Comment by devinsba** [comment]
To get the intended results you will need to change the outer quotes on your JAVA_OPTS to single quotes or escape the quotes around service name:

`JAVA_OPTS='-Xmx2000m -javaagent:/usr/share/datadog/dd-java-agent.jar -Ddd.service.name=web-api -Ddd.service.mapping="mysql:web-mysql" -Ddd.version=fa65f2de9837829r8236a4d5677c59cefbbf4926'`

or

`JAVA_OPTS="-Xmx2000m -javaagent:/usr/share/datadog/dd-java-agent.jar -Ddd.service.name=web-api -Ddd.service.mapping=\"mysql:web-mysql\" -Ddd.version=fa65f2de9837829r8236a4d5677c59cefbbf4926"`

**Comment by pulkitsethi** [comment]
@devinsba Thanks for catching that. That was the issue. I just removed the double quotes.

@charliegracie @mcculls @devinsba Really appreciate the quick response.
