### ISSUE TITLE
disable tag interceptors by default

### ISSUE THREAD

**Issue by jodevsa** [DataDog/dd-trace-java#3003]
Hi, 

I'm curious to know the reason behind adding these interceptors. For example the peer.service interceptor is wrong in so many ways and should be disabled by default!

**Comment by devinsba** [comment]
Can you expand on why you think the peer.service interceptor is wrong?

The reason for the tag interceptors is to map between the opentracing conventions and the datadog trace model

**Comment by devinsba** [comment]
@jodevsa would you be able to create another issue for just the `peer.service` concern, there is a conversation going about changing this behavior so a customer case would be good to have. Thanks

**Comment by jodevsa** [comment]
sure :)
