### ISSUE TITLE
More JAX-RS context in instrumentation

### ISSUE THREAD

**Issue by jrogers** [DataDog/dd-trace-java#305]
More of a feature request, but could the class/method names of the invoked resource be added to the span/trace name, or in the attributes? It would provide helpful context.

**Comment by jrogers** [comment]
I could probably create a pull request for this if I get some time.

**Comment by tylerbenson** [comment]
@jrogers Thanks for the suggestion.  Would you mind including a screenshot of the UI, and/or some examples of before/after to help me understand better what you're asking for?

**Comment by jrogers** [comment]
So I'm just comparing jax-rs to our ruby tracing. See screenshots attached. In the ruby traces for rails, the rack and rails traces both have the `Api::DocumentsController#show` in the trace name and in the attributes, which lets me easily know what the code path taken was, without knowing how the http path was routed. In JAX-RS land, you can get this from the ResourceInfo context in a filter for logging. Looking at the instrumentation, I assume this can really just be retrieved from the class and method names of where the Path annotation is. See screenshots attached, using 0.7.0 of java agent.

![ruby_rails](https://user-images.githubusercontent.com/277460/39640680-bd1b7f16-4f99-11e8-8523-4a8a649abc62.png)
![ruby_rack](https://user-images.githubusercontent.com/277460/39640686-c09a6a12-4f99-11e8-9e8e-8302c8532b88.png)
![jaxrs](https://user-images.githubusercontent.com/277460/39640688-c28c92d2-4f99-11e8-9419-d075337cc5dd.png)

**Comment by tylerbenson** [comment]
@jrogers thanks for the suggestion.  Sorry for the delay in implementing it.  Can you take a look at #435?  I believe that should solve your problem.  You can try it out by using the build from the PR:
https://7873-89221572-gh.circle-artifacts.com/0/home/circleci/dd-trace-java/libs/dd-java-agent-0.13.0-SNAPSHOT.jar

Any other feedback or suggestions?

**Comment by jrogers** [comment]
Sorry I didn't get around to testing this, was working on a different project. I can try it out tomorrow.

**Comment by tylerbenson** [comment]
I'm doing the release right now, so you should upgrade to `0.13.0` when it's out.

**Comment by jrogers** [comment]
BTW, tried out 0.14.0, looks good.
