### ISSUE TITLE
Spring boot traces not available

### ISSUE THREAD

**Issue by erikasoncin** [DataDog/dd-trace-java#3051]
Hi :)
We have a Spring Boot application (version 2.0.1.RELEASE) and we've integrated with datadog sdk (version 0.86.0) and we are not able to see the APM traces for http requests, while Apache HTTP Client. gRPC, Spring Scheduling resources are correctly tracked and shown.

We have these dependencies in our gradle:
`    
   implementation group: 'org.springframework.boot', name: 'spring-boot-starter-web', version: '2.0.1.RELEASE'
    implementation group: 'org.springframework.boot', name: 'spring-boot-devtools', version: '2.0.1.RELEASE'
    implementation group: 'com.ibm.etcd', name: 'etcd-java', version: '0.0.14'
    implementation group: 'com.datadoghq', name: 'dd-java-agent', version: '0.86.0'
    implementation group: 'com.datadoghq', name: 'dd-trace-api', version: '0.86.0'
    implementation group: 'com.datadoghq', name: 'dd-trace-ot', version: '0.86.0'
    implementation group: 'org.apache.tomcat.embed',name: 'tomcat-embed-jasper',version: '9.0.11'
`

This is our dockerfile:

`
FROM openjdk:8-jre-slim as Run
RUN mkdir /app
RUN mkdir /app/datadog
RUN apt-get update && apt-get install -y wget
RUN wget -O /app/datadog/dd-java-agent.jar https://dtdg.co/latest-java-tracer
EXPOSE 8080
COPY --from=build /home/gradle/src/build/libs/*.jar /app/application.jar
ARG version
ENV PUBLIC_API_VERSION=$version
ENV DD_LOGS_INJECTION=true
ENV DD_TRACE_SAMPLE_RATE=1
ENV DD_VERSION=$version
ENV DD_PROFILING_ENABLED=true

ENTRYPOINT ["java", "-XX:+UnlockExperimentalVMOptions", "-XX:+UseCGroupMemoryLimitForHeap", "-Djava.security.egd=file:/dev/./urandom", "-javaagent:/app/datadog/dd-java-agent.jar", "-jar","/app/application.jar"]
`

How can we get the http calls tracked properly?
Thanks

**Comment by hugochinchilla** [comment]
Hi @erikasoncin, can you share what you did to solve the issue? (I'm assuming you solved it, as you closed the issue yourself)
