### ISSUE TITLE
Jetty upgrade 9 to 11, and Javax to Jakarta, no traces found

### ISSUE THREAD

**Issue by tnguyenquy** [DataDog/dd-trace-java#3084]
Hi,

We recently upgraded 2 of our services from Jetty 9 to 11, and Java library from Javax to Jakarta. We don't see any traces for our rest endpoints.

So in datadog, under Services tab, and servlet.request is selected, we see nothing under Endpoints section (NO endpoints available in this time frame for ... environment). If we change our time frame to older version, we see all the endpoints. Requests coming in to our services are working fine, we just don't see them.

We are using datadog version 0.80.0. 

Could you take a look?

![Screenshot from 2021-09-21 14-54-47](https://user-images.githubusercontent.com/1173815/134246295-9a9d4e64-fe9a-41cc-b95c-8cc441e40634.png)

**Comment by mcculls** [comment]
Hi @tnguyenquy - we're working on support for Jetty 11 (mostly involves handling the new jakarta.* packages)

**Comment by tnguyenquy** [comment]
Thanks @mcculls, I will keep an eye on your releases. Thank you!

**Comment by tnguyenquy** [comment]
@mcculls , do you have an estimate on when data-dog agent supporting jetty 11 and jakarta. We tried to add jetty 11 and jakarta instrumentation but we couldn't add tests because test libraries (restEasy, jetty-continuation and  dropwizard) they are not jetty 11/jakarta ready.

**Comment by pdenis1** [comment]
Hi @mcculls .. I'm on the same team as @tnguyenquy.  We are quite far down the rabbit hole of upgrading all of our microservices to jetty 11 and jakarta.* namespaces, and it wasn't until we started pushing out to prod that we noticed some metrics getting "wonky".  Comparing latency with previous versions has shown drastic changes, but that's only b/c the metrics aren't getting collected the same way and it is throwing off our numbers.

I took a look at your CONTRIBUTING.md guide, forked your repo and have an MR up to add support for jetty11 and jakarta.  I basically took the javax.ws.rs-2 instrumentation module and replaced jax.rs with jakarta.rs.  We created a custom build and it is working in our test DataDog environment now.  

I'd love to contribute this back to your project!  Would you take a look at our MR and let us know how we should proceed?  We got a little stuck on the testing part FYI.

The MR is here: https://github.com/PasonSystems/dd-trace-java/pull/1

Looking forward to hearing back from you!

**Comment by bm1549** [comment]
This was closed by https://github.com/DataDog/dd-trace-java/pull/3211
