### ISSUE TITLE
Opentracing Redisson implementation reports under main service, instead of creating a redis service

### ISSUE THREAD

**Issue by gokhanoner** [DataDog/dd-trace-java#3086]
I'm using opentracing Redisson client implementation ( https://github.com/opentracing-contrib/java-redis-client ), with opentracing 0.33.0 & Datadog Java agent 0.75.0 as APM agent.

I can see the Redis related traces in Datadog, but under the application service, which is a Java Play framework app. (See below screenshot). Here's my Redisson tracing setup:

```
                RedissonClient redissonClient = Redisson.create(redisConfig);
                this.redissonClient = new TracingRedissonClient(
                        redissonClient,
                        new TracingConfiguration.Builder(GlobalTracer.get())
                                .withSpanNameProvider(RedisSpanNameProvider.PREFIX_OPERATION_NAME("redis."))
                                .build());
```

How can I see this under its own service, like mysql one in this example?
<img width="909" alt="Screen Shot 2021-09-22 at 8 26 38 AM" src="https://user-images.githubusercontent.com/6715308/134373648-adda27f5-39a8-4978-b9e6-abc2858eec2c.png">

**Comment by devinsba** [comment]
Hi @gokhanoner, you should be able to change the service name by adding a tag `DDTags.SERVICE_NAME aka service.name = "redis"`

Your OT library seems to have a builder method `extensionTag(String key, String value)` that you could use for this

**Comment by gokhanoner** [comment]
@devinsba Thanks. After that, would it be also getting the DD config & change `redis` name to whatever I'm changing?

I have this in Datadog conf file -> `dd.service.mapping=mysql:prefix-mysql,redis:prefix-redis`

**Comment by devinsba** [comment]
Yeah, or you could just set it to the correct value directly when you build the client. That's up to you, it's probably easier to share the code if it's non-specific

**Comment by gokhanoner** [comment]
@devinsba I have different prefixed for different environments, so `extensionTag` worked well, I can see it now as a separate service. Many thanks.
