### ISSUE TITLE
Java agent not working with Spring Boot 2 Reactive (Netty)

### ISSUE THREAD

**Issue by ctoestreich** [DataDog/dd-trace-java#313]
When adding the javaagent to the JVM args and running a spring boot 2 application using 

```
<dependency>
     <groupId>org.springframework.boot</groupId>
     <artifactId>spring-boot-starter-webflux</artifactId>
</dependency>
```
The following is logged as the agent is started, but running requests against endpoints doesn't produce any traces in the UI.

```
app_1  | Picked up JAVA_TOOL_OPTIONS: -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -XX:+UseCompressedOops -Djava.awt.headless=true -Djava.net.preferIPv4Stack=true -Dorg.jboss.resolver.warning=true -Dsun.rmi.dgc.client.gcInterval=3600000 -Djboss.as.management.blocking.timeout=700 -Dsun.rmi.dgc.server.gcInterval=3600000 -XX:-UseParallelOldGC
app_1  | [main] INFO datadog.trace.agent.ot.DDTraceOTInfo - dd-trace - version: 0.6.0~0ca84e8
app_1  | [main] INFO datadog.trace.agent.ot.DDTracer - New instance: DDTracer-76494737{ service-name=hello-world, writer=DDAgentWriter { api=DDApi { tracesEndpoint=http://localhost:8126/v0.4/traces } }, sampler=AllSampler { sample=true }, tags={}}
app_1  | [main] INFO datadog.trace.api.DDTraceApiInfo - dd-trace-api - version: unknown
app_1  | [main] INFO datadog.trace.agent.tooling.DDJavaAgentInfo - dd-java-agent - version: 0.6.0~0ca84e8
```
## Agent Up
<img width="830" alt="screen shot 2018-05-07 at 10 47 47 am" src="https://user-images.githubusercontent.com/691357/39711033-21fc73a8-51e4-11e8-9f24-9e9befb02302.png">

## No traces here
<img width="1083" alt="screen shot 2018-05-07 at 10 47 23 am" src="https://user-images.githubusercontent.com/691357/39711034-220d7b3a-51e4-11e8-9ea0-b122ffe88159.png">

**Comment by ctoestreich** [comment]
I can confirm that switching to use the following fixes the traces.

```
<dependency>
	<groupId>org.springframework.boot</groupId>
	<artifactId>spring-boot-starter-web</artifactId>
</dependency>
```

I also tried using a non-flux/mono endpoint when running Netty, but this didn't fix the issue as both of these do not trace when using flux/Netty

```java
 @RequestMapping(value = "/", produces = MediaType.APPLICATION_JSON_UTF8_VALUE)
    public Mono<Response> index() {
        return Mono.just(new Response("OK"));
    }

    @RequestMapping(value = "/home", produces = MediaType.APPLICATION_JSON_UTF8_VALUE)
    public Response index2() {
        return new Response("OK");
    }
```

**Comment by tylerbenson** [comment]
Thanks for your report.  The netty framework is on our short list of things to instrument.  When that is done, we will look into compatibility with Spring Boot 2.

**Comment by duke-cliff** [comment]
What's the roadmap for this? We are having the same issue few of reactive services are kind of blind right now.

**Comment by tylerbenson** [comment]
@duke-cliff @ctoestreich I recently implemented netty support in #352, which was just merged into master.  We will be testing compatibility of that instrumentation with webflux over the next few weeks.  If you'd like to try it out before hand, you can download the snapshot build and enable it by setting this system property at startup: `-Ddd.integration.netty.enabled=true`.  If you do try that out, let me know if it works.
Thanks!

**Comment by ctoestreich** [comment]
I was able to verify that the the APM tracing is not working in a http://micronaut.io application that is based on netty.  I am unable to find anywhere in this repo where the check the actually done for dd.integration.netty.enabled.  Perhaps I missed it, but here is my app stack that isn't working.

https://github.com/tardisoft/micronaut-metrics-example

**Comment by gihad** [comment]
@duke-cliff Can you please test the latest release of the java datadog agent on one of our Spring Webflux apps and one of our Vert.x apps? Please report your findings here and for @tylerbenson to see. Thank you.

**Comment by duke-cliff** [comment]
Okay will do

**Comment by tylerbenson** [comment]
It appears the netty instrumentation was broken in some cases.  I believe this is resolved by a combination of #411 (released in `0.12.0`) and #417 (which will be released in 0.13.0 -- you can find the snapshot build [here](https://oss.jfrog.org/artifactory/oss-snapshot-local/com/datadoghq/dd-java-agent/0.13.0-SNAPSHOT/dd-java-agent-0.13.0-SNAPSHOT.jar)).

We have tests (#434) that verify the netty instrumentation works for webflux on master, but are continuing to improve specific instrumentation for it.

Thanks for your patience.

**Comment by duke-cliff** [comment]
@tylerbenson Just verified it's working properly. 👍

**Comment by duke-cliff** [comment]
This is one more issue, I found the stack could not show our reactive redis calls. I have -Ddd.integration.lettuce.enabled=true in the arguments.

**Comment by tylerbenson** [comment]
@duke-cliff Would you be able to create a separate issue for this?  It would also help if you could provide a small sample app that demonstrates the problem.  Thanks!

**Comment by tylerbenson** [comment]
@duke-cliff @ctoestreich Additional Spring Webflux instrumentation has been added to our latest release: https://github.com/DataDog/dd-trace-java/releases/tag/v0.15.0
