### ISSUE TITLE
Question: Using OpenTelemetry for custom instrumentation

### ISSUE THREAD

**Issue by pp-davy** [DataDog/dd-trace-java#3275]
With OpenTelemetry now having a stable release of their tracing specification. Are there any plans for adopting that over OpenTracing for custom instrumentation? Today I am using the Datadog java agent for auto instrumentation exporting to an agent running in a sidecar.

I would like to add custom trace instrumentation and looking at the Datadog docs it is [suggested to use the OpenTracing libraries](https://docs.datadoghq.com/tracing/setup_overview/custom_instrumentation/java/#add-custom-span-tags).

Ideally, I would like to use the OpenTelemetry libraries instead as there is an intention to move to OpenTelemetry for all our instrumentation in the future.

I have looked at using the [OpenTelemetry auto instrumentation](https://github.com/open-telemetry/opentelemetry-java-instrumentation) javaagent coupled with the [OpenTelemetry collector](https://github.com/open-telemetry/opentelemetry-collector-contrib) exporting to Datadog but unfortunately, the JVM metrics and correlation with infrastructure metrics is not as good as what the Datadog agents provide.

Is this possible? Any advice would be greatly appreciated.

**Comment by reify-marcio-faria** [comment]
As I mentioned on this [comment](https://github.com/DataDog/dd-trace-java/pull/2054#issuecomment-1150494524), the [OpenTracing is deprecated](https://github.com/opentracing/specification/issues/163), so what are the plans to support Opentelemetry as a way to add [custom instrumentation](https://docs.datadoghq.com/tracing/setup_overview/custom_instrumentation/java/)?

We tried to use both, the [Open Telemetry Java Agent](https://github.com/open-telemetry/opentelemetry-java-instrumentation#getting-started) with Datadog Trace Java Agent, but we [had problems](https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/6036#issuecomment-1146384376) with it. Looks like they [don't play well together](https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/1534)

While it doesn't get done, what we can do to circumvent this limitation?

**Comment by bantonsson** [comment]
@reify-marcio-faria As I answered in your other comment, adding support for OpenTelemetry is definitely on our roadmap, but I can't give you any solid dates. The best path forward for now is to stick with using OpenTracing, and use the OpenTelemetry compatibility layer if you want to switch an OpenTelemetry based agent.

**Comment by updevstacks** [comment]
Any progress on this topic?

**Comment by PerfectSlayer** [comment]
Hello,

I can confirm OTel is part of [our roadmap](https://www.datadoghq.com/blog/datadog-supports-opentelemetry-open-source/):

> In addition to these, we are currently preparing to roll out:
> 
> - Support for OTel runtime metrics.
> - Additional improvements to our OTel product and feature support that are under active development, such as 128-bit trace IDs and support for the OpenTelemetry API in Datadog tracers.

I am currently working on it and you can follow the development of the feature from the related PR: #4669 

Best,
Bruce

**Comment by PerfectSlayer** [comment]
You can try using OpenTelemetry for custom instrumentation since 1.10.0 (it keeps improving in 1.11.0 and 1.12.0). 
The support is still in progress, so the public documentation is not yet ready for prime time.
[As stated in the release note](https://github.com/DataDog/dd-trace-java/releases/tag/v1.12.0), you can enable it using the `DD_TRACE_OTEL_ENABLED=true` flag. You will only need to have the `opentelemetry-api` dependency (no sdk nor exporter).

**Comment by febpetroni** [comment]
Sorry for bringing this closed issue back, but I'm trying to use Datadog agent with Opentelemetry, and I have an Exporter for logging spans, which doesn't run when I include the agent. 
Is there a way to run the exporter in this scenario? Or even to have a custom exporter when using Datadog?
