### ISSUE TITLE
log4j1 instrumentation injects incorrect value for dd.span_id

### ISSUE THREAD

**Issue by krosen040** [DataDog/dd-trace-java#3278]
For `dd.span_id`, the log4j1 instrumentation incorrectly injects the trace ID, see [here](https://github.com/DataDog/dd-trace-java/blob/7aed8c331d0e7e297a7da25d3060090a82ce6e30/dd-java-agent/instrumentation/log4j1/src/main/java/datadog/trace/instrumentation/log4j1/LoggingEventInstrumentation.java#L144).

**Comment by bantonsson** [comment]
Not released yet
