### ISSUE TITLE
Opentracing dependencies upgrade to 0.33.0

### ISSUE THREAD

**Issue by nicolas-vivot** [DataDog/dd-trace-java#3293]
Hi,

**Request**
Could you please upgrade dependencies on opentracing to the version 0.33.0 ? (mainly the dd-trace-java i guess)

**Context**
I'm a [Quarkus](https://quarkus.io/) user and have developed an extension to provide native support for the Datadog tracer in Quarkus ecosystem.
As you may know, Quarkus native is running on GraalVM and using your java agent is not an option (at least wasn't on elder versions).
The extension ([available here](https://github.com/quarkiverse/quarkus-datadog-opentracing)) is using the dd-trace-ot and dd-trace-api libraries to start, initialize and register the Datadog tracer as the tracer implementation for opentracing.

Quarkus recently upgraded their dependency on opentracing 0.33.0, bringing incompatibility with datadog libraries that are still on 0.32.0. ([opened issue](https://github.com/quarkiverse/quarkus-datadog-opentracing/issues/67))

In order to keep compatibility between those two and continue to support the Datadog tracer on Quarkus (native mode), i need you to also upgrade to version 0.33.0.

**Changes**

![image](https://user-images.githubusercontent.com/79290619/147422197-e19227a3-aae8-419a-8063-82f62d9a6d62.png)

Some of your classes are using deprecated and now removed methods like Scope.span().
Example: the use of Scope.span() in the [TypeConverter class, line 161](https://github.com/DataDog/dd-trace-java/blob/master/dd-trace-ot/src/main/java/datadog/opentracing/TypeConverter.java).

I'm not sure how many classes are impacted and if it would be complex to do this upgrade, but would be great if you can.

**Comment by devinsba** [comment]
Hi @nicolas-vivot, unfortunately it's not really that simple for us. We have to maintain compatibility with 0.31-0.33, I see that there is an issue with our 0.33 support as you have reported.

https://github.com/DataDog/dd-trace-java/blob/master/dd-trace-ot/src/main/java/datadog/opentracing/TypeConverter.java

This code cannot depend on that method when using 0.33, and our tests should catch this. I'll see if I can find a quick fix that could work for you, though a release will not happen again until after the new year

**Comment by mcculls** [comment]
The GraalVM issue is fixed by https://github.com/DataDog/dd-trace-java/pull/3299 which will be in the 0.93.0 release

You can test the latest  0.93.0-SNAPSHOT by temporarily adding this to your Maven project:
```
  <repositories>
    <repository>
      <id>ossrh-snapshots</id>
      <url>https://oss.sonatype.org/content/repositories/snapshots</url>
      <releases><enabled>false</enabled></releases>
      <snapshots><enabled>true</enabled></snapshots>
    </repository>
  </repositories>
```

**Comment by nicolas-vivot** [comment]
@mcculls 

Thank you for this fix. I've tested it inside the Quarkus extension as well as another project depending on both and the analysis step is now passing as expected.

I will update the Quarkus Datadog extension, adding a note about compatibility versions between Quarkus & Datadog dependencies so that users are not confused.

Thanks again to quick fixing it so fast!
