### ISSUE TITLE
Method 'findConfigurationFile' returns 'no config file present' if file exists

### ISSUE THREAD

**Issue by vladonemo** [DataDog/dd-trace-java#3302]
Hi there.

I believe that there is a bug in the `findConfigurationFile` method of `Config` class. If any of the env or system variable is provided and the file exists, the method returns `no config file present`. However, if the variable is provided and the file does not exist, it returns the path to the file. 

(For internal reference: I have mentioned this in the support case 621176)

Perhaps this only produces misleading log entry and has no impact on the actual config resolution.

**Comment by mcculls** [comment]
Yes that check is wrong - this only affects logging though because the actual loading is done by https://github.com/DataDog/dd-trace-java/blob/master/internal-api/src/main/java/datadog/trace/bootstrap/config/provider/ConfigProvider.java#L224

**Comment by mcculls** [comment]
This will be fixed by https://github.com/DataDog/dd-trace-java/pull/3303 which will be in the next release (0.93.0)
