### ISSUE TITLE
Add support for Couchbase SDK 3.2.4+

### ISSUE THREAD

**Issue by brentryan** [DataDog/dd-trace-java#3339]
Currently Datadog APM does not work with latest version of Couchbase SDK.

https://github.com/couchbase/couchbase-jvm-clients

This stops customers from adopting Datadog APM and newer versions of Couchbase SDK.

**Comment by brentm5** [comment]
We also opened a support ticket for this to better track this.  The ticket number is 654226

**Comment by bm1549** [comment]
We support Couchbase 3.2 as of [v0.108.0](https://github.com/DataDog/dd-trace-java/releases/tag/v0.108.0). Note that the current version is [v1.24.2](https://github.com/DataDog/dd-trace-java/releases/tag/v1.24.2)
