### ISSUE TITLE
Question: Duration of the trace is finishing in first service - Service1 - kinesis - Service2

### ISSUE THREAD

**Issue by SzymonWiedeheft** [DataDog/dd-trace-java#3343]
Hello, I have some problem with propagating root span context to the second service using kinesis. I have followed example repo here: [dd-kinesis](https://github.com/DataDog/dd-trace-java-kinesis-example).
I'm using io.opentracing.Tracer#inject to inject headers to class that implement TextMap(in service1) and io.opentracing.Tracer#extract to extract context span from the message(in service2)

Flame graph looks like this
![datadog](https://user-images.githubusercontent.com/17436809/151342595-2237e04d-0a07-474a-a79e-625ca3f7b092.png)

As you can see root span is completed when spring application is finishing POST request handling. That cause, that duration of the trace is equal to time of handling request(1.27s). Is there a way to display the total duration time(8.4s), or extend root span to second service? 

dependencies used in projects
compile 'com.datadoghq:dd-trace-api:0.92.0'
compile 'io.opentracing:opentracing-api:0.33.0'
compile 'io.opentracing:opentracing-util:0.33.0'

regards

**Comment by bm1549** [comment]
@SzymonWiedeheft thanks for reporting this. If this is still an issue, please open up a support ticket at https://www.datadoghq.com/support/
