### ISSUE TITLE
Add support for play-redis

### ISSUE THREAD

**Issue by jokalli2** [DataDog/dd-trace-java#3379]
`play-redis` is using `rediscala` under the hood. But the package it is using (`com.github.karelcemus:rediscala_2.13`) is a fork of the supported `rediscala` package. If I've understood correctly, it should start working by just adding the forked package name to rediscala muzzle, right?

Do you want me to create a PR to add the fork package to the muzzle?

**Comment by bantonsson** [comment]
Hi @jokalli2, if the `com.github.karelcemus:rediscala_2.13` artifact hasn't changed the names of packages and classes, and is of a supported `rediscala` version, i.e. `1.9`, then you don't have to do anything.
The `muzzle` section in the build-file is just for running verification tests, and is not used during runtime.

**Comment by jokalli2** [comment]
Thanks @bantonsson , that is good information. I'll investigate more. We are not seeing Redis metrics for a service that is using `play-redis`, but we are seeing those on one service that is using `scalaredis` directly. Feel free to close this ticket meanwhile.

**Comment by bantonsson** [comment]
Thanks @jokalli2. If you want to have some more information about what `dd-java-agent` is doing, you can add the command line option `-Ddd.trace.debug=true` or the environment variable `DD_TRACE_DEBUG=TRUE`.
