### ISSUE TITLE
HTTP request spans with error response codes not marked as error.

### ISSUE THREAD

**Issue by tys1019** [DataDog/dd-trace-java#3389]
The current implementation of [HTTP status code tagging](https://github.com/DataDog/dd-trace-java/blob/7d5c68c4fd77be11eebd6049115f1bbaf5e81dc7/dd-trace-core/src/main/java/datadog/trace/core/taginterceptor/TagInterceptor.java#L195) adds the numeric value only of the status code. I'd like to propose that for all error codes (4xx and 5xx), the span is also marked as an error. 

I was picturing something like:
```java
    if (statusCode instanceof Number) {
      var httpStatus = HttpStatus.valueOf((int) statusCode);
      span.setHttpStatusCode(((Number) httpStatus.value()).shortValue());
      span.setErrorFlag(httpStatus.isError());
      return true;
    }
    try {
      var shortStatusCode = Short.parseShort(String.valueOf(statusCode));
      span.setHttpStatusCode(shortStatusCode);
      span.setErrorFlag(HttpStatus.valueOf(shortStatusCode).isError());
    } catch (Throwable ignore) {
    }

**Comment by randomanderson** [comment]
This is currently done in 

`HttpClientDecorator`: https://github.com/DataDog/dd-trace-java/blob/master/dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/decorator/HttpClientDecorator.java#L93

and `HttpServerDecorator`: https://github.com/DataDog/dd-trace-java/blob/master/dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/decorator/HttpServerDecorator.java#L187

**Comment by tys1019** [comment]
Oh interesting. This is the span (`http.request`) that I was looking at. It has a status of 502 but isn't marked as an error.

![image](https://user-images.githubusercontent.com/10453928/153642045-6b681690-283b-4a8b-9a31-e7caf3e41279.png)

**Comment by randomanderson** [comment]
@tys1019 Client spans only get marked with an error for codes in the range 400-499. Conversely, server spans are marked with an error for codes in the range 500-599. The logic is that for 5xx errors, the client didn't do anything wrong so it is not in error.

You can change this behavior by setting `dd.http.client.error.statuses`. See [tracer configuration](https://docs.datadoghq.com/tracing/setup_overview/setup/java/?tab=containers#configuration)

**Comment by tys1019** [comment]
Oooo awesome. Thank you!
