### ISSUE TITLE
Missing jar in Release v0.98.0 breaks https://dtdg.co/latest-java-tracer

### ISSUE THREAD

**Issue by masonelmore** [DataDog/dd-trace-java#3464]
The [Add assets to release](https://github.com/DataDog/dd-trace-java/actions/workflows/add-assets-to-release.yaml) workflow did not run for Release `v0.98.0`. The https://dtdg.co/latest-java-tracer link no longer works because the jar hasn't been added to the release.
```
$ curl --location -i https://dtdg.co/latest-java-tracer
HTTP/2 302
[...]
location: https://github.com/DataDog/dd-trace-java/releases/latest/download/dd-java-agent.jar

HTTP/2 302
[...]
location: https://github.com/DataDog/dd-trace-java/releases/download/v0.98.0/dd-java-agent.jar

HTTP/2 404
[...]
```

**Comment by Michael-St-James** [comment]
I noticed the same issue, I'll close mine in favor of this report.

**Comment by ShivonQ** [comment]
We are seeing the same issue.

**Comment by Michael-St-James** [comment]
I am manually requesting the 0.97.0 version as a temporary fix.

`RUN wget -O dd-java-agent.jar 'https://github.com/DataDog/dd-trace-java/releases/download/v0.97.0/dd-java-agent.jar'`

**Comment by devinsba** [comment]
I delete the release notes for 0.98.0 so the latest link will work again. I think we will have to manually recreate the release

**Comment by MMan0114** [comment]
Yup same issue here, we grab the latest version in our pipeline and can't build anything unless we manually update each service to use an older version.

**Comment by devinsba** [comment]
I've recreated manually in case someone has the redirect cached https://github.com/DataDog/dd-trace-java/releases/tag/v0.98.0

**Comment by devinsba** [comment]
I'm not going to close this to track fixing the underlying issue. Sorry for the issues

**Comment by masonelmore** [comment]
Thanks for the fast response, @devinsba!
