### ISSUE TITLE
Add support for Jedis 4.0+

### ISSUE THREAD

**Issue by andrewmcnamara** [DataDog/dd-trace-java#3467]
We are using Jedis 4.2  and the Redis agent tracing doesn't seem to work. 

From the [Data store compatibility](https://docs.datadoghq.com/tracing/setup_overview/compatibility_requirements/java/#data-store-compatibility) section the latest  version of Jedis 4.2.0 should be supported. 

Looking through the source the `instrumentation` seems to only support `Jedis` up to 3.0. 

Incidentally I  forked this repo and created a new [jedis-4.0](https://github.com/DataDog/dd-trace-java/compare/master...andrewmcnamara:jedis-4.0?expand=1) branch to see what it would take to get Jedis 4 to work.  I blindly copied the  `jedis-3 .0` folder and changed the instrumentation so it would work with 4.0. Unsure whether it works - all of the test cases from `jedis-3,0`  passed.

**Comment by devinsba** [comment]
@andrewmcnamara if you create a PR we would gladly review it

**Comment by andrewmcnamara** [comment]
@devinsba  Thank you., that sounds great. 

 I'll  go through my branch later today and  get it PR  ready.
