### ISSUE TITLE
Issue with datadog java agent

### ISSUE THREAD

**Issue by shanmukha511** [DataDog/dd-trace-java#3476]
Hi All,

when i start my application with datadog java agent getting below error. i have installed datadog java agent in docker file and added JAVA_OPTS env variable in kubernetes manifest file with java agent jar location

**ERROR:**

Exception in thread "main" java.lang.ClassNotFoundException: datadog.trace.bootstrap.AgentBootstrap
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:304)
        at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:401)
FATAL ERROR in native method: processing of -javaagent failed

 A fatal error has been detected by the Java Runtime Environment:
  SIGSEGV (0xb) at pc=0x00007fb07ac8193b, pid=1, tid=0x00007fb079acb640

 JRE version: OpenJDK Runtime Environment (8.0_292-b10) (build 1.8.0_292-b10)
 Java VM: OpenJDK 64-Bit Server VM (25.292-b10 mixed mode linux-amd64 compressed oops)
 Problematic frame:
 C  [libc.so.6+0x2693b]  abort+0x1ed

 Core dump written. Default location: //core or core.1

 An error report file with more information is saved as:
 /tmp/hs_err_pid1.log

 If you would like to submit a bug report, please visit:
   https://github.com/AdoptOpenJDK/openjdk-support/issues

does anyone faced similar issue?

How to fix the issue?

**Comment by mcculls** [comment]
Hi @shanmukha511 - how are you adding `dd-java-agent` to your application?  Have you repackaged it or added it to any of your jars?

**Comment by shanmukha511** [comment]
hi @mcculls 
i have added into docker file using below command

**RUN wget -O dd-java-agent.jar https://dtdg.co/latest-java-tracer**  

 And added JAVA_OPTS env variable in kubernetes manifest file with java agent jar location
 env:
     - name: JAVA_OPTS
        value: -javaagent:dd-java-agent.jar

**Comment by mcculls** [comment]
Is it possible to share the complete set of JVM options used on the command-line?

The `datadog.trace.bootstrap.AgentBootstrap` class is definitely in the jar from https://dtdg.co/latest-java-tracer:
```
> unzip -l dd-java-agent.jar|grep datadog.trace.bootstrap.AgentBootstrap
8078  03-28-2022 21:10   datadog/trace/bootstrap/AgentBootstrap.class
```
so unless you somehow got a bad download I'm not sure why the JVM couldn't find that class.

**Comment by shanmukha511** [comment]
hi @mcculls 

i have changed the directory path for java agent jat.Have fixed the issue

Thanks
