### ISSUE TITLE
Custom Baggage Header Mapping

### ISSUE THREAD

**Issue by Xyaren** [DataDog/dd-trace-java#3542]
Hi,
we are looking for a way to map Http headers to custom baggage names:

for example:
`X-Mycomp-Business-Process-ID` to `mycomp.businessProcessID`
`X-Mycomp-Business-Process-Name` to `mycomp.businessProcessIName`

I tried using DD_TRACE_HEADER_TAGS but this does **not** propagate the values, which is a requirement we have.
I also tried using "ot-baggage" which will propagate the values but does not allow specifying arbitrary headers or target-attributes.

Maybe an additional config attribute could be used in order to specify a baggage mapping ? 

like:

DD_TRACE_ADDITIONAL_BAGGAGE_HEADERS:
`X-Mycomp-Business-Process-ID:mycomp.businessProcessID,X-Mycomp-Business-Process-Name:mycomp.businessProcessName`

Ideally this would also allow defining multiple input headers, like this:
```
X-Mycomp-Business-Process-ID|X-Mycomp-BPID:mycomp.businessProcessID,
X-Mycomp-Business-Process-Name:mycomp.businessProcessName
```

If found #717 kind of related but not quite the same issue I think.

Best Regards,
Xyaren

**Comment by dmsalomon** [comment]
Using spring boot you should be able to write something like this (it's written in kotlin, but you should be able to get the idea):

```kotlin
@Component
@ConditionalOnWebApplication
class HeaderInjectionFilter : OncePerRequestFilter() {
    override fun doFilterInternal(request: HttpServletRequest, response: HttpServletResponse, filter: FilterChain) {
        val span = GlobalTracer.get().activeSpan()
        span.setBaggageItem("mycomp.businessProcessID", request.getHeader("X-Mycomp-Business-Process-ID"))
        span.setBaggageItem("mycomp.businessProcessName", request.getHeader("X-Mycomp-Business-Process-Name"))
        filter.doFilter(request, response)
    }
}
```

**Comment by Xyaren** [comment]
Thanks for the suggestion.
I'm afraid this is not the same, as this would only apply to web applications and not something like kafka events for example.

**Comment by Xyaren** [comment]
@randomanderson Would a PR implementing such a feature be implemented at all ?
 Just probing before I put effort into this :)

**Comment by burningbit** [comment]
@Xyaren is the use-case of baggage item is only for non-root spans?
Shouldn't this be treated as a more generic solution for mapping headers to tags, regardless of the span being root or not?

**Comment by Xyaren** [comment]
> @Xyaren Is the use-case of baggage items only for non-root spans? Shouldn't this be treated as a more generic solution for mapping headers to tags, regardless of the span being root or not?

There is already a way to map to tags in place. 
This is about mapping headers to **tracing** properites, that will also be propagated implicitly.

**Comment by burningbit** [comment]
> There is already a way to map to tags in place. This is about mapping headers to **tracing** properites, that will also be propagated implicitly.

but shouldn't this propagate those tracing properties even if it's a root trace?

Assuming if we set this in the origin service: `-Ddd.trace.header.baggage=some-header:some-tag` this won't be honoured as per current change due to following code:
`  TagContext build() {
    if (valid) {
      if (!DDTraceId.ZERO.equals(traceId)) {
        final ExtractedContext context;
        context =
            new ExtractedContext(
                traceId,
                spanId,
                samplingPriority,
                origin,
                endToEndStartTime,
                baggage,
                tags,
                httpHeaders,
                datadogTags);
        return context;
      } else if (origin != null || !tags.isEmpty() || httpHeaders != null) {
        return new TagContext(origin, tags, httpHeaders);
      }
    }
    return null;
  }`
  
  and even if we set both of these:
   `-Ddd.trace.header.baggage=some-header:some-tag -Ddd.trace.header.tags=some-header:some-tag`  it will still not propagate the same tracing properties further the first config works on baggage and second works on tags.
   
   
 Is the expectation here to set baggage manually once in origin service as mentioned by @dmsalomon above?

**Comment by Xyaren** [comment]
That is not the expectation.
I'm not sure if I can follow...

When the span is created by a HTTP Request, the baggage is mapped. 
This was the use-case I had in mind.

This is specifically for tracing baggage, not arbitrary span properties.

**Comment by burningbit** [comment]
In that case this is a bug, as baggage items are not applied to spans when it's a root span of the trace.

**Comment by Xyaren** [comment]
I assume, this also applies to other "ot-baggage-*" headers ?

**Comment by burningbit** [comment]
> 

Opened an issue #4516 to track issue around baggage handling
