### ISSUE TITLE
exec ${JAVA_HOME}/bin/java -javaagent:/path/to/dd-java-agent.jar com.test.HelloWorld

### ISSUE THREAD

**Issue by nmadhavi33** [DataDog/dd-trace-java#3562]
when I see Profiles/ Runtime Info  in Datadog APM , java.class.path variable value has :/path/to/dd-java-agent.jar

why it's adding dd-java-agent.jar in java.class.path even though it's not passed in classpath

Here, I am using Java HotSpot(TM) 64-Bit Server VM with java 1.8

**Comment by mcculls** [comment]
Hi @nmadhavi33 this is expected, the agent adds itself to the boot classpath when it's attached in order to provide some base types for various transformations - we use an isolating classloader and some package relocation to make sure adding that jar doesn't affect the application

**Comment by mcculls** [comment]
@nmadhavi33 it's always added to the boot classpath - the difference is that Java 8 shows the addition in the `java.class.path` system property while Java 11+ doesn't

**Comment by mcculls** [comment]
https://bugs.openjdk.java.net/browse/JDK-8208064 explains the difference in behaviour:
* Java 8 and below shows attached agent jars at the end of `java.class.path`
* Java 9 and above doesn't

note this doesn't have any effect on the actual application being traced
