### ISSUE TITLE
getting traces, not logs

### ISSUE THREAD

**Issue by pepparole** [DataDog/dd-trace-java#3574]
Hi, followed documentation on datadog, I am getting the traces but i am not able to receive the logs on datadog. and i also enabled profiling. and i cant see anything in profiling tab in datadog. I have enables follwoing env variables. 
DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL=true
DD_PROCESS_AGENT_ENABLED=true
DD_APM_ENABLED=true
DD_LOGS_INJECTION=true
DD_DOGSTATSD_ORIGIN_DETECTION=true
DD_CLUSTER_AGENT_ENABLED=true
DD_ENV=dev
DD_LOGS_ENABLED=trueDD_DOGSTATSD_STATS_ENABLE=true
DD_DOGSTATSD_NON_LOCAL_TRAFFIC=true
DD_PROFILING_ENABLED=true
DD_APM_NON_LOCAL_TRAFFIC=true
DD_VERSION=4.1
DD_AGENT_HOST=hostip(24.35.112.178)
DD_PROFILING_ALLOCATION_ENABLED=true
DD_APPSEC_ENABLED=true
DD_DOGSTATSD_TAG_CARDINALITY=low
DD_SERVICE=my-app
DD_PROCESS_CONFIG_ENABLED=true

Could you help me?

**Comment by bm1549** [comment]
@pepparole if this is still a problem, please open up a support ticket at https://www.datadoghq.com/support/
