### ISSUE TITLE
not able to see in continuous profiler

### ISSUE THREAD

**Issue by pepparole** [DataDog/dd-trace-java#3578]
Hi,

I am getting the Traces in datadog. but these traces are only isready/islive kind of responses. I am not getting any logs and profiler in datadog.
these are the ENV variables I have enabled.
- name: DD_VERSION, - name: DD_SERVICE,  - name: DD_ENV,  - name: DD_AGENT_HOST
            - name: DD_PROCESS_CONFIG_ENABLED
            - name: DD_LEADER_ELECTION
            - name: DD_LOGS_ENABLED
            - name: DD_CLUSTER_AGENT_ENABLED
            - name: DD_NETWORKMONITORING_ENABLED
            - name: DD_PROCESS_AGENT_ENABLED
            - name: DD_APM_ENABLED
            - name: DD_LOGS_INJECTION
            - name: DD_TRACE_DEBUG
            - name: DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL
            - name: DD_DOGSTATSD_ORIGIN_DETECTION
            - name: DD_APM_NON_LOCAL_TRAFFIC
            - name: DD_LOGS_CONFIG_USE_HTTP
            - name: DD_TRACE_DB_CLIENT_SPLIT_BY_INSTANCE
            - name: DD_PROFILING_ENABLED
            - name: DD_PROFILING_ALLOCATION_ENABLED
            - name: DD_RUNTIME_METRICS_ENABLED
            - name: DD_HTTP_CLIENT_TAG_QUERY_STRING
            - name: DD_HTTP_SERVER_TAG_QUERY_STRING
            - name: DD_APPSEC_ENABLED
            - name: DD_TRACE_AGENT_PORT
            - name: DD_LOG_LEVEL
            - name: DD_TRACE_SAMPLE_RATE
            - name: DD_DOGSTATSD_NON_LOCAL_TRAFFIC
            - name: DD_TRACE_HEALTH_METRICS_ENABLED
            - name: DD_DOGSTATSD_STATS_ENABLE
            - name: DD_SYSTEM_PROBE_ENABLED
            - name: DD_DOGSTATSD_ORIGIN_DETECTION
            - name: DD_DOGSTATSD_TAG_CARDINALITY
            - name: DD_PROPAGATION_STYLE_EXTRACT
            - name: DD_PROPAGATION_STYLE_INJECT.
            
Moreover, I have added spanid, traceid in main class of Java-app. and @Trace to all public methods in java app. The only thing i see that JMX metrics but not sure how can i get the logs and continuous profiler.

**Comment by bm1549** [comment]
@pepparole if this is still an issue, please open up a support ticket at https://www.datadoghq.com/support/
