### ISSUE TITLE
No AppSec for ARM64?

### ISSUE THREAD

**Issue by danielstravito** [DataDog/dd-trace-java#3629]
Noticed the following warning on startup after having moved to Graviton2:

```
CRITICAL com.datadog.appsec.powerwaf.LibSqreenInitialization - AppSec could not load libddwaf native library, as a result, AppSec could not start....
```

Yet I see libddwaf being built for arm64 here:
https://github.com/DataDog/libddwaf/actions/runs/2589465271

Some kind of arch detection that's broken?

**Comment by ValentinZakharov** [comment]
Hi @danielstravito. I'm sorry for the issue you faced. We are not officially supported AppSec for arm64 yet. However we are working in it right now and arm64 will be available in future releases as soon as it will be well tested.

**Comment by ValentinZakharov** [comment]
Hi @danielstravito. I'd like to let you know, we recently released new version of Java tracer with AppSec support for arm64 (Linux/MacOS). Please, let us know, if you find any issues while running on ARM.
