### ISSUE TITLE
Rabbitmq consumer does not generate span, but producer does.

### ISSUE THREAD

**Issue by lrwh** [DataDog/dd-trace-java#3679]
ddtrace-java-agent version : v0.104.0

I have two applications, consumer and producer of rabbitmq, which are connected to ddtrace-java-agent at the same time. Trace is generated on the producer , but consumer does not generate span. 

Can I customize traceid to achieve this function? For example, the producer stores the traceid in message, and the consumer parses the message and sets the traceid to make it a child span.

Thanks.

**Comment by bm1549** [comment]
@lrwh if this issue still persists on the latest version of the tracer [v1.24.2](https://github.com/DataDog/dd-trace-java/releases/tag/v1.24.2), please open up a support ticket at https://www.datadoghq.com/support/
