### ISSUE TITLE
Add support for mariadb-java-client 3.x

### ISSUE THREAD

**Issue by bfiorini** [DataDog/dd-trace-java#3777]
Hey there :wave: 
When we upgraded `org.mariadb.jdbc:mariadb-java-client` from `2.7.5` to `3.0.7` (which is the version provided by the latest SpringBoot), we lost all the mariadb driver traces. Looks like the 3.0.x is a complete rewrite of the java driver...
Can you have a look ?
Thanks

**Comment by am312** [comment]
Hi Benjamin.  I think this branch should fix your issue.  Would you like to give it a try and confirm?   These changes should also be merged into an upcoming release if you would rather wait for that.

https://github.com/DataDog/dd-trace-java/archive/refs/heads/andrew.munn/MariaDB-connectorJ-v3-JDBC-fix.zip

**Comment by bfiorini** [comment]
Hey Andrew, I confirm it fixes the issue :+1: the mariadb traces are back with your branch

**Comment by am312** [comment]
Great!

**Comment by mcculls** [comment]
HI @bfiorini this fix has now been released in 0.109.0
