### ISSUE TITLE
HikariCP: connection.getMetaData().getUserName() fires with each JDBC call

### ISSUE THREAD

**Issue by keki** [DataDog/dd-trace-java#379]
Using JDBC instrumentation, a `SELECT USER( )` query is sent with each SQL statement, effectively doubling the number of SQL queries sent by the app.

Screenshot from Datadog APM dashboard, after turning on the java agent. The number of requests is equal to the total number of sql queries sent by the app. 
![image](https://user-images.githubusercontent.com/1006648/41984922-2fe85c54-7a32-11e8-8487-de24cbfc18be.png)

Looking into connection metrics, HikariCP is properly reusing connections from its pool, so the caching mechanism in [[Prepared]StatementInstrumentation.java](https://github.com/DataDog/dd-trace-java/blob/master/dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/PreparedStatementInstrumentation.java#L67) should kick in, and there should be only one `SELECT USER( )` statement for each new connection created.

Play 2.6.13 (Scala), Slick 3.2.1, HikariCP 2.7.8

**Comment by gary-huang** [comment]
@keki thanks for the report! The caching mechanism should be kicking in, which version of the java agent are you using?

**Comment by keki** [comment]
oops, so many version numbers! I forgot to include that one. We're using 0.9.0.

**Comment by gary-huang** [comment]
No worries @keki, it seems that HikariCP creates proxy connection objects, so the actual JDBC connection was not cached, combined with MySQL's JDBC implementation to call the USER() query on every getMetaData.getUserName() call, that is why there is a USER() query for every JDBC query. #382 should fix this, if you want to test out the bugfix and let us know if the issue still persists, here's the [snapshot](https://6179-89221572-gh.circle-artifacts.com/0/home/circleci/dd-trace-java/libs/dd-java-agent-0.11.0-SNAPSHOT.jar) that should address this issue. It is expected that there will be a USER() query for new connections as a side effect of MySQL's implementation. Thanks again!

**Comment by ctoestreich** [comment]
We are also experiencing this issue.  Before I launch into a bunch of rebuilding and deploying images (which isn't trivial in our case) I will wait to see if @keki can provide any test results.

**Comment by ctoestreich** [comment]
@gary-huang This issue was closed without cutting a release or assigning a milestone/release.

**Comment by twbarber** [comment]
@gary-huang Also interested in a release with this issue resolved. We've turned off APM in the meantime.

**Comment by realark** [comment]
Reopening. Will close this issue when the fix ships in the 0.11.0 release early next week.

**Comment by mar-kolya** [comment]
0.11.0 has been released, closing.
