### ISSUE TITLE
Generate X-Ray compliant trace headers

### ISSUE THREAD

**Issue by willarmiros** [DataDog/dd-trace-java#3861]
Today this SDK will generate trace headers with a zero epoch timestamp like so:

```
X-Amzn-Trace-Id: Root=1-00000000-bd862e3fe1be46a994272793;Parent=53995c3f42cd8ad8;Sampled=1
```

Per [X-Ray documentation](https://docs.aws.amazon.com/general/latest/gr/xray.html#limits_xray), trace IDs are only accepted if they are from the last 7 days, as identified by their epoch timestamp, so this trace header is not valid. To fix this issue, the SDK just needs to generate a hex epoch timestamp with the current time, e.g.:

```
X-Amzn-Trace-Id: Root=1-5759e988-bd862e3fe1be46a994272793;Parent=53995c3f42cd8ad8;Sampled=1
```

Originally opened a related issue here: https://github.com/DataDog/browser-sdk/issues/1734

**Comment by mcculls** [comment]
Hi @willarmiros - this has been implemented in #3955 and will be in the next release (0.111.0)
