### ISSUE TITLE
OpenTelemetry custom instrumentation in BETA

### ISSUE THREAD

**Issue by odin-delrio** [DataDog/dd-trace-java#3900]
### Question
Why is **OpenTelemetry** instrumentation still in beta after 2 years? any plans to enable it by default in future APM versions?

### Context
We're developing a library in which we would like to provide some traces information. To do so, we gave it a try to OpenTelemetry, but then realized that it does not work out of the box with the datadog APM agent, as it requires an additional configuration to be enabled:

[From the commit in this repo when this was added](https://github.com/DataDog/dd-trace-java/commit/74e90dd6b636c73f437731cafb2c1c13e7805c82):
```
To enable:
* System Property: `-Ddd.integration.opentelemetry-beta.enabled=true`
* Environment Variable: `DD_INTEGRATION_OPENTELEMETRY_BETA_ENABLED=true`
``` 

As the applications using the agent are out of our control, we can't ensure that flag is enabled, nor we are sure it is a good idea as it is marked as BETA on your side. 
We needed to fallback to OpenTracing, which is deprecated in favor of OpenTelemetry [according to their webpage](https://opentracing.io/), and everything works.

<img width="462" alt="image" src="https://user-images.githubusercontent.com/9112748/192502265-d35c641c-4224-437a-8188-6ca3def9f22a.png">

cc: @anil-n26

**Comment by bantonsson** [comment]
Hi @odin-delrio,

The open telemetry beta integration that you are referring to is for a very old version of OpenTelemetry that is incompatible with the current version. We are looking at supporting the current version of OpenTelemetry, but I can't give you any dates.

Just as you said, you can still use OpenTracing. The deprecation notice is just there to highlight the fact that no new development is being done on the code or the standard, but it is still fully functional.

**Comment by odin-delrio** [comment]
thanks for the quick response! we'll stick to OpenTracing for now then, and we'll keep an eye into this project to be aware when OpenTelemetry support is added :)
