### ISSUE TITLE
java.io.File.deleteOnExit() throws NoClassDefFoundError with 0.109.0

### ISSUE THREAD

**Issue by darylrobbins** [DataDog/dd-trace-java#3912]
Some of the changes in 0.109.0 break `java.io.File.deleteOnExit()`.

## Expected Behavior
We see no exception in 0.108.2 and earlier.

## Current Behavior
We receive the following exception when running the test program on 0.109.0:
```
Exception in thread "main" java.lang.NoClassDefFoundError: Could not initialize class java.io.DeleteOnExitHook
        at java.io.File.deleteOnExit(Unknown Source)
        at com.company.delete.App.main(App.java:10)
```

## Steps to Reproduce

Execute the following test program with the agent enabled using default settings under 0.109.0:
```java
public class App {
    public static void main(String[] args) throws Exception {
        new File("test_file").deleteOnExit();
    }
}
```

**Comment by mcculls** [comment]
Hi @darylrobbins I've tried the steps above with a variety of JVMs but haven't yet reproduced this issue - it could be timing related so I'll keep trying on some other machines.

Meanwhile could you post the JVM and OS versions you tested on.

Could you also try adding the following system property to see if it helps:
```
-Ddd.integration.shutdown.enabled=false
```
this turns off some instrumentation of the JVM's shutdown logic which was enabled in 0.109.0

**Comment by darylrobbins** [comment]
We are using Amazon Corretto 1.8.0_302 but saw it on a few different versions in the Corretto 1.8.0 stream.

**Comment by darylrobbins** [comment]
This was running on Windows. I'll see if I can get more specific information from the team.

**Comment by darylrobbins** [comment]
He was running on Windows 10. He tried both Amazon Corretto 8 and 17.

17:
openjdk version "17.0.4.1" 2022-08-12 LTS
OpenJDK Runtime Environment Corretto-17.0.4.9.1 (build 17.0.4.1+9-LTS)
OpenJDK 64-Bit Server VM Corretto-17.0.4.9.1 (build 17.0.4.1+9-LTS, mixed mode, sharing)

**Comment by darylrobbins** [comment]
We no longer see the exception when specifying `-Ddd.integration.shutdown.enabled=false`

**Comment by mcculls** [comment]
Thanks - I can recreate it on Windows when I use Amazon Corretto 8 and it is related to that new shutdown instrumentation. We'll sort out a patch release with a fix for this issue as soon as possible.

In the meantime you can use `-Ddd.integration.shutdown.enabled=false` as a workaround. Turning off this instrumentation won't affect the traces collected, and it is the safest way to avoid that exception.

**Comment by darylrobbins** [comment]
Is Corretto 8 on Windows part of your standard battery of tests? This change had a significant adverse effect on our production environments and required a considerable time investment to pinpoint the cause to the Datadog agent.

**Comment by mcculls** [comment]
We test on a matrix of different JDKs to try and catch this sort of issue, but unfortunately this one got through.

We'll address that gap going forwards.

**Comment by darylrobbins** [comment]
Thanks! Are there any trace agent-specific signals that we should monitor for in our tests that may identify similar issues in the future before they get to prod? Unfortunately, the typical application signals didn't catch this one.

**Comment by mcculls** [comment]
This snapshot should avoid the issue: https://output.circle-artifacts.com/output/job/7a24ff5e-c114-4f3e-b062-7915ebbec798/artifacts/0/libs/dd-java-agent-0.110.0-SNAPSHOT.jar (built from https://github.com/DataDog/dd-trace-java/pull/3913)

wrt. `trace agent-specific signals`... as well as checking the same test assertions pass with the tracer attached you could scrape the logs to see if there were any additional exceptions compared to when running without the tracer. That's what a number of our 'smoke' tests do - they run sample applications and check behaviour as well as if there were unexpected exceptions in the logs. Unfortunately this issue still snuck through, but we'll close that gap.
