### ISSUE TITLE
Support for OpenSearch instrumentation

### ISSUE THREAD

**Issue by andrewparmet** [DataDog/dd-trace-java#3944]
I'm going to be instrumenting some client calls to OpenSeach manually since they don't seem to pick up a service name. Any chance that can be integrated by default and I can migrate over (i.e., remove my custom spans)?

Thanks!

**Comment by bm1549** [comment]
Opensearch support was released in [v1.16.0](https://github.com/DataDog/dd-trace-java/releases/tag/v1.16.0). Note that the latest version is [v1.24.2](https://github.com/DataDog/dd-trace-java/releases/tag/v1.24.2)
