### ISSUE TITLE
How to attach service type "web" in APM and trace view for a specific span

### ISSUE THREAD

**Issue by martin2176** [DataDog/dd-trace-java#4030]
Datadog APM and traces view identifies the services as 4 types: db,web,cache,custom based on the span.
 However I am unable to find a way to assign the required type to span so that Datadog APM will identify it correclty and display it appropriately.
I have used span.setTag("type", "web");
But no luck. APM view and trace view identifies it as custom instead of web
The openweathermap icon shows as type:custom
![image](https://user-images.githubusercontent.com/14482998/195926504-210927b3-b841-445f-b7cb-88a92c54d44b.png)

How can I change it to web? 
Here is code I am using

Span span = tracer.buildSpan("call.saas.weatherapi")
            .withTag(DDTags.SERVICE_NAME, "openweathermap")
            .withTag(DDTags.RESOURCE_NAME, "web.request")
            .start();
		try (Scope scope = tracer.activateSpan(span)) {
            span.setTag("type", "web");
		//code to trace
		String result = response.getBody();
		log.info("Weather API response - {}", result);
		return result;
		}
		finally {
            span.finish();

**Comment by nayeem-kamal** [comment]
Hi @martin2176,
The recognized tag key/value pairs you are looking for are located in [datadog.trace.api.DDTags](https://github.com/DataDog/dd-trace-java/blob/4d59186ae2da55d5f73f466b53a031444a4d5398/dd-trace-api/src/main/java/datadog/trace/api/DDTags.java#L5)  and [datadog.trace.api.DDSpanTypes](https://github.com/DataDog/dd-trace-java/blob/4d59186ae2da55d5f73f466b53a031444a4d5398/dd-trace-api/src/main/java/datadog/trace/api/DDSpanTypes.java#L5)

`  public static final String HTTP_SERVER = "web";`
`  public static final String SPAN_TYPE = "span.type";`

I would recommend trying `span.setTag("span.type","web");` and see if this resolves your issue.

**Comment by martin2176** [comment]
> span.setTag("span.type","web");

That worked beautifully!
much appreciated. I can see the span having a type (and icon) of web

![image](https://user-images.githubusercontent.com/14482998/195950843-93c7a1a3-03c9-4484-8f70-f695c6d9aca0.png)
