### ISSUE TITLE
parent_id not visible in indexed trace

### ISSUE THREAD

**Issue by martin2176** [DataDog/dd-trace-java#4036]
I couldn't find an APM repo to post this. Hence posting it in one of the language specific apm repo hoping someone knows the answer already
Why is parent_id not visible in indexed spans (only shows span_id and trace_id)

While ingested spans (live view) shows parent, span and trace id
https://github.com/DataDog/datadog-agent/issues/13907#issue-1411729377

**Comment by bm1549** [comment]
@martin2176 if this issue still persists, please open up a support ticket at https://www.datadoghq.com/support/
