### ISSUE TITLE
Use default service name for Spring RabbitMQ consumer

### ISSUE THREAD

**Issue by mlichtblau** [DataDog/dd-trace-java#4047]
Similar to #855, I would like to use the default service name in applications instrumented with springamqp.
Like in the [`RabbitDecorator`](https://github.com/DataDog/dd-trace-java/blob/master/dd-java-agent/instrumentation/rabbitmq-amqp-2.7/src/main/java/datadog/trace/instrumentation/rabbitmq/amqp/RabbitDecorator.java) of the rabbitmq instrumentation, one could use the `Config.get().getServiceName()`
Can I open a PR for this?

**Comment by mcculls** [comment]
If you set this system property:
```
-Ddd.rabbitmq.legacy.tracing.enabled=false
```
or this environment variable:
```
DD_RABBITMQ_LEGACY_TRACING_ENABLED=false
```
then you'll get the default service name for the producing and consuming spans, and a new "time-in-queue" span which has a service of "rabbitmq".

**Comment by mlichtblau** [comment]
Hey, 
thank you very much for your quick reply.
 I tried both of your suggestions, but it didn't work. 
To be clear, I am using the [**spring**-rabbit](https://github.com/DataDog/dd-trace-java/tree/master/dd-java-agent/instrumentation/spring-rabbit) instrumentation and not the [rabbitmq-amqp-2.7](https://github.com/DataDog/dd-trace-java/tree/master/dd-java-agent/instrumentation/rabbitmq-amqp-2.7) instrumentation.
In the latter, I found [the code path](https://github.com/DataDog/dd-trace-java/blob/c0e281a6397388436da82222d38e03c4032fdcf6/dd-java-agent/instrumentation/rabbitmq-amqp-2.7/src/main/java/datadog/trace/instrumentation/rabbitmq/amqp/RabbitDecorator.java#L37) I think you are referring to.
This would be perfect and exactly what I need.
However, I cannot find that in the spring-rabbit instrumetation, [only the component](https://github.com/DataDog/dd-trace-java/blob/c0e281a6397388436da82222d38e03c4032fdcf6/dd-java-agent/instrumentation/spring-rabbit/src/main/java/datadog/trace/instrumentation/springamqp/RabbitListenerDecorator.java#L19) is set here.
My proposal / feature request would be to update the spring-rabbit part to behave like the rabbitmq-amqp-2.7 part.
Thanks again for your, help!

**Comment by mcculls** [comment]
Hi @mlichtblau - the spring-rabbit instrumentation doesn't set a service name, which means that it will pick up the service name from the surrounding parent span, if one exists. If there is no parent span then it will use the service name configured for the application.

What service name are you seeing for your span and what is the component tag for that span?

**Comment by mlichtblau** [comment]
Thanks for your clarification!
So I inspected my active span in the debugger using:
```
Tracer tracer = GlobalTracer.get();
tracer.activeSpan().context().delegate
```
In my active span I can see:
```
parentServiceName = "rabbitmq"
serviceName = "rabbitmq"
resourceName = "amqp.consume {redacted}"
operationName = {UTF8BytesString@22476} "amqp.consume"
```
Via
```
tracer.activeSpan().context().delegate.trace.rootSpan.context()
```
i see:
```
parentServiceName = "null"
serviceName = "rabbitmq"
resourceName = "basic.deliver {redacted}"
operationName = {UTF8BytesString@22507} "amqp.command"
```
Via
```
tracer.scopeManager().tracer
```
i see:
```
serviceName = "myServiceName"
```

Component name taken from DataDog trace view is `rabbitmq-amqp`

Do you think using the system property did not work or was overwritten somewhere? Is there a way to check this from inside the debugger?

**Comment by mlichtblau** [comment]
`System.getProperty("dd.rabbitmq.legacy.tracing.enabled")` returns `false`

**Comment by mcculls** [comment]
Did you add the system property to both the publishing and consuming JVMs?

**Comment by mcculls** [comment]
Also how are you setting the system property - on the JVM command-line or via `System.setProperty` ?

**Comment by mlichtblau** [comment]
`-Ddd.rabbitmq.legacy.tracing.enabled=false` on the command line.
Just as a sanity check i tried setting it to true on the command line and `System.getProperty("dd.rabbitmq.legacy.tracing.enabled")` is true.

**Comment by mlichtblau** [comment]
Just be sure, that I understand the current situation correctly: 
Currently my problem is, that  rabbitmq-amqp-2.7 creates the root span:
```
parentServiceName = "null"
serviceName = "rabbitmq"
resourceName = "basic.deliver {redacted}"
operationName = {UTF8BytesString@22507} "amqp.command"
```
which has serviceName rabbitmq and then spring-rabbit creates a new span `amqp.consume` which has the other span as its parent and therefore also has service `rabbitmq`?
So I need to change the service of my first span `basic.deliver` in order to have `amqp.consume` be the same service?
I would think `rabbitmq` is fine for `basic.deliver`, but not for `amqp.consume` so maybe, spring-amqp should not pick the service from its surrounding span?
What do you think?

**Comment by mcculls** [comment]
the `basic.deliver` span should be getting the app's service name when `-Ddd.rabbitmq.legacy.tracing.enabled=false` is set - the only explanation I can think of at the moment is that you're using a version of the tracer before 0.93.0 (where this feature was added)

**Comment by mlichtblau** [comment]
oh my, I am sorry @mcculls this is it. Apparently I have only checked the dd-java-agent version in the ci-pipeline. Main agent was still on 0.91.0 and update fixed it. Sorry for taking your time and thank you very much for your support!

**Comment by nikita2206** [comment]
May I ask you to document these properties in the official DataDog docs?
It will also help DataDog's sales engineers, as they seemed to not be aware this exists.
