### ISSUE TITLE
APM Traces are not sending from Java Clients

### ISSUE THREAD

**Issue by parasappafluke** [DataDog/dd-trace-java#4079]
Hi,
We are using DD helm chart version 3.1.3 with latest 7.39.0-jmx agent docker image and latest tracer-agent. We started facing APM traces are not sending to DD. Below are the error from java clients.
**Java Clients Output**
`
[dd.trace 2022-10-24 11:48:07:924 +0000] [StatsD-Sender-1] WARN datadog.communication.monitor.DDAgentStatsDConnection - IOException in StatsD client - /var/run/datadog/dsd.socket java.io.IOException: Resource temporarily unavailable (Will not log errors for 5 minutes)

[dd.trace 2022-10-24 11:48:56:374 +0000] [OkHttp http://172.22.0.81:8126/...] WARN com.datadog.profiling.uploader.ProfileUploader - Failed to upload profile, received empty reply from http://172.22.0.81:8126/profiling/v1/input after uploading profile (Will not log errors for 5 minutes)

[dd.trace 2022-10-24 11:50:10:419 +0000] [dd-trace-processor] WARN datadog.trace.agent.common.writer.ddagent.DDAgentApi - Error while sending 2 (size=3KB) traces to the DD agent. Total: 56523, Received: 56523, Sent: 0, Failed: 56523. java.net.SocketTimeoutException: connect timed out (Will not log errors for 5 minutes)

[dd.trace 2022-10-24 11:53:56:375 +0000] [OkHttp http://172.22.0.81:8126/...] WARN com.datadog.profiling.uploader.ProfileUploader - Failed to upload profile, received empty reply from http://172.22.0.81:8126/profiling/v1/input after uploading profile (Will not log errors for 5 minutes)

[dd.trace 2022-10-24 11:54:07:924 +0000] [StatsD-Sender-1] WARN datadog.communication.monitor.DDAgentStatsDConnection - IOException in StatsD client - /var/run/datadog/dsd.socket java.io.IOException: Resource temporarily unavailable (Will not log errors for 5 minutes)

[dd.trace 2022-10-24 11:55:10:730 +0000] [dd-trace-processor] WARN datadog.trace.agent.common.writer.ddagent.DDAgentApi - Error while sending 2 (size=3KB) traces to the DD agent. Total: 56584, Received: 56584, Sent: 0, Failed: 56584. java.net.SocketTimeoutException: connect timed out (Will not log errors for 5 minutes)

[dd.trace 2022-10-24 11:58:56:378 +0000] [OkHttp http://172.22.0.81:8126/...] WARN com.datadog.profiling.uploader.ProfileUploader - Failed to upload profile, received empty reply from http://172.22.0.81:8126/profiling/v1/input after uploading profile (Will not log errors for 5 minutes)

[dd.trace 2022-10-24 12:00:11:039 +0000] [dd-trace-processor] WARN datadog.trace.agent.common.writer.ddagent.DDAgentApi - Error while sending 2 (size=3KB) traces to the DD agent. Total: 56645, Received: 56645, Sent: 0, Failed: 56645. java.net.SocketTimeoutException: connect timed out (Will not log errors for 5 minutes)

[dd.trace 2022-10-24 12:15:56:375 +0000] [OkHttp http://172.22.0.81:8126/...] WARN com.datadog.profiling.uploader.ProfileUploader - Failed to upload profile, received empty reply from http://172.22.0.81:8126/profiling/v1/input after uploading profile (Will not log errors for 5 minutes)

[dd.trace 2022-10-24 12:20:12:285 +0000] [dd-trace-processor] WARN datadog.trace.agent.common.writer.ddagent.DDAgentApi - Error while sending 2 (size=3KB) traces to the DD agent. Total: 56889, Received: 56889, Sent: 0, Failed: 56889. java.net.SocketTimeoutException: connect timed out (Will not log errors for 5 minutes)

[dd.trace 2022-10-24 12:21:56:374 +0000] [OkHttp http://172.22.0.81:8126/...] WARN com.datadog.profiling.uploader.ProfileUploader - Failed to upload profile, received empty reply from http://172.22.0.81:8126/profiling/v1/input after uploading profile (Will not log errors for 5 minutes)
`

**`agent status` command output**
`=========
APM Agent
=========
  Status: Running
  Pid: 1
  Uptime: 281174 seconds
  Mem alloc: 9,132,576 bytes
  Hostname: i-0ed8ac1069c3cd0d4
  Receiver: 0.0.0.0:8126
  Endpoints:
    https://trace.agent.datadoghq.com

  Receiver (previous minute)
  ==========================
    No traces received in the previous minute.`

Are we missing any configuration to config for helm chart?

Thanks 
Parasappa

**Comment by bm1549** [comment]
@parasappafluke if this issue still persists on the latest version of the tracer [v1.24.2](https://github.com/DataDog/dd-trace-java/releases/tag/v1.24.2), please open up a support ticket at https://www.datadoghq.com/support/
