### ISSUE TITLE
How can I disable the dd tracer in code?

### ISSUE THREAD

**Issue by jeacott1** [DataDog/dd-trace-java#408]
I am not using the jvm agent.
I am trying to manually use dd-trace-ot 0.11.0 in a spring boot application along with opentracing-spring-cloud-starter.

I want to disable the datadog agent in various profiles and had thought it would be as simple as not instantiating the DDAgentWriter and Tracer beans -ie

```
 @Bean
    @ConditionalOnProperty(value = "opentracing.datadog.enabled", havingValue = "true", matchIfMissing = false)
    public io.opentracing.Tracer tracer() {
              DDAgentWriter writer = new DDAgentWriter(...);
              Sampler sampler = new AllSampler();
              Tracer tracer = new DDTracer("serviceName", writer, sampler);
              return tracer;
    }
```

unfortunately it turns out that not declaring this bean makes no difference because there's a DDTracerResolver that creates one anyway.  the only thing I can find is with the agent  to prevent it from starting the Tracer is to set system vars 
dd.integrations.enabled=false
or equivalent environment variables, but these doesnt appear to have any effect when trying to use this in a manual world.

I can also use a system var or equivilant env var of
tracerresolver.disabled=true  

which does actually work (when I pull the latest TracerResolver from opentracing) but also stomps on everything else and requires external config.

how can I prevent the DDTracer from instantiating without setting System vars or env vars, and without removing the dependency from my code altogether?

*update - I have figured out that I can set dd.writer.type=LoggingWriter
and while that works more or less for my purposes, it vomits a ridiculous amount of log in INFO!!

thanks in advance.

**Comment by jeacott1** [comment]
@tylerbenson yeah that's exactly what I have done. 2hrs vs 10 minutes to run tests just from log output!
would be better to be able to just disable the mech entirely though.

thanks.

**Comment by tylerbenson** [comment]
> there's a DDTracerResolver that creates one anyway
I'm confused... Where is the `TracerResolver` being called?  `DDTracerResolver` shouldn't matter unless you're also using `TracerResolver`.

Are you using the `NoopTracer` when that condition is false?

If you want, you can also move the conditional to provide an instance of the `datadog.trace.common.writer.Writer` interface.  When enabled, return the `DDAgentWriter` you're using right now, if not, provide a no-op implementation.

Do you have any specific suggestions for things we should change/implement?

**Comment by jeacott1** [comment]
hmmm, I have tried creating a noOp tracer bean, and even tried manually registering it. makes no difference. the dd Tracer still starts.

```
	@Bean
	public io.opentracing.Tracer noOpTracer() {
		Tracer tracer =  NoopTracerFactory.create();
		GlobalTracer.register(tracer);
		return tracer;
	}
``` 

this was pretty much the first thing I tried after realising the Tracer was starting on its own.

What I'd like is a way to disable the TracerResolver and to allow me to manually provide the bean I want.

What would be even better (not a datadog lib issue) would be to be able to selectively disable instrumentation altogether.

**Comment by jeacott1** [comment]
hmmm, I have tried creating a noOp tracer bean, and even tried manually registering it. makes no difference. the dd Tracer still starts.

```
	@Bean
	public io.opentracing.Tracer noOpTracer() {
		Tracer tracer =  NoopTracerFactory.create();
		GlobalTracer.register(tracer);
		return tracer;
	}
``` 

this was pretty much the first thing I tried after realising the Tracer was starting on its own.

What I'd like is a way to disable the TracerResolver and to allow me to manually provide the bean I want.

What would be even better (not a datadog lib issue) would be to be able to selectively disable instrumentation altogether.

**Comment by tylerbenson** [comment]
Are you sure you're not running the `dd-java-agent`?  ;-)

I'm trying to understand what is calling the [resolveTracer()](https://github.com/opentracing-contrib/java-tracerresolver/blob/master/opentracing-tracerresolver/src/main/java/io/opentracing/contrib/tracerresolver/TracerResolver.java#L63) method.  Perhaps there's some spring magic that is initializing the TraceResolver automatically?  Are you using Spring Sleuth?

Our automatic instrumentation (provided by the javaagent) can be disabled selectively.  Not sure that helps though since you're not using that.

**Comment by jeacott1** [comment]
I'm definitely not using the java agent. plain spring boot application  with the following related deps:

the opentracing-tracerresolver is what is calling the resolveTracer() and I'm explicitly pulling in the latest here because it has a hook to disable it, but its not appropriate for my case as its global, and requires external config (env or system vars)

```
  <dependency>
            <groupId>com.datadoghq</groupId>
            <artifactId>dd-trace-ot</artifactId>
            <version>0.11.0</version>
        </dependency>

        <dependency>
            <groupId>io.opentracing.contrib</groupId>
            <artifactId>opentracing-tracerresolver</artifactId>
            <version>0.1.4</version>
        </dependency>

        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-openfeign</artifactId>
            <version>1.4.5.RELEASE</version>
        </dependency>

        <dependency>
            <groupId>io.opentracing.contrib</groupId>
            <artifactId>opentracing-spring-jaeger-cloud-starter</artifactId>
            <version>0.2.0</version>
        </dependency>

       <dependency>
            <groupId>io.opentracing.contrib</groupId>
            <artifactId>opentracing-redis-lettuce</artifactId>
            <version>0.0.2</version>
        </dependency>

        <dependency>
            <groupId>io.opentracing.contrib</groupId>
            <artifactId>opentracing-elasticsearch6-client</artifactId>
            <version>0.0.5</version>
        </dependency>
```

jaeger is here only for local testing and is easy to disable via code or config on demand.

**Comment by tylerbenson** [comment]
@jeacott1 ok, I've added a setting to disable our trace resolver.  Please take a look at #415.

**Comment by jeacott1** [comment]
it would also be great if all the INFO logging could be changed to TRACE for the logwriter output.

**Comment by jeacott1** [comment]
my usecase isnt common?
the dd agent doesn't cover many of the services I need to trace (feign, elasticsearch, lettuce redis, manual span roots from scheduled jobs etc), I'd suggest many people will need to use the Manually applied version of this. As such it should not log to datadog from test or other profiles, and it shouldnt require special intervention to prevent it from excessive logging during routine build tests. 
fwiw Travis took 2 hours to build and test just one project I had instrumented with the dd lib +  dd.writer.type=LoggingWriter, and it gave up logging a looong time before that as the log had vastly exceeded its 4Mb limit. 

after setting 
logging.level.datadog.trace.common.writer.LoggingWriter=ERROR
it took just 10 minutes with everything else on debug.

So I think there's a strong argument for changing the INFO to TRACE. 
Now that there's an option to turn it off entirely, that need is somewhat mitigated, but I still think its such a vast amount of data that it just swamps anything anyone might reasonably want in an INFO log.

**Comment by tylerbenson** [comment]
The intended use case for `LoggingWriter` is for debug purposes and displaying the spans to the console.  We can certainly consider adding a no-op writer, since that's what you really want.  Would you mind creating a separate issue for that if it is still important to you?

Now that that branch is merged into master, you can download the latest snapshot from the [snapshot repo](https://oss.jfrog.org/webapp/#/artifacts/browse/simple/General/oss-snapshot-local/com/datadoghq/dd-java-agent/0.12.0-SNAPSHOT/dd-java-agent-SNAPSHOT.jar)

**Comment by jeacott1** [comment]
exactly - debug!=info. 
I can create another issue. I think it will bug enough other folk it should be changed to at least DEBUG.

Cheers.

**Comment by jeacott1** [comment]
well, now that I have a way to disable the auto creation, I can create my own noop writer. so not really a need.
