### ISSUE TITLE
`TaintedMapTest` is flaky 

### ISSUE THREAD

**Issue by richardstartin** [DataDog/dd-trace-java#4098]
https://app.circleci.com/pipelines/github/DataDog/dd-trace-java/17403/workflows/4fb2ea4d-9b26-4855-8493-00684d396803/jobs/415507

**Comment by manuel-alvarez-alvarez** [comment]
We've opened a PR to solve this issue:

https://github.com/DataDog/dd-trace-java/pull/4100

**Comment by manuel-alvarez-alvarez** [comment]
Merged!, don't hesitate to reopen the issue if you see the test flaky again

**Comment by bantonsson** [comment]
![And there was much rejoicing](https://user-images.githubusercontent.com/805830/194008426-928040a4-7b43-4066-8834-705e9ae7ccae.gif)
