### ISSUE TITLE
Add support for jdbc-secretsmanager connection URLs in JDBCConnectionUrlParser

### ISSUE THREAD

**Issue by aldoms** [DataDog/dd-trace-java#4209]
Connection strings using [jdbc-secretsmanager:](https://github.com/aws/aws-secretsmanager-jdbc) are not correctly parsed by `JDBCConnectionUrlParser`, thus returning a `DEFAULT` DbType. This is causing spans to have different tags from connections using only `jdbc:`.

Sample connection string `jdbc-secretsmanager:mysql://example.com:3306`

**Comment by mcculls** [comment]
I believe this should be fixed by @ymengesha's changes in #4112 which I'm planning to merge via #4215
