### ISSUE TITLE
Change output from LoggingWriter from INFO to TRACE or DEBUG

### ISSUE THREAD

**Issue by jeacott1** [DataDog/dd-trace-java#421]
at the moment the LoggingWriter outputs vast amounts of log data as INFO.
it would be great if all the INFO logging could be changed to TRACE for the logwriter output so that folk don't have to isolate the LoggingWriter as special (ie set it to > WARN) for normal operation.

**Comment by realark** [comment]
The logging writer is intended to be used with debugging or auditing. Turning it on disables data reporting so it's not a tool that can be used during normal operations.

Silencing the Logging writer can still be accomplished like this `-Ddd.writer.type=LoggingWriter -Ddatadog.slf4j.simpleLogger.defaultLogLevel=off`

Given that other users may rely on the current behavior I don't see much benefit adding this.
