### ISSUE TITLE
GraphQL Instrumentation - operation as resource_name

### ISSUE THREAD

**Issue by glenwinters** [DataDog/dd-trace-java#4210]
I'm interested in graphing trace metrics related to the GraphQL instrumentation by operation name. I can graph latency, hits and errors using `trace.graphql_java`, but there's no tag to view by operation name.

One potential solution is to set `esource_name` (e.g. graphql.request) to the operation name. `resource_name` is already an available tag on trace metrics, so then it could be used to split metrics by operation name.

**Comment by krosen040** [comment]
Making the GraphQL operation name the name of the spans would make the generated trace metrics and the resources on the APM service dashboard a lot more useful. Right now all GraphQL metrics are tagged with `resource_name:graphql.field`, `resource_name:graphql.request`, etc which isn't very helpful.

**Comment by theJC** [comment]
And for anonymous operations, using the sanitized/normalized graphql query text could be an option.
