### ISSUE TITLE
Can we disable  injection of DD tracing headers or set as Null?

### ISSUE THREAD

**Issue by vamsikoneru1** [DataDog/dd-trace-java#4250]
Hi,

We have a application which is consuming from kafka topic and writing it to kafka topic, while writing it to kafka topic , all the records are having the data dog trace headers. I did try adding the dd.logs.injection=false in system properties , but i dont see any difference.

Below is the record header example :

headers=RecordHeaders(headers = [RecordHeader(key = x-datadog-trace-id, value = [51, 50, 55, 48, 52, 52, 48, 57, 53, 53, 56, 55, 54, 54, 56, 55, 57, 53]), RecordHeader(key = x-datadog-parent-id, value = [56, 57, 50, 52, 51, 57, 52, 55, 53, 55, 55, 53, 50, 49, 54, 49, 53, 52]), RecordHeader(key = x-datadog-sampling-priority, value = [49]), RecordHeader(key = ot-baggage-t0, value = [49, 54, 54, 56, 53, 52, 51, 52, 49, 55, 55, 50, 52])], isReadOnly = true),

Is there any way that we can send these headers as null or can we disable this feature?

**Comment by devinsba** [comment]
`dd.logs.injection=false` is for controlling adding trace and span IDs into logging MDC. You can disable propagation using `dd.kafka.client.propagation.enabled=false` or `dd.kafka.client.propagation.disabled.topics=` to disable for a specific topic name.

**Comment by vamsikoneru1** [comment]
Thanks a lot @devinsba , it worked .
