### ISSUE TITLE
Agent doesn't start with read-only filesystem

### ISSUE THREAD

**Issue by nhoughto** [DataDog/dd-trace-java#429]
Trying to use the tracing agent in a Kubernetes deployed application, that has no runtime writable filesystems. As all disk writes are done during Docker Image build time we don't need writable disk.

The datadog agent seems to need a tmp file to extract / bootstrap some internal dependencies?
Seems to be done here:
https://github.com/DataDog/dd-trace-java/blob/master/dd-java-agent/src/main/java/datadog/trace/agent/TracingAgent.java

Failing stacktrace:
```
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:401)
	at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:416)
Caused by: java.io.IOException: Read-only file system
	at java.io.UnixFileSystem.createFileExclusively(Native Method)
	at java.io.File.createTempFile(File.java:2024)
	at java.io.File.createTempFile(File.java:2070)
	at datadog.trace.agent.TracingAgent.extractToTmpFile(TracingAgent.java:143)
	at datadog.trace.agent.TracingAgent.startAgent(TracingAgent.java:49)
	at datadog.trace.agent.TracingAgent.premain(TracingAgent.java:37)
	... 6 more

```

It would be great if this bootstrapping could happen another way or if we could manually bring it forward to image build time and pass in the JARs ourselves, lots of other ways to do it obv.

Compromising our application security to add APM isn't worth it, so this is a showstopper for our use of Datadog APM.

**Comment by nhoughto** [comment]
Raised with support as 160696
https://help.datadoghq.com/hc/requests/160696

**Comment by tylerbenson** [comment]
I will have to discuss this with my team, as I can't think of a clean way of fixing this right now.  Unfortunately the Java API we're using to add classes to the boostrap requires a file on the file system.

**Comment by nhoughto** [comment]
So were ok with a file, but just not a temporary file. So a way to specify an existing already-extracted file would work for us.

**Comment by nhoughto** [comment]
Took a stab at fixing this 🤞

**Comment by nhoughto** [comment]
Any updates on this? We heard from product that this was tentative for first quarter this year? Almost end of first quarter =)

**Comment by devstuff** [comment]
I've also got a K8s app with the same need for a readonly filesystem.

@realark Any updates on a build-time solution as proposed in the linked PR #440 ?

**Comment by andrewsouthard1** [comment]
Hey all, we haven't been able to prioritize this in the short-term. We'll continue to keep this in our backlog and revisit when we can take a look further.

**Comment by andrewsouthard1** [comment]
@nhoughto @devstuff We've made some progress towards this effort here: https://github.com/DataDog/dd-trace-java/pull/934 however there may still be reliance on read-only for certain instrumentation. Would your teams be willing to try out the latest version: https://github.com/DataDog/dd-trace-java/releases/tag/v0.31.1 to confirm whether you are still receiving this exception?

**Comment by randomanderson** [comment]
#2215 is another step towards this

**Comment by nhoughto** [comment]
Way late on the update, sorry about that! but yes version `0.83.2` does start with a read-only container, i'm sure it started working earlier than this, but i just tested the latest one and success!

Are the limitations of read-only agent understood? How do I know what isn't going to work?

**Comment by tylerbenson** [comment]
Thanks for the confirmation.  I think we can close this issue then.  If anything comes up, please open a new issue.
