### ISSUE TITLE
JaxRS Client Leaks PendingTraces on Exception

### ISSUE THREAD

**Issue by tony-schellenberg** [DataDog/dd-trace-java#437]
We have had a problem with a memory leak in one of our applications. After some digging, it appears that it happens with the auto instrumentation of JaxRS clients (Jersey implementation in this case). 

If I've tracked it down properly, the ClientRequestFilter is executed creating the span. Then, the networking tries to actually connect to the server which throws an exception and the ClientResponseFilter is never executed leaving the span dangling.

There also appears to be an error with the cleanup of PendingTraces up to version 0.12.0 but I believe that has been fixed in master. Once that goes through, this won't cause unbounded leaks as it appears to be doing today. However, as these spans are never finished, the traces don't get sent to the agent and we have no record of these failures even if there was no memory leak.

How to reproduce:
The easiest way is to try and connect a client to a server end point that doesn't exist. It generates a javax.ws.rs.ProcessingException from a java.net.ConnectionException: Connection refused. Inspecting DataDog debug logs, it's clear the trace isn't closed or written.

**Comment by tylerbenson** [comment]
> There also appears to be an error with the cleanup of PendingTraces up to version 0.12.0 but I believe that has been fixed in master.

Could you clarify what error you're referring to and what fixes it on master (if you know)?

Thanks for digging into the problem.  Next week I'll see if I can reproduce it and figure out a way to solve it.

Meanwhile, you can disable the client instrumentation:
`-Ddd.integration.jax-rs-client.enabled=false`

**Comment by tylerbenson** [comment]
I see the problem and this is a tricky one to solve.  The jax-rs interfaces make this very difficult.  I might need to add some instrumentation at the implementation level.

**Comment by tony-schellenberg** [comment]
> Could you clarify what error you're referring to and what fixes it on master (if you know)?

This commit is the one that I believe fixes the memory leak: https://github.com/DataDog/dd-trace-java/commit/e51708023437b168b42e8592e4c12680016126b4#diff-28ebab7e0711a0924cd60c0e28ab0f06R253 

If I've read and understood the code correctly, prior to this there were two span cleaners. One that was a static member of the PendingTraces class and another that was instanced in with the start of the scheduled thread. As PendingTraces were created, they were getting pushed into the class static member but, since that wasn't the one running in the thread, the traces were never getting cleaned up.

>Meanwhile, you can disable the client instrumentation:
-Ddd.integration.jax-rs-client.enabled=false

I'm looking at switching to HttpUrlConnection instead of disabling this. There's other advantages for us to make this switch as well.

**Comment by tony-schellenberg** [comment]
Looking quickly again at 0.12.0 and the why it seems to be holding the memory I think maybe the SpanCleaner is holding strong references https://github.com/DataDog/dd-trace-java/blob/v0.12.0/dd-trace-ot/src/main/java/datadog/opentracing/PendingTrace.java#L254

**Comment by tylerbenson** [comment]
@tony-schellenberg the intention is that `PendingTrace` should automatically clean itself up as soon as all pending work is done.  This is tracked via the `AtomicInteger` counter.  The spans are what is referenced weakly.  When they are either finished or GC'd, the counter should be decremented and when it reaches 0, it should be reported.  The notification of a span being GC'd is what is using `WeakReference`s.

The client instrumentation still needs to be fixed. Thanks for the report.

**Comment by tylerbenson** [comment]
@tony-schellenberg please check out #479.  Unfortunately the solution is specific to Jersey and Resteasy, but should at least still help you.
You can get the build from that branch here: https://9190-89221572-gh.circle-artifacts.com/0/home/circleci/dd-trace-java/libs/dd-java-agent-0.15.0-SNAPSHOT.jar

**Comment by tylerbenson** [comment]
Ok, no worries.  Thanks for reporting it though.

**Comment by realark** [comment]
Fix shipped in 0.16.0

**Comment by tony-schellenberg** [comment]
Great! Thanks.
