### ISSUE TITLE
Need support for Spring Boot 2 Reactive Redis Template/Connection

### ISSUE THREAD

**Issue by duke-cliff** [DataDog/dd-trace-java#445]
The previous https://github.com/DataDog/dd-trace-java/issues/313 was solved. We are able to see all API calls with duration. But still I found the Apm service trace does not show the inner redis calls. In Spring Boot 2 we use ReactiveRedisTemplate to make all our redis operations asynchronous as well.

The typical call stack will be something like this:
@GetMapping(...)
Mono<String> restfulApiMethod(@PathVariable String key)
{
   return reactiveRedisTemplate.opsHash().get(key).map(result -> String.valueof(result)).defaultIfEmpty("");
}

We have the snapshot agent from #313 and have  -Ddd.integration.lettuce.enabled=true enabled as well.

Thanks

**Comment by randomanderson** [comment]
This should be fixed with #1308 if it was fixed already.  Please let us know if that is not the case.
