### ISSUE TITLE
Run on virtual threads

### ISSUE THREAD

**Issue by bdeneuter** [DataDog/dd-trace-java#4509]
Hi,

In JDK 19, virtual threads were being introduced as a preview: https://openjdk.org/jeps/425.
We run the Java DataDog agent to collect traces and profile data. We see from the profiles that TraceProcessingWorker and okHttp3 are running on their own thread.
It would be nice to configure the Java agent to be able to let those run on virtual threads if virtual threads are available.

**Comment by bm1549** [comment]
Hi there @bdeneuter 👋  I'm Brian from Datadog

We've released support for Java virtual threads (aka loom) as part of [v1.35.0](https://github.com/datadog/dd-trace-java/releases/tag/v1.35.0) and is available on the latest version - [v1.38.1](https://github.com/DataDog/dd-trace-java/releases/tag/v1.38.1)

As such, I'm going to close out this issue, but please re-open or comment if you run into any issues!
