### ISSUE TITLE
Allow option to disable resource.name 404 rewriting

### ISSUE THREAD

**Issue by rymndhng** [DataDog/dd-trace-java#458]
The datadog documention recommends to reduce the cardinality of the `resource.name`, and most of the instrumentation is cognizant of this. What's the scenario where the Status404Decorator is useful? 

The decorator here rewrites 404 responses with a custom `resource.name`. This was very confusing for me because I was expecting to look at the ratio of 404s to non-404s for my resource.

Can we add an option to turn this decorator off? I would like to have the ability to see my 404 responses with their original `resource.name`.

**Comment by realark** [comment]
@rymndhng Is this instrumentation for a server? If so how would you know which resource to associate the 404 with?

For example, if you had two endpoints `/my/service` and `/other/service`, where would you expect a request `/a/bad/request` to appear?

**Comment by tylerbenson** [comment]
@rymndhng can you explain the circumstance where the 404 being returned by the application is useful to not group together?

**Comment by rymndhng** [comment]
The cirumstance where the 404s are not useful to be grouped together is because applications may implement generic routes with a different permission scheme. i.e. if I am seeing a huge number of 404s on the url pattern `/foo/:id/bar/:id`, I want to see the spans with 404s grouped under the same resource name `/foo/:id/bar/:id` -- not the resource name `404`

**Comment by randomanderson** [comment]
Resolved with #1152
