### ISSUE TITLE
ARM64 async profiler

### ISSUE THREAD

**Issue by houston3** [DataDog/dd-trace-java#4588]
Is there a way to use async profiler on arm64? 
I'm getting `"INFO com.datadog.profiling.async.AsyncProfiler - Unable to instantiate async profiler for the detected environment: arch=aarch64, os=linux, cause=File /native-libs/linux-musl-aarch64/libasyncProfiler.so was not found on classpath."` when using the latest version of agent (https://dtdg.co/latest-java-trace) on AWS arm64 linux instance. 
If I manually add the missing library from https://github.com/jvm-profiling-tools/async-profiler I get:` "INFO com.datadog.profiling.async.AsyncProfiler - Unable to instantiate async profiler for the detected environment: arch=aarch64, os=linux, cause='int one.profiler.AsyncProfiler.getMaxContextPages0()'"`. 

My application:

public class App {
    public static void main(String[] args) {
        System.out.println( "Hello World!");
    }
}

My dockerfile:

FROM gcr.io/distroless/java17-debian11:nonroot-arm64
COPY App.java dd-java-agent.jar /home/nonroot/
USER nonroot
WORKDIR /home/nonroot
EXPOSE 8080 
ENTRYPOINT [ "java", \
             "-javaagent:/home/nonroot/dd-java-agent.jar", \
             "/home/nonroot/App.java"]

**Comment by richardstartin** [comment]
arm64 is now supported, except for JDK8
