### ISSUE TITLE
Missing slash(/) in akka and play request span name

### ISSUE THREAD

**Issue by alok1111** [DataDog/dd-trace-java#4806]
Hi Team,

We use play framework + Java on our backend. For some reason, akka and play spans name doesn't contain slash symbol.
![image](https://user-images.githubusercontent.com/38399528/221794610-0ae78e2b-17e8-4752-b950-db1ff6d61fe9.png)
I believe the issue appeared when we divided `routes` files.
main `routes` file:
```
->          /webhook                                              webhook.Routes
```
webhook sub-project `webhook.routes` file:
```
POST        /repo-push                      controllers.webhook.WebhookController.process(request: Request)
```

**Comment by ygree** [comment]
Thanks for reporting this issue! Can you add Java Tracer, Play Framework versions please?

**Comment by alok1111** [comment]
@ygree 
dd-trace-java - 0.107.1
play framework -  2.8.18

**Comment by ygree** [comment]
Thanks for the info, @alok1111! Datadog Java Tracer takes the route from `HandlerDef.path` which is already missing expected separator. This looks like a bug in PlayFramework's Routes Compiler. `HandlerDef` is generated from the defined routes using this Twirl template: https://github.com/playframework/playframework/blob/main/dev-mode/routes-compiler/src/main/twirl/play/routes/compiler/inject/forwardsRouter.scala.twirl#L70.

I'll see if we can add a workaround by adding a missing slash separator when it's missing.
