### ISSUE TITLE
Memory leak reported against profiler in 1.10.0 

### ISSUE THREAD

**Issue by richardstartin** [DataDog/dd-trace-java#4883]
https://github.com/DataDog/dd-trace-java/issues/3778#issuecomment-1462530694

**Comment by richardstartin** [comment]
This appears to have been caused by unbounded growth of thread metadata, which was not being cleared out because of the change from stopping and starting the profiler to continuous dumping made in #4796. I have a fix for this running under a load test and the issue should hopefully be addressed in 1.11.0.

**Comment by donholly** [comment]
Thank you, @richardstartin! let me know if you need anything else to assist with this investigation.

**Comment by richardstartin** [comment]
Fixed in 1.11.2
