### ISSUE TITLE
Google-PubSub support

### ISSUE THREAD

**Issue by hkoosha** [DataDog/dd-trace-java#4932]
Currently while using the java agent, it's not possible to treat each PubSub message as an individual operation. They are all stacked under one grpc call.

The tracing should preferably be managed at an upper level (PubSub itself) rather than at grpc level.

**Comment by eigengrau** [comment]
We are seeing the same issue and it greatly impacts observability in a stack where Pub/Sub is used.

**Comment by ShaneWhelan** [comment]
Any update on when Pub/Sub tracing support will be added? 

It works perfectly with Kafka but with Pub/Sub Datadog cant trace across systems that integrate via Pub/Sub.

**Comment by hkoosha** [comment]
I no longer have access to DataDog as my company doesn't use it anymore. But if you folks are a DataDog customer, I suggest opening a support ticket AND referencing the PR I made (not this issue, link to the PR) and say you need it merged.

I tried the DataDog's pitiful support once, and after a lot of back and forth the support people still had zero clue what I was talking about... so maybe mentioning the PR in the support ticket give them an idea what's being asked for.

**Comment by hkoosha** [comment]
I no longer have access to DataDog as my company doesn't use it anymore. But if you folks are a DataDog customer, I suggest opening a support ticket AND referencing the PR I made (not this issue, link to the PR) and say you need it merged.

I tried the DataDog's support once, and after a lot of back and forth the support people still had zero clue what I was talking about... so maybe mentioning the PR in the support ticket give them an idea what's being asked for.

**Comment by amarziali** [comment]
The google Pub/Sub support has been merged with #4933. It's currently in beta hence it must be explicitely activated (see #6222 for more info and instructions)
