### ISSUE TITLE
Cannot download agent with specific version more precise than major

### ISSUE THREAD

**Issue by acouvreur** [DataDog/dd-trace-java#5018]
OS: Mac
Architecture: arm64 (M1)
Java version: 
```
openjdk version "18.0.2" 2022-07-19
OpenJDK Runtime Environment Zulu18.32+11-CA (build 18.0.2+9)
OpenJDK 64-Bit Server VM Zulu18.32+11-CA (build 18.0.2+9, mixed mode, sharing)
```

When grabbing the agent 

```
wget https://dtdg.co/java-tracer-v1.9.0
``` 

And loading it as an agent will show:

```
Error opening zip file or JAR manifest missing : /path/to/dd-java-agent.jar
Error occurred during initialization of VM
agent library failed to init: instrument
```

I changed the path for this example, but this is not the issue. The path is correct, the permissions are good.

To test even further I just tried to do the following:

```
java -jar java-tracer-v1.9.0
Error: Invalid or corrupt jarfile java-tracer-v1.9.0
```

---

I switched to version 1.11.2 and the issue is resolved.

**Comment by acouvreur** [comment]
Actually, the reason why it doesn't work is because when I hit the `wget` command on any specific version, the result is an html page...

According to the docs:

> Note: To download a specific major version, use the https://dtdg.co/java-tracer-vX link instead, where vX is the desired version. For example, use https://dtdg.co/java-tracer-v0 for the latest version 0. Alternatively, see Datadog’s [Maven repository](https://repo1.maven.org/maven2/com/datadoghq/dd-java-agent) for any specific version.

So `wget https://dtdg.co/java-tracer-v1.9.0` should be valid right?

**Comment by acouvreur** [comment]
Ok, so with further test, it seems that I cannot download when I specify a version with minor or patch.

`wget https://dtdg.co/java-tracer-v1` works

**Comment by acouvreur** [comment]
Ok, so maybe I got it wrong, and for specific version you have to download them through maven, not just checking versions.

So I did something like that:

```
https://repo1.maven.org/maven2/com/datadoghq/dd-java-agent/${DD_JAVA_TRACER_VERSION}/dd-java-agent-${DD_JAVA_TRACER_VERSION}.jar
```

And it works

**Comment by bantonsson** [comment]
Yes @acouvreur, the short links are only for _latest_ versions which is not easily supported by `maven`. Fixed versions should be downloaded the way you describe.
