### ISSUE TITLE
Tracing broken on Quarkus as of 1.106.0

### ISSUE THREAD

**Issue by pcasaes** [DataDog/dd-trace-java#5042]
In order to get complete traces on Quarkus using Resteasy (with or without reactive) we must add the following configurations per https://github.com/DataDog/dd-trace-java/issues/2258#issuecomment-759189657:

```
ENV DD_INTEGRATION_VERTX_ENABLED="false"
ENV DD_TRACE_EXECUTORS="org.jboss.threads.EnhancedQueueExecutor"
```

As of 1.106.0 the service entry span **netty.request** is no longer parenting the **jax_rs.request** span.

I believe the issue was introduced here
https://github.com/DataDog/dd-trace-java/pull/4578/files#diff-6b77a4212deadb4f788d9f47e6f3c2d17f1390122219d32b1ee106220c0ae2aeR179

If we add
```
ENV DD_LEGACY_INSTALLER_ENABLED="true"
```

It works again.

Summary:
To get tracing working on Quarkus with Resteasy as of 1.106.0 we must add the following flags:

```
ENV DD_INTEGRATION_VERTX_ENABLED="false"
ENV DD_LEGACY_INSTALLER_ENABLED="true"
ENV DD_TRACE_EXECUTORS="org.jboss.threads.EnhancedQueueExecutor"
```

**Comment by mcculls** [comment]
Hi @pcasaes - could you enable tracer [debug logging](https://docs.datadoghq.com/tracing/troubleshooting/tracer_debug_logs/?code-lang=java) and capture logs with
```
ENV DD_LEGACY_INSTALLER_ENABLED="true"
```
and again with
```
ENV DD_LEGACY_INSTALLER_ENABLED="false"
```
and send the zipped logs via support - thanks!

**Comment by mcculls** [comment]
Could you also let us know which version of Quarkus you're using, and other third-party dependency versions

**Comment by pcasaes** [comment]
I can.

Quarkus 2.16.6

**Comment by pcasaes** [comment]
Using 
protobuf 3.21.7
kafka-protobuf-serializer 7.1.1

 The tracing doesn't propagate correctly if we are missing this
 
 ```
 DD_TRACE_EXECUTORS="org.jboss.threads.EnhancedQueueExecutor"
 ```
 
 I imagine that that isn't configured when NOT in legacy mode.

**Comment by pcasaes** [comment]
Logs sent, ticket 1163742

**Comment by mcculls** [comment]
Thanks for the logs - I believe I've recreated the issue and I'm working on a fix

**Comment by pcasaes** [comment]
Fantastic. I'll give it a go once out.

**Comment by pcasaes** [comment]
Tested with 1.12.1

Fixed!
