### ISSUE TITLE
Can we override traceId with custom uniqueId which we currently have?

### ISSUE THREAD

**Issue by akhil-karanth** [DataDog/dd-trace-java#507]
I see the traceId being generated in this [code](https://github.com/DataDog/dd-trace-java/blob/c3f7630387c042e1e36ed428bf17ddab46fd1979/dd-trace-ot/src/main/java/datadog/opentracing/DDTracer.java#L491).

Is there a way to override this trace id with our own unique id (base 64 UUID), which we currently to track a request across our systems to maintain uniformity.
If yes, will the datadog backend be able to handle this?

**Comment by tylerbenson** [comment]
There's not an easy way to do this right now.  Your best bet is to add your own ID as a tag on the root span where you can use Trace Search to query for it.

Does that help?

**Comment by randomanderson** [comment]
Closing as there has been no response in over a year.  Please open a new feature request if adding a tag is insufficient to solve the problem.
