### ISSUE TITLE
Failing build on master

### ISSUE THREAD

**Issue by htmldoug** [DataDog/dd-trace-java#512]
I'm interested in testing the snapshot on master now that #443 is merged, but the build is failing at HEAD: 76876e7d9e00d001e6a56a4637184dd4044a1638. https://circleci.com/gh/DataDog/dd-trace-java/9897?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by realark** [comment]
@htmldoug Thanks for your patience. @mar-kolya has fixed the issue.

https://github.com/DataDog/dd-trace-java/pull/513

https://circleci.com/workflow-run/47f0bf27-b0ac-41ab-a7ba-3c7debcffaa6

2a22ee17bbda151682e340813deae8841b60a614
