### ISSUE TITLE
Add vert.x 4.x to Java compatibility documentation

### ISSUE THREAD

**Issue by akleiman** [DataDog/dd-trace-java#5126]
Hi. Apologies if this isn´t the right place, but at https://docs.datadoghq.com/tracing/trace_collection/compatibility/java/ the version of vert.x supported is shown as 3.5 to 3.9. 

But with https://github.com/DataDog/dd-trace-java/pull/3557 merged shouldn´t the compatibility tables be updated?

**Comment by amarziali** [comment]
the documentation seems to have been updated with the right version range right now (3.4+)
