### ISSUE TITLE
JVM Memory Optimization

### ISSUE THREAD

**Issue by ctoestreich** [DataDog/dd-trace-java#514]
We have run a couple tests on a boot 1.5.X Java 1.8 app that uses tomcat and we have found that when enabling the APM agent we are adding about about 180Mb of ram to the JVM.  There is exactly 2 controllers in addition to the actuator endpoints for a total of ~10 accessible HTTP endpoints, rather small.

A few questions:

- [ ] Is this expected?
- [ ] Have you profiled the APM tool and do you have any results to share?
- [ ] Are you working to optimize the JVM memory usage at all?
- [ ] Does the memory usage scale up or down based on some factor of application scale (ie number of controllers, classes, etc?)

![image](https://user-images.githubusercontent.com/691357/46018606-e2ab2480-c09f-11e8-924b-6bf62fd3d8a6.png)

  | APM Enabled1 | APM Enabled2 | APM Disabled1 | APM Disabled2 |   | Avg APM Enabled | Avg APM Disabled | Avg Difference
-- | -- | -- | -- | -- | -- | -- | -- | --
1 | 107.9 | 159.5 | 30.52 | 85.91 |   | 133.7 | 58.215 | 75.485
2 | 171.9 | 196.2 | 50.76 | 31.02 |   | 184.05 | 40.89 | 143.16
3 | 183.6 | 181 | 50.76 | 160.5 |   | 182.3 | 105.63 | 76.67
4 | 189.6 | 140.4 | 172.7 | 97.76 |   | 165 | 135.23 | 29.77
5 | 139.9 | 133.3 | 58.69 | 107.6 |   | 136.6 | 83.145 | 53.455
6 | 144.8 | 200 | 173.7 | 99.91 |   | 172.4 | 136.805 | 35.595
7 | 240.5 | 261.2 | 104.9 | 56.14 |   | 250.85 | 80.52 | 170.33
8 | 158.9 | 219.1 | 162.2 | 47.98 |   | 189 | 105.09 | 83.91
9 | 153.6 | 282 | 140.2 | 121.4 |   | 217.8 | 130.8 | 87
10 | 174.8 | 314.7 | 85.75 | 59.49 |   | 244.75 | 72.62 | 172.13
11 | 222.8 | 204.2 | 92.83 | 140.4 |   | 213.5 | 116.615 | 96.885
12 | 290.5 | 204 | 187.1 | 174.6 |   | 247.25 | 180.85 | 66.4
13 | 301.7 | 345.1 | 74.09 | 144.8 |   | 323.4 | 109.445 | 213.955
14 | 212.9 | 284.9 | 161.1 | 125.4 |   | 248.9 | 143.25 | 105.65
15 | 304.4 | 217 | 201.2 | 59.11 |   | 260.7 | 130.155 | 130.545
16 | 284.6 | 261.4 | 126.6 | 167.8 |   | 273 | 147.2 | 125.8
17 | 218.5 | 335.3 | 182.4 | 123.4 |   | 276.9 | 152.9 | 124
18 | 239.6 | 264.8 | 81.1 | 199.4 |   | 252.2 | 140.25 | 111.95
19 | 325.4 | 320.3 | 118 | 218.6 |   | 322.85 | 168.3 | 154.55
20 | 304.7 | 378 | 174.3 | 199.5 |   | 341.35 | 186.9 | 154.45
21 | 290.9 | 263.8 | 160.3 | 199.6 |   | 277.35 | 179.95 | 97.4
22 | 310.5 | 241.1 | 212 | 150.2 |   | 275.8 | 181.1 | 94.7
23 | 268.7 | 317.3 | 204.2 | 96.4 |   | 293 | 150.3 | 142.7
24 | 344.5 | 318 | 209.4 | 89.4 |   | 331.25 | 149.4 | 181.85
25 | 380.2 | 318.9 | 203.1 | 149.7 |   | 349.55 | 176.4 | 173.15
26 | 325.1 | 320.7 | 145.6 | 151 |   | 322.9 | 148.3 | 174.6
27 | 326.8 | 321.1 | 146.5 | 151.8 |   | 323.95 | 149.15 | 174.8
28 | 298.5 | 321.9 | 148.3 | 153.3 |   | 310.2 | 150.8 | 159.4
29 | 310.3 | 323.5 | 149.8 | 153.9 |   | 316.9 | 151.85 | 165.05
30 | 310.9 | 323.9 | 150.1 | 154.4 |   | 317.4 | 152.25 | 165.15
31 | 313.1 | 324.3 | 151.3 | 156.7 |   | 318.7 | 154 | 164.7
32 | 313.6 | 325.9 | 151.7 | 157.1 |   | 319.75 | 154.4 | 165.35
33 | 318.3 | 326.4 | 151.7 | 157.7 |   | 322.35 | 154.7 | 167.65
34 | 319.9 | 327.2 | 153.2 | 158.8 |   | 323.55 | 156 | 167.55
35 | 321 | 328.9 | 153.6 | 158.9 |   | 324.95 | 156.25 | 168.7
36 | 321.5 | 329.2 | 153.9 | 159.1 |   | 325.35 | 156.5 | 168.85
37 | 323 | 330.2 | 155.4 | 160.5 |   | 326.6 | 157.95 | 168.65
38 | 323.4 | 331.9 | 155.9 | 160.5 |   | 327.65 | 158.2 | 169.45
39 | 324.2 | 332.1 | 156.1 | 160.7 |   | 328.15 | 158.4 | 169.75
40 | 325.7 | 332.8 | 157.6 | 162.1 |   | 329.25 | 159.85 | 169.4
41 | 326.2 | 334.5 | 158 | 162.1 |   | 330.35 | 160.05 | 170.3
42 | 326.5 | 334.9 | 158.3 | 162.6 |   | 330.7 | 160.45 | 170.25
43 | 328.5 | 335.2 | 159.9 | 164 |   | 331.85 | 161.95 | 169.9
44 | 328.9 | 336.8 | 160.3 | 164.3 |   | 332.85 | 162.3 | 170.55
45 | 329.8 | 337.1 | 160.6 | 165 |   | 333.45 | 162.8 | 170.65
46 | 331.3 | 338 | 161.8 | 166.4 |   | 334.65 | 164.1 | 170.55
47 | 331.8 | 339.5 | 162.4 | 166.4 |   | 335.65 | 164.4 | 171.25
48 | 332.2 | 340 | 162.7 | 166.9 |   | 336.1 | 164.8 | 171.3
49 | 333.8 | 340.2 | 163.9 | 168.6 |   | 337 | 166.25 | 170.75
50 | 334.2 | 342 | 164.4 | 169 |   | 338.1 | 166.7 | 171.4
51 | 335.1 | 342.3 | 164.4 | 169.2 |   | 338.7 | 166.8 | 171.9
52 | 336.6 | 343.6 | 165.6 | 170.3 |   | 340.1 | 167.95 | 172.15
53 | 336.9 | 345 | 166.3 | 170.6 |   | 340.95 | 168.45 | 172.5
54 | 337.3 | 345.5 | 166.5 | 171.1 |   | 341.4 | 168.8 | 172.6
55 | 339.4 | 345.8 | 167.8 | 172.8 |   | 342.6 | 170.3 | 172.3
56 | 339.8 | 347.5 | 168.2 | 172.8 |   | 343.65 | 170.5 | 173.15
57 | 340.7 | 348 | 168.6 | 173.3 |   | 344.35 | 170.95 | 173.4
58 | 342.3 | 349 | 170 | 175 |   | 345.65 | 172.5 | 173.15
59 | 342.7 | 350.6 | 170.9 | 175 |   | 346.65 | 172.95 | 173.7
60 | 343.1 | 351.1 | 170.9 | 175.6 |   | 347.1 | 173.25 | 173.85
61 | 344.6 | 351.4 | 172.3 | 177.2 |   | 348 | 174.75 | 173.25
62 | 345 | 353 | 172.7 | 177.6 |   | 349 | 175.15 | 173.85
63 | 345.8 | 353.4 | 172.7 | 178.1 |   | 349.6 | 175.4 | 174.2
64 | 347.5 | 354.6 | 174.2 | 179.2 |   | 351.05 | 176.7 | 174.35
65 | 347.8 | 356.1 | 175.2 | 179.5 |   | 351.95 | 177.35 | 174.6
66 | 348.2 | 356.5 | 175.2 | 179.7 |   | 352.35 | 177.45 | 174.9
67 | 350.3 | 356.8 | 176.4 | 181.1 |   | 353.55 | 178.75 | 174.8
68 | 350.7 | 358.4 | 176.6 | 181.4 |   | 354.55 | 179 | 175.55
69 | 351.5 | 358.9 | 176.6 | 183.4 |   | 355.2 | 180 | 175.2
70 | 352.9 | 359.6 | 177.7 | 184.8 |   | 356.25 | 181.25 | 175
71 | 353.3 | 361.1 | 178.3 | 185.1 |   | 357.2 | 181.7 | 175.5
72 | 354.7 | 361.8 | 178.4 | 185.6 |   | 358.25 | 182 | 176.25
73 | 356.1 | 362.2 | 179.8 | 187.1 |   | 359.15 | 183.45 | 175.7
74 | 356.5 | 363.9 | 180.2 | 187.4 |   | 360.2 | 183.8 | 176.4
75 | 357.2 | 364.6 | 180.4 | 187.6 |   | 360.9 | 184 | 176.9
76 | 359.2 | 365.3 | 181.8 | 189 |   | 362.25 | 185.4 | 176.85
77 | 359.6 | 366.9 | 183 | 189 |   | 363.25 | 186 | 177.25
78 | 360 | 367.3 | 183.4 | 189.5 |   | 363.65 | 186.45 | 177.2

**Comment by nilsdaniel** [comment]
I might add to this. We have been relying on data-dog (and the Java APM / dd-agent) to monitor large scale Atlassian Jira instances. Running a re-index db-read/io-write heavy processes resulted in unexpected high amounts of memory being allocated (and never freed) in the JVM. An instance that usually re-indexes smoothly with ~ 6gb of Xmx required 48g Xmx all of a sudden. It took a while to figure out the dd-agent is to blame (partially?).

Please see attached screenshot that illustrates the problem.
<img width="1592" alt="screen shot 2018-09-26 at 09 28 48" src="https://user-images.githubusercontent.com/391838/46110445-f19aef80-c1e3-11e8-94d0-c547663db7fb.png">

**Comment by ctoestreich** [comment]
@nilsdaniel When you disable the APM javaagent did the issue resolve?

**Comment by nilsdaniel** [comment]
Yes it does. I’ll attach a screenshot of the same indexing-run without the agent later. Overall memory averaged at ~ 3g.

**Comment by realark** [comment]
@nilsdaniel @ctoestreich 

Have you guys been able to reproduce this on the latest version of the tracer? We've recently made some improvements to our class info cache: https://github.com/DataDog/dd-trace-java/pull/468

If the problem persists can each of you open up a support ticket with a heap dump and debug logs so we can diagnose further?


> Does the memory usage scale up or down based on some factor of application scale (ie number of controllers, classes, etc?)

The number of classes and classloaders is the biggest factor in terms of memory.

> Is this expected?

Not expected with the latest version.

> Have you profiled the APM tool and do you have any results to share?

We do in-house profiling, but mostly as a means of checking for regressions. APM performance measurements are very sensitive to what's being profiled. Our app is different from yours, so the numbers would not reflect your experience. We'd have to do some work to publish those numbers in a meaningful way.

Here's the app we use for profiling: https://github.com/DataDog/dd-trace-java/tree/master/dd-java-agent/benchmark-integration

> Are you working to optimize the JVM memory usage at all?

Not currently, but if we can confirm a performance bug we'd like to fix it.

**Comment by nilsdaniel** [comment]
Hi Andrew,

the issue is not solved in 0.15. Please see Screen Shot attached.

<img width="1592" alt="screenshot 2018-09-27 at 19 56 24" src="https://user-images.githubusercontent.com/391838/46164968-aa6a3880-c28f-11e8-8b5a-30e1506ec91c.png">

**Comment by realark** [comment]
@nilsdaniel That's pretty high! Can you send logs and a heapdump through datadog support?

**Comment by ctoestreich** [comment]
We are also on 0.15.0

**Comment by nilsdaniel** [comment]
We can't share heap-dumps (due to data privacy concerns). What kind of logs would you need?

Btw. here is how it should look like.

<img width="1592" alt="screenshot 2018-09-26 at 21 40 14" src="https://user-images.githubusercontent.com/391838/46210817-1ac99600-c332-11e8-80c5-0d9f9ecd2723.png">

**Comment by tylerbenson** [comment]
For both of these situations (especially if you can't provide heap dumps), I think it would be useful to identify which integrations are running (probably identifiable in your application logs by [enabling debug logging](https://docs.datadoghq.com/tracing/advanced_usage/?tab=java#debugging) for the javaagent).  You can then disable all of the integrations, and enable 1-2 at a time to help narrow down where the problem might be.

To disable all integrations, add the following system property:
```
-Ddd.integrations.enabled=false
```

Then for each integration that you want to enable, manually renable with the following property:
```
-Ddd.integration.{INTEGRATION_NAME}.enabled=true
```

The best place to find the name of the integration is in [the code](https://github.com/DataDog/dd-trace-java/blob/master/dd-java-agent/instrumentation/servlet-3/src/main/java/datadog/trace/instrumentation/servlet3/AbstractServlet3Instrumentation.java#L11).  You may use any of those strings that are passed into the super constructor for implementations of `Instrumenter.Default`.

**Comment by nilsdaniel** [comment]
Hi Tyler,

even with all integrations disabled there is some added load, although it looks way better. What integrations are enabled by default?

Cheers,

Daniel

<img width="1548" alt="screenshot 2018-09-28 at 17 50 15" src="https://user-images.githubusercontent.com/391838/46281022-ca3e7c80-c56d-11e8-9a0a-156dd7984a4c.png">

**Comment by tylerbenson** [comment]
@nilsdaniel almost all of them are enabled by default.  I'd suggest start with the ones that look interesting to you and likely to apply to your application and go from there.

**Comment by realark** [comment]
@nilsdaniel To clarify, most integrations are enabled by default, but the only ones that apply are specific to your stack.

You can find the integrations that applied by looking for this debug log message:

```
Applying instrumentation: <integration-name>
```

**Comment by nilsdaniel** [comment]
@realark @tylerbenson is there a list of the default integrations documented somewhere? Or do we have to dig through this repo?

**Comment by realark** [comment]
@nilsdaniel All integrations are documented here: https://docs.datadoghq.com/tracing/setup/java/#integrations

You'll still need to check your logs to see what applies because that is determined by your runtime.

**Comment by ctoestreich** [comment]
We have noticed in our spring 4 java 8 application that the memory footprint is also pretty terrible with APM on.  

Heap usage of app - approx. memory usage after a GC 
•	With APM ~1380MB
•	Without APM ~830MB 

![core_memory](https://user-images.githubusercontent.com/691357/47031239-145e5b00-d135-11e8-822e-af94eaa5ba83.png)

I am still not clear if this is "expected behavior" from your agent.  I get the sense that there hasn't been a real deep dive on jvm profiling.  I think we are a bit leery to add 25-50% overhead for using the APM tool. 

@tylerbenson Also on the integrations page the flags are merely present to ENABLE features. The flags to DISABLE are not present.

**Comment by tylerbenson** [comment]
@ctoestreich I realize it's not ideal and we need to improve the public docs for this, but the best place to find the name of the integration is in [the code](https://github.com/DataDog/dd-trace-java/blob/v0.16.0/dd-java-agent/instrumentation/servlet-3/src/main/java/datadog/trace/instrumentation/servlet3/AbstractServlet3Instrumentation.java#L11). You may use any of those strings that are passed into the super constructor for implementations of `Instrumenter.Default`.

The expected behavior is that we don't add a significant burden on your application. I would consider 20+% excessive and something we should look at.  The best way forward to troubleshoot excessive heap usage is to open a ticket and provide a heap dump and your application logs with [dd trace debug enabled](https://docs.datadoghq.com/tracing/advanced_usage/?tab=java#debugging).

Could you please clarify which version of the tracer you're using?

**Comment by ctoestreich** [comment]
@tylerbenson currently we are on 0.14.0~8e218ce3

I will see if we can come up with more verbose logging that we can share

**Comment by ctoestreich** [comment]
Our perf engineer did grab this out of dynatrace.

![image](https://user-images.githubusercontent.com/691357/47728092-ada86980-dc2b-11e8-9d44-d37c9616fded.png)

His notes:
"I did notice that the old gen for [application] consistently sit at around 1365MB, and after a full GC it will drop down to 460MB. In a 6 min period or so, it will go back to 1200MB. I am still doing further analysis in this and potentially explore other GC as old gen parallel (what we have setup currently by default) doesn’t do frequent GC and objects have higher chances of not getting garbage collected in the eden space making its way to old gen."

**Comment by ctoestreich** [comment]
@tylerbenson Some people on my team smarter than I have pointed to https://github.com/DataDog/dd-trace-java/blob/master/dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/DDCachingPoolStrategy.java#L31 as a possible culprit for high memory usage.  

Some flavor from my engineers "If they’re using weak references in their cache implementation,that might explain why it would eat up most available memory but get cleared on a full GC. If that’s the case, dedicating less overall memory should be ok since weak reference should release if new objects need heap space."

This weak map may explain @nilsdaniel's issue depending on how many objects are in that map.

**Comment by tylerbenson** [comment]
@ctoestreich I appreciate the extra details and suggestions.  The reason I was asking which version you were using is because in `0.15.0` we submitted a fix for this with #468.  Could you try upgrading and see if that solves the issue?  The latest is `0.17.0` if you want to jump all the way to that.

You can see the [cache eviction settings](https://github.com/DataDog/dd-trace-java/blob/master/dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/DDCachingPoolStrategy.java#L60-L63).  We are happy to tune those if you feel it should be adjusted.

**Comment by ctoestreich** [comment]
Yes I have a pretty for our docker image with 0.17 that our perf team can retest.

**Comment by tylerbenson** [comment]
@ctoestreich awesome.  I look forward to the results.

**Comment by redijedi** [comment]
Just to add to this, we're seeing significantly increased memory usage with DD Java Agent. We're on 0.17.0. Anecdotally, but consistently, we see almost a full doubling of memory usage. One service that used to run just shy of 300M at rest jumped up to 621M at rest after enabling the dd-java-agent. This is a dealbreaker as we don't want to increase our cluster sizes (and cost) just to use DD.

**Comment by ctoestreich** [comment]
I have it on my docket this week to produce some results and analysis with yourkit or dynatrace.

**Comment by redijedi** [comment]
For policy reasons I can't produce much that would leak IP, but here's a graph of another heavier service that typically use about half a gig now uses over a gig after enabling the agent.

<img width="194" alt="screen shot 2018-11-14 at 8 15 33 pm" src="https://user-images.githubusercontent.com/83999/48523447-7a302680-e84a-11e8-955c-78aec26180ea.png">

Seems to be a fairly consistent doubling of memory usage across all the services I've tested so far.

**Comment by ctoestreich** [comment]
My ability to put arbitrary items into the env that has dynatrace is limited so all testing is local and down running java -jar on a boot application both with and without the agent.  I didn't see anything that "jumped out".  This was done on the latest 0.17 release.  Things are higher, but not like when deployed out into real container platform.  Also I ran a huge load that only hit a few URLs on the application as this service doesn't have a lot of routes.

# With Agent Enabled

<img width="1696" alt="screen shot 2018-11-15 at 3 38 48 pm" src="https://user-images.githubusercontent.com/691357/48583687-612c8180-e8ed-11e8-8bc4-5c3071cbb6c6.png">
<img width="841" alt="screen shot 2018-11-15 at 3 37 35 pm" src="https://user-images.githubusercontent.com/691357/48583691-612c8180-e8ed-11e8-830a-c84bedcbcdc1.png">

<img width="1700" alt="screen shot 2018-11-15 at 3 37 13 pm" src="https://user-images.githubusercontent.com/691357/48583692-612c8180-e8ed-11e8-8252-014a6b134706.png">
<img width="1663" alt="screen shot 2018-11-15 at 3 12 09 pm" src="https://user-images.githubusercontent.com/691357/48583694-61c51800-e8ed-11e8-8e67-34ae257d6ff0.png">

# With Agent Disabled
<img width="1696" alt="screen shot 2018-11-15 at 3 38 33 pm" src="https://user-images.githubusercontent.com/691357/48583688-612c8180-e8ed-11e8-8df5-ab41e41dc9cc.png">

<img width="854" alt="screen shot 2018-11-15 at 3 37 44 pm" src="https://user-images.githubusercontent.com/691357/48583689-612c8180-e8ed-11e8-92d0-1ed041a09110.png">

<img width="1689" alt="screen shot 2018-11-15 at 3 36 58 pm" src="https://user-images.githubusercontent.com/691357/48583693-612c8180-e8ed-11e8-8eb4-beab83d66026.png">

**Comment by tylerbenson** [comment]
@ctoestreich Thanks for the follow up report.  The updated results seem reasonable to me.  Are you comfortable saying that the issue is resolved then?

@nilsdaniel I am pretty sure your issue is different from what @ctoestreich submitted.  However I just submitted a PR that I think has a good chance of resolving your problem: #582.  Go ahead and follow up on that PR.

@redijedi perhaps it would be better if you contact support directly?  It would really help if we could get a heap dump to better identify the problem.

**Comment by ctoestreich** [comment]
After we do a round of validation in our container platform next week I will update.

**Comment by realark** [comment]
@nilsdaniel Wanted to make you aware we just shipped a fix for async servlets using dispatch we believe will solve your issue.

**Comment by tylerbenson** [comment]
@ctoestreich any update?

**Comment by ctoestreich** [comment]
Close
