### ISSUE TITLE
Trace and Span IDs with logback-access in Spring Boot with Tomcat 9

### ISSUE THREAD

**Issue by internetstaff** [DataDog/dd-trace-java#5191]
We're using Spring Boot 2.7.11 and Tomcat 9.0.74. We recently added `logback-access` for improved access logging and realized we're not getting trace or span IDs.

The root cause appears to be:

* Datadog agent injects into `org.apache.coyote.Request` using `setAttribute()`
* `org.apache.coyote.Request` is encapsulated by `org.apache.catalina.connector.Request`
* `logback-access` sees a `org.apache.catalina.connector.Request`
* Logback `AccessEvent` copies all the attributes to avoid mutation.
* Logback calls `getAttributeNames()` on `org.apache.catalina.connector.Request`, which does not return names from the encapsulated `org.apache.coyote.Request` despite those attributes being accessible via `getAttribute()`.
* Logback then does not have the trace_id and span_id available because they are not in the `AccessEvent`.

If Datadog agent could call `setAttribute()` on the `org.apache.catalina.connector.Request` this should be fixed, but I'm not clear on the downsides of this.

In the mean time, I simply worked around this with a custom Valve that effectively copies the two attributes out of the encapsulated coyote Request into the connector Request:

```java
      request.setAttribute("dd.trace_id", request.getAttribute("dd.trace_id"));
      request.setAttribute("dd.span_id", request.getAttribute("dd.span_id"));
```

Notes:
https://github.com/qos-ch/logback/blob/master/logback-access/src/main/java/ch/qos/logback/access/spi/AccessEvent.java#L407
https://github.com/apache/tomcat/blob/main/java/org/apache/catalina/connector/Request.java#L902

**Comment by amarziali** [comment]
👋 The issue should be fixed by the PR just merged. It should be included in the next release
