### ISSUE TITLE
Amazon Opensearch instrumentation support

### ISSUE THREAD

**Issue by AhmadMasry** [DataDog/dd-trace-java#5232]
Hi Datadog team;
The java agent does not support Amazon Opensearch yet, so I created a PR implementing a new instrumentation module for Opensearch.
As I believe Elasticsearch and Opensearch are now totally diffrent products, we have it in a separated module, not like what is done in python ddtrace which detects it as Elasticsearch.

The PR for reference:
https://github.com/DataDog/dd-trace-java/pull/5233

**Comment by AhmadMasry** [comment]
I noticed that muzzle tests are failing;
and after reviewing why, it is because I need to include all Opensearch versions in the tests.
The tests are running in Java 8, and Opensearch 2 is Java 11+ compatible.
Should I exclude version 2 from muzzle? or there is a way to tell which java version should be used in muzzle?
Thanks

**Comment by mcculls** [comment]
Muzzle will use the same java-version as the other tests, but if you need to force it to use a different version you can use:
```
    javaVersion = '11'
```
ie:
```
muzzle {
  pass {
    group = "org.opensearch.client"
    module = "opensearch-rest-client"
    versions = "[1,)"
    javaVersion = '11'
    assertInverse = true
  }
}
```

**Comment by AhmadMasry** [comment]
Modified.
Thanks a lot.

**Comment by mcculls** [comment]
BTW, expect the system-tests part of the CI build to fail because those require the author to be in a particular group

**Comment by AhmadMasry** [comment]
So muzzle is now fixed, is there anything required for the remaining failed tests in the below list?
- system-tests-ratpack
- system-tests-jersey-grizzly2
- system-tests-spring-boot-openliberty
- system-tests-spring-boot
- system-tests-vertx3
- system-tests-spring-boot-jetty
- system-tests-spring-boot-3-native
- system-tests-resteasy-netty3
Thanks again

**Comment by mcculls** [comment]
Those are expected to fail for external contributions - they require the author to be in a particular group

**Comment by mcculls** [comment]
Hi @AhmadMasry - I did an initial review and left some comments.

Once you've merged instrumentation classes and tests from `dd-java-agent/instrumentation/elasticsearch/transport-7.3` into your new `dd-java-agent/instrumentation/opensearch/transport` module then we should be good to merge this and get it into the next tracer release.

**Comment by AhmadMasry** [comment]
@mcculls , I do not know if my changes has anything with this test:
`z_test_ibm8_smo - Failed.`
And copying my comment from the PR:

> Moving transport-7.3 was a bit tricky, where it is not supported at all in OpenSearch 2 and many needed functionalities are removed and deprecated in OpenSearch 1.
> I removed the incompatible code, modified muzzle and refactored tests so they can pass.
> One strange thing is the need to add multiple Thread.sleep(10000) before any trace evaluation as all of them where timing out in any assertTraces or TEST_WRITER.waitForTraces.
> I will be great if someone can check why they are timing out to help me remove these sleeps.
> 

Thanks

**Comment by mcculls** [comment]
Closing as this formed part of the [1.16.0](https://github.com/DataDog/dd-trace-java/releases/tag/v1.16.0) release
