### ISSUE TITLE
ability to toggle java tracing

### ISSUE THREAD

**Issue by drobert** [DataDog/dd-trace-java#528]
I realize that typically the agent is toggled on or off by virtue of adding/removing the requisite `-javaagent` argument. In some environments, like heroku, it's fairly tricky to to enable the agent in one place and disable it in another.

This is feature request to support something like `trace.enabled` flag (`DD_TRACE_ENABLED` environment variable, etc.) that would completely disable tracing.

Alternatively (or in addition), it would be nice to supply a `NoOpWriter`. Similar situation/cause: if the datadog agent itself itself is disabled, the java tracer will still collect traces and consistently fail to write to a non-running agent; which is basically just a waste of logging, memory, and cpu.

**Comment by tylerbenson** [comment]
I think this is handled in #824 which will be included in our next release.

**Comment by tylerbenson** [comment]
0.28.0 is now available.
