### ISSUE TITLE
Distributed tracing manual propagation using W3C style

### ISSUE THREAD

**Issue by davidtam** [DataDog/dd-trace-java#5311]
Hello previously I was using these library https://github.com/DataDog/dd-trace-java/tree/master/dd-trace-ot/src/main/java/datadog/opentracing to do manual context propagation.  Now datadog support W3C trace context https://docs.datadoghq.com/tracing/trace_collection/trace_context_propagation/java, is there plan to move over supporting https://github.com/open-telemetry/opentelemetry-java/blob/main/api/all/src/main/java/io/opentelemetry/api/trace/Tracer.java (or pls forgive my ignorant, if this is already supported?)

Thank you

**Comment by bantonsson** [comment]
Hi @davidtam, experimental support for the OTel tracer API was merged here #4669, and has been available since version `1.10.0`. It is not enabled by default, so you have to add `-Ddd.integration.opentelemetry.experimental.enabled=true` to your Java command line.

**Comment by davidtam** [comment]
@bantonsson ah ok thank you I will take a look and see how I could use that

**Comment by davidtam** [comment]
Hello - while the otel format context could be propagated, I have having problem asking datadog using the context propagated in downstream service.

I am following the example here:
https://opentelemetry.io/docs/instrumentation/java/manual/#context-propagation

```java
TextMapGetter<Map<String, String>> getter =
  new TextMapGetter<>() {
    @Override
    public String get(Map<String, String> carrier, String key) {
      if (carrier.containsKey(key)) {
        return carrier.get(key);
      }
      return null;
    }

   @Override
   public Iterable<String> keys(Map<String, String>  carrier) {
     return carrier.keySet();
   }
};
...
public void handle(HttpExchange httpExchange) {
  // Extract the SpanContext and other elements from the request.
  Context extractedContext = openTelemetry.getPropagators().getTextMapPropagator()
        .extract(Context.current(), myMap, getter);
  try (Scope scope = extractedContext.makeCurrent()) {
    // Automatically use the extracted SpanContext as parent.
    Span serverSpan = tracer.spanBuilder("GET /resource")
        .setSpanKind(SpanKind.SERVER)
        .startSpan();
    try {
      // Add the attributes defined in the Semantic Conventions
.
.
.
      // Serve the request
      ...
    } finally {
      serverSpan.end();
    }
  }
}

```


Is there something I am missing here?

**Comment by davidtam** [comment]
ok it turns out it isnt an issue and things do work across distributed components.
