### ISSUE TITLE
New versions (1.15.0+) of dd-java-agent no longer showing up on maven repo

### ISSUE THREAD

**Issue by Hexcles** [DataDog/dd-trace-java#5312]
https://repo1.maven.org/maven2/com/datadoghq/dd-java-agent/ only has 1.14.0 as the latest version.

**Comment by smola** [comment]
@Hexcles Somehow the HTML directory listings seem to be cached for very long. The artifacts are present in the repository ([see Maven Search](https://central.sonatype.com/artifact/com.datadoghq/dd-java-agent/1.15.1), and can be fetched with Maven.

**Comment by kayman-mk** [comment]
Yeah, definitely present. We updated to 1.15.1 via Maven central.

**Comment by bantonsson** [comment]
As @smola said, the HTML listings are cached, and the most reliable way is to look at the xml data file https://repo1.maven.org/maven2/com/datadoghq/dd-java-agent/maven-metadata.xml which has `1.15.1` as the latest.

**Comment by Hexcles** [comment]
Ahh you're right. `https://repo1.maven.org/maven2/com/datadoghq/dd-java-agent/1.15.1/dd-java-agent-1.15.1.jar.sha256` works. Thanks!
