### ISSUE TITLE
Setting the `error` tag to true on a span no longer has effect since 1.13.0

### ISSUE THREAD

**Issue by Hexcles** [DataDog/dd-trace-java#5316]
See this for more context: https://github.com/cashapp/misk/pull/2585

It's been working great until recently we upgraded the agent (and libraries) from 1.13 to 1.14. The spans no longer show up as errors.

I can't seem to find anything suspicious after a quick glance of https://github.com/DataDog/dd-trace-java/compare/v1.13.0...v1.14.0 but I'm not really familiar with your code base.

**Comment by smola** [comment]
This might be a duplicate of https://github.com/DataDog/dd-trace-java/issues/5307

**Comment by Hexcles** [comment]
Weird, reverting the agent and libraries back to 1.13.0 didn't fix the issue.

We now suspect maybe it's because of cluster agent upgrade: we went from 3.10.9 to 3.28.1 for https://github.com/DataDog/helm-charts/releases around the same time

**Comment by Hexcles** [comment]
Hmm or we might need to go back to 1.12.1 (we upgraded to 1.13 and then to 1.14 relatively quickly)

**Comment by Hexcles** [comment]
We can confirm 1.12.1 works, so this is indeed a duplicate of #5307 .

**Comment by amarziali** [comment]
Should be fixed by #5359 scheduled for next release

**Comment by Hexcles** [comment]
We can confirm this is now fixed.
