### ISSUE TITLE
Trace id can't be decoded by agent due to being transmitted as float

### ISSUE THREAD

**Issue by aesy** [DataDog/dd-trace-java#532]
My team is currently experimenting with tracing a system that in part consists of Python and Java applications. On the Python side of things we use [dd-trace-py](https://github.com/DataDog/dd-trace-py/). All outgoing requests include the following headers for distributed tracing: 
`{
        'x-datadog-trace-id': str(tracer.current_span().trace_id),
        'x-datadog-parent-id': str(tracer.current_span().span_id)
}`
These ids are as far as I understand 64-bit unsigned integers. 

When a Java application receive a request with such headers and try to submit them to the trace agent, the id will be incorrectly (imo) encoded by msgpack as `float64` rather than `uint64`. The trace agent expect the trace id to be an int so it throws the following error and drops the traces: 
`ERROR (receiver.go:386) - cannot decode v0.4 traces payload: msgp: attempted to decode type "float64" with method for "int"`

I have created a ticket in the [msgpack-java](https://github.com/msgpack/msgpack-java/) repository which can be found [here](https://github.com/msgpack/msgpack-java/issues/487). I'm posting this here because there may be others that have this problem, and I thought I'd let you know.

Currently we've worked around this by swapping out the `objectMapper` in `DDApi`, with the unfortunate use of reflection, to a subclass that use a `MessagePackGenerator` that contains the fix suggested in the pull request related to the issue ticket linked above.

**Comment by tylerbenson** [comment]
@aesy Thanks for the report. From your investigation, do you see something that can be changed inside the java tracer to improve the situation besides waiting for better handling in `msgpack-java`?

**Comment by aesy** [comment]
The issue is only present when serializing string numbers, like such:

https://github.com/DataDog/dd-trace-java/blob/6b0e43b32dc01fcc66dce8944f783dfcb3f658dc/dd-trace-ot/src/main/java/datadog/opentracing/DDSpan.java#L330-L346

https://github.com/DataDog/dd-trace-java/blob/6b0e43b32dc01fcc66dce8944f783dfcb3f658dc/dd-trace-ot/src/main/java/datadog/opentracing/DDSpan.java#L408-L424

I think this could be circumvented by storing the id's as `BigInteger` rather than `String`. Maybe this would result in worse performance, as discussed [here](https://github.com/DataDog/dd-trace-java/pull/392#discussion_r205458166), I don't know.

I can make a pull request if you think think this would be a good solution.

**Comment by realark** [comment]
@aesy trace/span identifiers are sometimes logged in performance sensitive areas. We wanted to avoid paying the penalty of conversion for such cases.

Serialization to the agent is less of a concern (only happens once). Do you think we could accomplish the same thing with changes to `UInt64IDStringSerializer`?

**Comment by aesy** [comment]
Ah I see. 

Yeah, that would work. And there wouldn't need to be any validation since that's already been done at an earlier stage.

**Comment by realark** [comment]
@aesy Thank you so much for the fix! This will ship in our 0.17.0 release (estimated to go out next week).

Will close this issue once the release ships.

**Comment by tylerbenson** [comment]
Fix is included in [0.17.0](https://github.com/DataDog/dd-trace-java/releases/tag/v0.17.0).
