### ISSUE TITLE
Authentication failure while downloading dd-java-agent file from sonatype repository

### ISSUE THREAD

**Issue by Nitstabs** [DataDog/dd-trace-java#5330]
wget -O dd-java-agent.jar 'https://repository.sonatype.org/service/local/artifact/maven/redirect?r=central-proxy&g=com.datadoghq&a=dd-java-agent&v=LATEST'

Result:
https://repository.sonatype.org/service/local/artifact/maven/redirect?r=central-proxy&g=com.datadoghq&a=dd-java-agent&v=LATEST
Resolving repository.sonatype.org (repository.sonatype.org)... 52.207.204.11, 50.19.137.226
Connecting to repository.sonatype.org (repository.sonatype.org)|52.207.204.11|:443... connected.
HTTP request sent, awaiting response... 401 Unauthorized

Username/Password Authentication Failed.

**Comment by mcculls** [comment]
Hi @Nitstabs - repository.sonatype.org is not a canonical repository for the Datadog Java tracer, it is a repository manager managed by Sonatype primarily for their employees that mirrors various other repositories. It may be unavailable at certain times depending on their maintenance schedule.

If you need a link that will download the latest Java tracer then we recommend using https://dtdg.co/latest-java-tracer which will download the latest tracer from GitHub.

Alternatively (assuming you know the version you want to download) you can download tracer releases from Maven Central, for example: https://repo1.maven.org/maven2/com/datadoghq/dd-java-agent/1.15.3/dd-java-agent-1.15.3.jar

**Comment by Nitstabs** [comment]
Thanks @mcculls. 
I tried as you suggested but there's error wrt certificate. Is it something that you can help with??

wget -O dd-java-agent.jar https://dtdg.co/latest-java-tracer

Result:
https://dtdg.co/latest-java-tracer
#0 0.288 Resolving dtdg.co (dtdg.co)... 67.199.248.12, 67.199.248.13
#0 0.325 Connecting to dtdg.co (dtdg.co)|67.199.248.12|:443... connected.
#0 0.794 ERROR: The certificate of ‘dtdg.co’ is not trusted.
#0 0.794 ERROR: The certificate of ‘dtdg.co’ has expired.

**Comment by mcculls** [comment]
Hi @Nitstabs - for some reason your wget is using an old certificate for dtdg.co instead of the latest published certificate

That link is just a shortened URL for https://github.com/DataDog/dd-trace-java/releases/download/download-latest/dd-java-agent.jar so you could just use the longer form instead which would avoid this issue (since the certificate mentioned above just relates to the shortened URL)

**Comment by Nitstabs** [comment]
@mcculls 
wget --version
GNU Wget 1.21.1 built on linux-gnu

Operating System:
cat /etc/os-release
NAME="CentOS Stream"
VERSION="9"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="9"
PLATFORM_ID="platform:el9"
PRETTY_NAME="CentOS Stream 9"
ANSI_COLOR="0;31"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:centos:centos:9"
HOME_URL="https://centos.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux 9"
REDHAT_SUPPORT_PRODUCT_VERSION="CentOS Stream"

**Comment by Nitstabs** [comment]
Can you please suggest how can I get the ca-certificates for 'dtdg.co' & update the ca-bundle.crt/ca-bundle.trust.crt files??

**Comment by mcculls** [comment]
If your system has an older version of openssl installed then you might be encountering https://www.openssl.org/blog/blog/2021/09/13/LetsEncryptRootCertExpire/ - If so then upgrading the version of openssl may help.

Another possible reason is that your `ca-certificates` are out-of-date - assuming you  have this package installed then it should just involve running `sudo update-ca-certificates`

You might also want to try using curl instead as that may have been compiled against a different SSL library that doesn't suffer from the same issue as wget.

Finally the simplest option is to just use the longer link: https://github.com/DataDog/dd-trace-java/releases/download/download-latest/dd-java-agent.jar to fetch the tracer directly from GitHub

**Comment by Nitstabs** [comment]
Information shared by you are really helpful. I will try them out. We are good to close this ticket. Thanks for the help.

**Comment by mcculls** [comment]
Closing as discussed, feel free to re-open if you have further questions
