### ISSUE TITLE
Question/Possible bug interceptor bypassed?

### ISSUE THREAD

**Issue by basimons** [DataDog/dd-trace-java#5402]
Hello all,

I hope this is the right place for my answer, if not please let me know where I can post this instead.

We have recently implemented the datadog trace agent. However, we want to specifically trace somethings, and trace other things not so much. I wrote an interceptor, the code can be found below. In short, I want to see 1 in 100 requests, all delete requests and 1 in 10000 authorization requests.

```
import datadog.trace.api.GlobalTracer;
import datadog.trace.api.interceptor.MutableSpan;
import datadog.trace.api.interceptor.TraceInterceptor;
import java.util.Collection;
import java.util.Collections;
import java.util.Random;
import java.util.Set;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpMethod;
import org.springframework.stereotype.Component;

@Configuration
@Slf4j
public class TraceConfiguration {

    private static final Random RANDOM = new Random();
    private static final float RATIO_TO_LET_THROUGH_NORMAL_REQUEST = 0.01f;
    private static final float RATIO_TO_LET_THROUGH_AUTH_REQUEST = 0.0001f;

    // These are uninteresting and/or clutter the overview
    private static final Set<String> BLACKLISTED_ROOT_RESOURCES = Set.of(
        "DatadogService.pollDatadog",
        "GET /serviceMessages",
        "GET /actuator/health/**",
        "postgresql.query",
        "404");

    @Autowired
    public TraceConfiguration() {
        GlobalTracer.get().addTraceInterceptor(new FilteringInterceptor());
    }

    private static class FilteringInterceptor implements TraceInterceptor {

        @Override
        public Collection<? extends MutableSpan> onTraceComplete(Collection<? extends MutableSpan> trace) {
            boolean validResource = trace.stream()
                .filter(t -> t.getLocalRootSpan() != null)
                .findAny()
                .filter(this::isValidTrace)
                .isPresent();

            return validResource ? trace : Collections.emptyList();
        }

        private boolean isValidTrace(MutableSpan rootSpan) {
            // Typically is something like this: PUT /auth/rest/{apiVersion}/projects/{projectId}/**
            String resourceName = rootSpan.getResourceName().toString();
            if (BLACKLISTED_ROOT_RESOURCES.contains(resourceName)) {
                return false;
            }

            String[] split = resourceName.split(" ", 3);
            if (split.length < 2) {
                return maybeLetThrough(RATIO_TO_LET_THROUGH_NORMAL_REQUEST);
            }

            HttpMethod method = HttpMethod.valueOf(split[0]);
            if (HttpMethod.DELETE.equals(method)) {
                return true;
            }

            String route = split[1];
            if (route.startsWith("/auth/rest/")) {
                boolean authRequestLetThrough = maybeLetThrough(RATIO_TO_LET_THROUGH_AUTH_REQUEST);
                // TODO: remove this later
                if (authRequestLetThrough) {
                    log.info("Letting through auth request with resource name: {}", resourceName);
                }
                return authRequestLetThrough;
            }

            return maybeLetThrough(RATIO_TO_LET_THROUGH_NORMAL_REQUEST);
        }

        private boolean maybeLetThrough(float changeToLetThrough) {
            return RANDOM.nextFloat() <= changeToLetThrough;
        }

        @Override
        public int priority() {
            // So that it is done last (must be unique)
            return Integer.MAX_VALUE - 546;
        }
    }
}
```

When first looking at it, this worked as expected. None of the items in the `BLACKLISTED_ROOT_RESOURCES` show up anymore. However, I noticed that a lot more auth request show up (I expect 1 in 10.000) than I first expected (that's why I added the info log). When I look in my logs I see this (roughly 5 in an hour):
![image](https://github.com/DataDog/dd-trace-java/assets/49156770/f0570e85-1e0b-4cb6-8b11-fd464771ab62)

However, when I then look at the APM traces I see in just a minute or so (all from the service I was looking at before):
![image](https://github.com/DataDog/dd-trace-java/assets/49156770/a9105b28-9731-4672-b709-6ffc900863aa)
Already way more than that. 

Before I had some logging statements which showed me that the splitting on a space that I do is correct.

How is it that I still see these other auth traces still showing up, is there another way in which they can maybe surpass this filter?

**Comment by PerfectSlayer** [comment]
Hello,

This question is being handled by the support team.
Closing it to prevent duplicate support.

**Comment by jsaxon-cars** [comment]
Hi.  Where and when is this being handled?  Is there a link?  Does this mean all TraceInterceptors can't do filtering at all?  I seem to have the same problem.

**Comment by basimons** [comment]
I had some contact with the datadog support team and they gave me some tips (one of them being that the .getName method could be  null), I tried them all but I can't seem to get it to work as I'd expect yet. 

I let it go for now, as priorities on the team changed, but I'm planning to pick it up again later.

If you find anything on how to fix it please let me know. If you are going to contact datadog support yourself, you can tell them that it is comparable to my issue (request 1240033). Maybe that'll speedup some things.
