### ISSUE TITLE
"Wrong" class names are shown in Actuator overview of scheduled tasks in Spring Boot application

### ISSUE THREAD

**Issue by maksymgendin** [DataDog/dd-trace-java#5651]
Instead of real class and method names the class `datadog.trace.instrumentation.springscheduling.SpringSchedulingRunnableWrapper` is shown when you open the scheduled tasks overview from Actuator (`/actuator/scheduledtasks`):

![image](https://github.com/DataDog/dd-trace-java/assets/3966758/b44635d1-0cd7-43ef-af10-1ba25a6d4adc)

There was a [similar issue in `opentelemetry-java-instrumentation`](https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/6103), I would suggest to peek in their fix implementation.

**Comment by amarziali** [comment]
Merged in master with #6249 . Will be GA with next release
