### ISSUE TITLE
How to configure grpc.server.error.statuses

### ISSUE THREAD

**Issue by aiguofer** [DataDog/dd-trace-java#5679]
We currently have very noisy traces due to most grpc codes being included as errors by default. After digging into the codebase I found `grpc.server.error.statuses` to configure this. Based on the docs for the HTTP statuses, I came up with `2,10,13-15`. When I start up, I see this in the logs:

```Invalid config for grpc.server.error.statuses: '2,10,13-15'. Must be formatted like '400-403,405,410-499'.```

I don't really understand what the difference is.. what's the right format I should use here?

**Comment by nayeem-kamal** [comment]
Thanks for inquiring @aiguofer ! Currently, the logic for parsing the integer ranges for status codes only parses 3 digit status codes ( ex)200,200-300,415, etc). Supporting the single and double digit status codes will require us to implement additional parsing logic for the`grpc.server.error.statuses` and `grpc.client.error.statuses` to handle the single and double digit status codes.

**Comment by aiguofer** [comment]
Ahh that makes sense! that would be extremely helpful, we'd love to lower the noise from error traces that are due to user input or configuration issues.

**Comment by nayeem-kamal** [comment]
@aiguofer The fix for this issue has been merged and should be available with the next release of the Java Agent.
