### ISSUE TITLE
Missing traces with mongo driver 4.10

### ISSUE THREAD

**Issue by gmariottiAtWolt** [DataDog/dd-trace-java#5702]
Could anyone confirm that the dd-agent works with the latest version `mongodb-driver`? In my team we are currently using the latest agent version and noticed that Mongo traces are missing when using `org.mongodb:mongodb-driver-core` and `org.mongodb:mongodb-driver-reactivestreams` version `4.10.2`, while they are there if we rollback to version `4.9.1` of the driver.

**Comment by ygree** [comment]
I've found the source of this issue. It is that in mongo-java-driver starting from 4.10 some instumented classes has changed method signatures.
Specifically, the BaseCluster and DefaultConnectionPool classes have changed the selectServerAsync and getAsync method signatures.
It is very likely that fixing this will fix the entire problem.
