### ISSUE TITLE
Don't write the body of ElasticSearch traces by default

### ISSUE THREAD

**Issue by matze121413** [DataDog/dd-trace-java#5718]
**Describe what happened:**
When you integrate ElasticSearch with the Datadog Agent, it will write the body of all ElasticSearch Traces into the metadata.

**Describe what you expected:**
As the body can contain sensitive information, it shouldn't write the body into the traces as default, like in every other HTTP Request. This behavior should be explicitly set.

**Steps to reproduce the issue:**
1. Integrate ElasticSearch with the Datadog Agent
2. Send some request to ElasticSearch
3. Go to "Traces" -> "your ElasticSearch Service"
4. Click on a request and go to "METADATA" and you will see the body of the request

**Comment by bantonsson** [comment]
Hi @matze121413 I'm not sure why this behavior is the default behavior, but it can be turned off by setting either `-Ddd.trace.elasticsearch.body-and-params.enabled=false` or `DD_TRACE_ELASTICSEARCH_BODY_AND_PARAMETERS_ENABLED=false`

**Comment by matze121413** [comment]
Hi @bantonsson, thanks! We figured that out. It would just be nice to don't run into that problem in the first place.

**Comment by bantonsson** [comment]
This is not closed until the release.
