### ISSUE TITLE
Memory leak with agent 1.19.0?

### ISSUE THREAD

**Issue by ghostdogpr** [DataDog/dd-trace-java#5721]
A week ago we released a new version of our software (using JDK 17) and noticed that memory usage kept increasing.
After taking a closer look, we found that both Heap and Non-heap metrics were stable but the growing memory was in the "other" memory section. According to [this](https://www.yourkit.com/docs/kb/sizes.jsp), what's neither Heap or Non-heap is "JVM code itself, JVM internal structures, loaded profiler agent code and data, etc.", which is why I suspected the datadog agent (+ the fact there was a new release).

We tried downgrading to 1.18.3 (with the exact same code), and the memory usage went back to normal.
Below is a picture of the memory usage, the middle part is 1.19.0 while before and after are 1.18.3.
<img width="2213" alt="Screen Shot 2023-08-16 at 10 27 55 AM" src="https://github.com/DataDog/dd-trace-java/assets/7413894/fb8fb31b-11f8-44c8-ab31-8efda5099859">

**Comment by ghostdogpr** [comment]
Sure, we only have `-Ddd.profiling.enabled=true`.

**Comment by ghostdogpr** [comment]
Hmm... we don't really want to do that in production as it is quite dangerous if it happens again (we're a large multiplayer online game). The issue can't be observed easily in other environments as there is very little load. We might be able to test it later but not right now.

**Comment by bantonsson** [comment]
I completely understand that @ghostdogpr. Thanks again for reporting.

**Comment by ghostdogpr** [comment]
OS: Alpine Linux v3.18
JVM Version: OpenJDK 64-Bit Server VM (17.0.7+7) for linux-amd64-musl JRE (17.0.7+7)
CPU: Intel

**Comment by jbachorik** [comment]
Hi @ghostdogpr, would you be able to open a support ticket so we can your org id and inspect the data more closesly.
We are using the same version internally and haven't noticed the increased memory usage yet so it will take some investigation before I can come back with an answer, and having the support ticket would help.

Cheers.

**Comment by ghostdogpr** [comment]
Opened ticket #1311173

**Comment by akmryuck** [comment]
After upgrading to 1.19.0 we are also seeing the same behavior in an EC2 Linux/ARM64 instance. We were able to remediate this by rolling back to 1.18.3.

**Comment by bantonsson** [comment]
Hi @akmryuck, thanks for reporting this. Are you running with profiling enabled or disabled? This would help us to further pinpoint the issue.

**Comment by richardstartin** [comment]
@bantonsson this is definitely a profiling defect - we're working on it.

**Comment by jbachorik** [comment]
The feature with the suspected leak in profiler was rolled back and the fix was released as 1.19.2

Please, give it a try if you can.
Thanks!

**Comment by akmryuck** [comment]
@bantonsson sorry for the delay, I was testing the 1.19.2 release before responding.
Yes, we use profiling.
Even better news, the 1.19.2 release does **not** exhibit the memory issue we were seeing in 1.19.1 ! 
Thank you for the quick fix!

**Comment by jbachorik** [comment]
@akmryuck 
Not at all. Sorry for the troubles :(
