### ISSUE TITLE
Support MUnit in CI Tests

### ISSUE THREAD

**Issue by atty303** [DataDog/dd-trace-java#5760]
[MUnit](https://scalameta.org/munit/) is a Scala testing framework and is based on JUnit4.
Since the current dd-java-agent supports JUnit, I thought it would automatically support MUnit as well, but although there are signs that it is trying to collect reports, the test cases are not recognized.

```
[dd.trace 2023-08-23 18:33:27:090 +0900] [main] DEBUG datadog.trace.civisibility.events.TestEventsHandlerImpl - Ignoring finish event, could not find test with name GenerateScheduleDates, suite nameglaze.del
GenerateScheduleDatesTest and class class glaze.delivery.backend.driver.scheduler.model.service. service.GenerateScheduleDatesTest
```

I will try to debug dd-java-agent here as well, but I think the current JUnit support needs to be made more generic or MUnit support needs to be added.

**Comment by atty303** [comment]
@nikita-tkachenko-datadog 
Thank you very much. I will share what I have found out.

dd-java-agent did not recognize the test cases because it could not detect the test suite.
MUnit calls JUnit's Suite constructor in the following places.

https://github.com/scalameta/munit/blob/v0.7.29/junit-interface/src/main/java/munit/internal/junitinterface/JUnitComputer.java#L52

This constructor initializes the ParentRunner's TestClass with null.

https://github.com/junit-team/junit4/blob/r4.13.2/src/main/java/org/junit/runners/Suite.java#L80-L82

As a result, the description of the testSuiteStarted event was null, and Suite information was not collected correctly.

https://github.com/DataDog/dd-trace-java/blob/v1.19.3/dd-java-agent/instrumentation/junit-4.10/src/main/java/datadog/trace/instrumentation/junit4/JUnit4SuiteEventsInstrumentation.java#L66

Note that since MUnit is based on JUni 4.13, it calls the testSuiteStarted method of RunNotifier, which was added in JUnit 4.13.

https://github.com/junit-team/junit4/blob/r4.13.2/src/main/java/org/junit/runner/notification/RunListener.java#L86

I implemented this in dd-java-agent's TracingListener and was able to verify that the Suite was collected correctly and the test was reflected on the Datadog site. However, I could not figure out how to code to support both JUnit 4.10 and 4.13 on my end.

**Comment by nikita-tkachenko-datadog** [comment]
Thank you very much for these details.

I have fixed the test suite events problem and a couple of other minor issues in [this PR](https://github.com/DataDog/dd-trace-java/pull/5781).
I was not familiar with MUnit so I only tested the basic cases, but looking at their docs it does not seem like there's anything else that needs explicit support (e.g. they don't have parameterized tests or nested suites, as far as I understood).

We normally have a release every couple of weeks, but if you're willing you can download the [snapshot build](https://output.circle-artifacts.com/output/job/889ffa84-709c-4f44-95ca-a2c349a0a5b0/artifacts/0/libs/dd-java-agent-1.20.0-SNAPSHOT.jar) and give it a try - that way if anything goes wrong, I'll be able to provide you with the fix faster.

**Comment by nikita-tkachenko-datadog** [comment]
@atty303, [release v1.20.0](https://repo1.maven.org/maven2/com/datadoghq/dd-java-agent/1.20.0/) is out now. It includes the MUnit support changes, so feel free to try it out, and please let me know if there's anything that does not work as expected. Thank you!

**Comment by atty303** [comment]
@nikita-tkachenko-datadog  I can confirm that it works smoothly for me. Thank you very much for your support!
