### ISSUE TITLE
Agent metrics are considered custom metrics in Datadog

### ISSUE THREAD

**Issue by florianmutter** [DataDog/dd-trace-java#5808]
In our dashboard we see metrics like `ddtrot.dd.tracer.tracer.trace.buffer.fill.time` that are created by the agent it self ( I think here: https://github.com/DataDog/dd-trace-java/blob/ccdadbf2def4f84ccc98f279d0981ae84d011646/dd-trace-core/src/main/java/datadog/trace/common/writer/PayloadDispatcherImpl.java#L89)

Those metrics show up as custom metrics in the dashboard and we are billed for them. I think this should not be the case. Any metric that is created by the datadog agent should be included.

Could this be due to the shading of internal packages? https://github.com/DataDog/dd-trace-java/blob/4818319bb7893b61fba4c8ef9af76bf1c7bda4ab/dd-trace-ot/build.gradle#L108

Support case regarding this here: https://help.datadoghq.com/hc/en-us/requests/1320104

**Comment by mcculls** [comment]
Hi @florianmutter - yes this looks like an issue with the shading configuration, thanks for reporting it

**Comment by mcculls** [comment]
@florianmutter can you confirm which version of the `dd-trace-ot` library you are using?

**Comment by mcculls** [comment]
Hi @florianmutter this has been addressed in https://github.com/DataDog/dd-trace-java/pull/5810 which will be in the next release of the Java tracer (1.20.0)
