### ISSUE TITLE
Support Apache Pekko framework

### ISSUE THREAD

**Issue by mox692** [DataDog/dd-trace-java#5811]
Recently, [Apache Pekko](https://github.com/apache/incubator-pekko) released their first major release v1.0.0. Is there any plan for automatically tracing support for Apache Pekko?

This web framework is based on akka-http and emerged as a community-based fork during [the licensing changes of the akka library](https://www.lightbend.com/blog/why-we-are-changing-the-license-for-akka). Since Pekko 1.0.0 is mostly based on akka 2.6, which makes migration relatively easy, and licensing fees can become expensive for heavy akka users, some companies have shifted from akka-http to the Pekko.

Since [`dd-trace-java` already supports akka-http](https://docs.datadoghq.com/tracing/trace_collection/compatibility/java/#web-framework-compatibility), I believe adding support for Pekko wouldn't be too difficult.

**Comment by bantonsson** [comment]
This will be released in `1.21.0`
