### ISSUE TITLE
-Ddd.integration.throwables.enabled=false not working since 1.19

### ISSUE THREAD

**Issue by ghostdogpr** [DataDog/dd-trace-java#5825]
We used this setting `-Ddd.integration.throwables.enabled=false` to disable exception profiling.
It worked well with the agent version 1.18 but from 1.19 exceptions are being profiled despite the setting.

1.18:
<img width="459" alt="Screen Shot 2023-09-04 at 2 44 55 PM" src="https://github.com/DataDog/dd-trace-java/assets/7413894/08a1298b-3669-4466-be36-409b2c9a9e37">
1.19:
<img width="342" alt="Screen Shot 2023-09-04 at 2 45 15 PM" src="https://github.com/DataDog/dd-trace-java/assets/7413894/77cb67f5-8db6-4e4b-94ca-502b4e6ef873">

**Comment by richardstartin** [comment]
Thanks for the report, we'll get this fixed ASAP.

**Comment by richardstartin** [comment]
Fixed in 1.21.0

**Comment by richardstartin** [comment]
hi @ghostdogpr could you share some details about why you disable exception profiling?

**Comment by ghostdogpr** [comment]
@richardstartin I disabled it because it's recommended in Datadog docs 😆 https://docs.datadoghq.com/profiler/profiler_troubleshooting/java/#exceptions-overwhelming-the-profiler
We are using a library (ZIO) that relies on exceptions for control flow so it generates a LOT of exceptions (they have no stack trace so performance is good). I haven't observed problems in production with exception profiling but I did observe slowdowns locally with another profiler (YourKit), so I prefered to be safe and disable it with Datadog.

**Comment by richardstartin** [comment]
In 1.23.0 we will avoid instrumenting throwable types like `ControlThrowable` which should hopefully increase SNR of exception profiling for Scala applications.
