### ISSUE TITLE
Security vulnerability in com.fasterxml.jackson.core_jackson-core <2.15.0

### ISSUE THREAD

**Issue by dAnjou** [DataDog/dd-trace-java#5844]
Hi 👋 

The scanner we use in our project, Prisma, has flagged a vulnerability in [com.fasterxml.jackson.core_jackson-core <2.15.0](https://github.com/FasterXML/jackson-core/pull/827):

> Description: com.fasterxml.jackson.core_jackson-core package versions before 2.15.0 are vulnerable to Denial of Service (DoS). The package does not properly restrict the size or amount of resources that are requested or influenced by an actor, which can be used to consume more resources than intended and leads to Uncontrolled Resource Consumption (\'Resource Exhaustion\').

Prisma gives it the ID PRISMA-2023-0067 (can't find a reference online though), a CVSS value of 7.5, and a severity HIGH.

Is it possible to bump the version of jackson-core in the next release?

🙏

**Comment by mcculls** [comment]
Hi @dAnjou - we'll be releasing 1.20.1 soon which removes this unused dependency.

This dependency is a transitive dependency of JMXFetch, but isn't actually used in the way we embed JMXFetch into the Java tracer. In other words, while the `dd-java-agent` jar contained this library it was never actually loaded or called.

**Comment by dAnjou** [comment]
Thank you very much for this speedy response 🙏

**Comment by mcculls** [comment]
Hi @dAnjou - Java Tracer [1.20.1](https://github.com/DataDog/dd-trace-java/releases/tag/v1.20.1) has just been released to address this issue.

**Comment by sayali-sawant** [comment]
Hi, can you help how to solve the Security vulnerability in com.fasterxml.jackson.core_jackson-core
