### ISSUE TITLE
DSM for AWS SQS v1

### ISSUE THREAD

**Issue by darin-holloway** [DataDog/dd-trace-java#5850]
The comment on the SQSv2 pr made it seem like it was going to be trivial/quick to add v1 support 

https://github.com/DataDog/dd-trace-java/pull/5637

Just adding an issue for tracking support for it since it didn't appear in 1.19 or 1.20 yet.

**Comment by JeanFred** [comment]
Covered by #6259?

**Comment by darin-holloway** [comment]
It appears that way, I'll try to carve out some testing time on our side to confirm, but thank you for the tag @JeanFred

**Comment by darin-holloway** [comment]
Confirmed SQS on SDKv1 is working now
