### ISSUE TITLE
custom instrumentation error 

### ISSUE THREAD

**Issue by callmediaomao** [DataDog/dd-trace-java#5871]
error: Cannot map this reference for static method or constructor start: public static synchronized javax.management.ObjectName com.alibaba.druid.stat.DruidDataSourceStatManager.addDataSource(java.lang.Object,java.lang.String).
I looked at other examples but didn't solve the problem.

![image](https://github.com/DataDog/dd-trace-java/assets/63587783/31716db2-25c2-4fc7-aa6f-cba8452db67b)

**Comment by bantonsson** [comment]
Hi @callmediaomao could you share some more details. Maybe you have the code in an project somewhere that could be looked at?

**Comment by callmediaomao** [comment]
Hi @bantonsson This is the code.
```
@AutoService(Instrumenter.class)
public class DruidAddDataSourceInstrumentation extends Instrumenter.Tracing
    implements Instrumenter.ForSingleType {

  public DruidAddDataSourceInstrumentation() {
    super("druidDatasource","datasource");
  }

  public String instrumentedType() {
    return "com.alibaba.druid.stat.DruidDataSourceStatManager";
  }

  public String[] helperClassNames() {
    return new String[]{
        packageName + ".DataSourceDecorator",
    };
  }

  public Map<String, String> contextStore() {
    return Collections.singletonMap("java.sql.Connection", DBInfo.class.getName());
  }

  public void adviceTransformations(AdviceTransformation transformation) {
    transformation.applyAdvice(
        isMethod()
            .and(isStatic())
            .and(named("addDataSource"))
            .and(takesArguments(2).and(takesArgument(0, Object.class)))
            .and(returns(named("javax.management.ObjectName"))),

        DruidAddDataSourceInstrumentation.class.getName() + "$DataSourceAdvice"
    );
  }

  public static class DataSourceAdvice {

    @Advice.OnMethodEnter(suppress = Throwable.class)
    public static AgentScope onEnter(
        @Advice.This final DruidDataSourceStatManager ds,
        @Advice.Argument(0) final Object druidDataSource
    ) {
      try {
        AgentSpan span = startSpan("datasource", "datasource.addDataSource");
        DataSourceDecorator.DECORATE.afterStart(span);
        Connection connection = ((DruidDataSource)druidDataSource).getConnection();
        DataSourceDecorator.DECORATE.onConnection(span,connection, InstrumentationContext.get(Connection.class, DBInfo.class));
        AgentScope agentScope = activateSpan(span);
        connection.close();
        return agentScope;
      } catch (SQLException e) {
        return null;
      }
    }

    @Advice.OnMethodExit(onThrowable = Throwable.class, suppress = Throwable.class)
    public static void stopSpan(
        @Advice.Enter final AgentScope scope,
        @Advice.Thrown final Throwable throwable) {
      if (scope == null) {
        return;
      }
      DataSourceDecorator.DECORATE.onError(scope, throwable);
      DataSourceDecorator.DECORATE.beforeFinish(scope);
      scope.close();
      scope.span().finish();
    }
  }
}
```

Gradle build.gradle 
```
apply from: "$rootDir/gradle/java.gradle"
apply plugin: 'call-site-instrumentation'

dependencies {
  compileOnly group: 'com.alibaba', name: 'druid', version: '1.1.22'
  compileOnly group: 'com.zaxxer', name: 'HikariCP', version: '3.2.0'
}
```

the error info

![](https://user-images.githubusercontent.com/63587783/267860343-aa1ff846-2a6d-416a-864d-2ba71a58564b.png)

**Comment by bantonsson** [comment]
@callmediaomao You can't use the `@Advice.This` on the method, since it's a `static` method that doesn't have a `this` object instance.

**Comment by callmediaomao** [comment]
@bantonsson Thank you!!!! I know why! My first time using byteBuddy.Many places are not very clear.

**Comment by callmediaomao** [comment]
@bantonsson Could you do me a favor about another question? I also want to ask a question about whether custom instrument are not effective.Now I will migrate the instrument of SkyWalking to datadog.
```
@AutoService(Instrumenter.class)
public class SpringTxInstrumentation extends Instrumenter.Tracing
    implements Instrumenter.ForSingleType {

  private static final Logger log = LoggerFactory.getLogger(SpringTxInstrumentation.class);

  public static final String CLASS_NAME = "org.springframework.transaction.support.AbstractPlatformTransactionManager";

  public SpringTxInstrumentation() {
    super("spring-tx");
  }

  @Override
  public String[] helperClassNames() {
    return new String[]{
        packageName + ".SpringTxDecorator",
        packageName + ".GetTransactionAdvice",
        packageName + ".CommintOrRollbackAdvice"
    };
  }

  @Override
  public String instrumentedType() {
    return CLASS_NAME;
  }

  @Override
  public void adviceTransformations(AdviceTransformation transformation) {
    transformation.applyAdvice(
        isMethod()
            .and(named("getTransaction")),
        packageName + ".GetTransactionAdvice"
    );

    transformation.applyAdvice(
        isMethod()
            .and(named("commit").or(named("rollback"))),
        packageName + ".CommintOrRollbackAdvice"
    );
  }
}
```

Gradle build.gradle
```
apply from: "$rootDir/gradle/java.gradle"
apply plugin: 'call-site-instrumentation'

dependencies {
  compileOnly group: 'org.springframework', name: 'spring-tx', version: '[5.0.4.RELEASE,5.1.10.RELEASE]'
}
```

I used skywalking's spring-tx-scenario to test the demo.The pom.xml
<img width="1470" alt="截屏2023-09-14 17 59 13" src="https://github.com/DataDog/dd-trace-java/assets/63587783/1a56b7ce-0233-4f7d-a48e-34f6aa008ee4">

I run tests without these logs.
`[dd.trace 2023-09-14 15:39:14:441 +0800] [main] DEBUG datadog.trace.agent.tooling.InstrumenterState - Instrumentation applied - instrumentation.names=[java_concurrent,runnable] instrumentation.class=datadog.trace.instrumentation.java.concurrent.RunnableInstrumentation instrumentation.target.classloader=org.springframework.boot.loader.LaunchedURLClassLoader@20e3c449
`
I think the dependency should have been resolved, but it didn't take effect.

![](https://user-images.githubusercontent.com/63587783/267862023-46be6c8c-9810-4f65-bd40-8dc521df8af3.png)

**Comment by PerfectSlayer** [comment]
Hi @callmediaomao 
If I get it right, you implemented your own automatic instrumentation for `Spring TX`, make a custom build of the Java tracer with it, and run this build against a demo application called `spring-tx-scenario`.

So, what do you call _custom instrument are not effective_?

To check your instrumentation is well loaded and applied, you can find the following lines from the tracer debug logs:
```
DEBUG datadog.trace.agent.tooling.InstrumenterState - Instrumentation applied - instrumentation.names=[<intrumentation_name_list>] instrumentation.class=<instrumentation_class_name> instrumentation.target.classloader=...
```
Near this line could be more debug log about your instrumentation loading (like injected helper class, field storage, etc...).

**Comment by callmediaomao** [comment]
Hi @PerfectSlayer 
I saw the log only printed  `Loading - instrumentation.class= .....` , but there's no print `starting matches class loader instrumentation:instrumentation.names=.....` and `DEBUG datadog.trace.agent.tooling.InstrumenterState - Instrumentation applied - instrumentation.names=[<intrumentation_name_list>] instrumentation.class=<instrumentation_class_name> instrumentation.target.classloader=...` 
<img width="1009" alt="截屏2023-10-16 17 41 57" src="https://github.com/DataDog/dd-trace-java/assets/63587783/77be2fb9-9b19-4b43-a543-f36ac4752ae3">
I printed all the Typedescriptions at CombiningMatcher and found no spring transaction related classes.
Like this `org.springframework.jdbc.datasource.DataSourceTransactionManager` and `org.springframework.transaction.PlatformTransactionManager`
<img width="1381" alt="截屏2023-10-16 17 42 54" src="https://github.com/DataDog/dd-trace-java/assets/63587783/8b63787f-8e3c-4db8-97ee-2180582778ca">

**Comment by mcculls** [comment]
Hi @callmediaomao - if there's a loading issue with your instrumentation then it won't be registered, in which case those spring-tx types might not reach the combining matcher, because the tracer does a lot of optimization to reduce matcher costs. If that's the case then there's probably a message earlier in the log about your instrumenter.

One common issue is creating a logger in the instrumenter and then referring to it in the advice - while the advice can see it at build time it won't at instrumentation time. This is because the advice bytecode is really just a template which gets lifted and inserted into the application/library method. So advice can only refer to bootstrap types like the AgentTracer classes, application types, and any helpers listed in helperClassNames.

**Comment by callmediaomao** [comment]
Hi @mcculls Sorry,I don't quite understand that last sentence. It seems to me that all classes will match this method unless you filter it out earlier.All instrumention passes through this code.
<img width="724" alt="截屏2023-10-17 16 21 24" src="https://github.com/DataDog/dd-trace-java/assets/63587783/58022f31-3ed3-4c1a-871c-89dae5619516">
Is the bootstrap in your sentence `Instrumenter.ForBootstrap`?

**Comment by mcculls** [comment]
Hi @callmediaomao - if your instrumentation matches a single or multiple known types then it will get matched by this line:
```
    knownTypesIndex.apply(target.getName(), knownTypesMask, ids);
```
in other words it won't have a separate matcher for that instrumentation, it will be matched using the known types index (we scan the instrumenters and generate the known-types index at build time so we can optimize matching on known types.)

Regarding what bootstrap types an advice can see, it's basically those types that get added to the boot-class-path when the agent attaches to the JVM, ie. types from
* `dd-trace-api`
* `internal-api`
* `agent-bootstrap`

plus anything that was on the boot-class-path already.

**Comment by mcculls** [comment]
Regarding injection, if you have a class called `FooInstrumentation` which has an advice class called `FooAdvice` then the thing that gets injected into the application class-loader is not `FooInstrumentation` or `FooAdvice` because those are just a way to describe what to inject and where. The actual thing injected is just the _bytecode_ from `FooAdvice`, which is added to the start of the method for OnEntry or the end of the method for OnExit.

So while you could add a reference to `FooInstrumentation` from `FooAdvice` which would still compile, it couldn't be injected because when byte-buddy lifts the bytecode to try and inject it into the application method then it won't be able to resolve any reference to `FooInstrumentation` because that type is never injected into the application.

**Comment by callmediaomao** [comment]
@mcculls I know what you mean.Whether my instrumentation is single, multiple knowledge, or ForTypeHierarchy, the types cannot be matched through bytebuddy. You can refer to my SpringTxInstrumentation code above.
<img width="811" alt="截屏2023-10-18 12 29 34" src="https://github.com/DataDog/dd-trace-java/assets/63587783/77249482-583e-4d79-ad57-6f07bf89b18f">
<img width="791" alt="截屏2023-10-18 11 49 58" src="https://github.com/DataDog/dd-trace-java/assets/63587783/f68289b4-50ff-438d-8739-bd60491bb567">

The key point I want to know is why SpringTx related classes cannot be injected when the agent attaches to the JVM.
The tracer does a lot of optimization to reduce matcher costs but it should not filter out the injection classes of the main program.

**Comment by mcculls** [comment]
Hi @callmediaomao - apologies, I just remembered that we have some legacy global excludes for `spring-tx` in https://github.com/DataDog/dd-trace-java/blob/master/dd-java-agent/agent-tooling/src/main/resources/datadog/trace/agent/tooling/bytebuddy/matcher/ignored_class_name.trie#L317

If you add this line:
```
0 org.springframework.transaction.support.AbstractPlatformTransactionManager
```
under this existing line:
```
2 org.springframework.transaction.*
```
then it should now work.

We use this global ignores filter as a very cheap way to narrow the search space for Spring (which contains a lot of classes) so whenever we add a new Spring integration like `spring- tx` we need to check that it wasn't previously ignored. Since you're only interested in a single class the example about just un-ignores that class, mainly for performance reasons.But if you plan to instrument more classes then you could widen it to:
```
0 org.springframework.transaction.support
```

**Comment by callmediaomao** [comment]
Hi @mcculls Thank you very much.It's now in effect.Mainly because my understanding of butebuddy is still too little now.My personal feeling is that bytebuddy's documentation can only be used for beginners, and many functions are not yet understood.
