### ISSUE TITLE
WARN datadog.trace.agent.core.propagation.DatadogTagsFactory - Invalid datadog tags header value

### ISSUE THREAD

**Issue by ivankatliarchuk** [DataDog/dd-trace-java#5930]
Every  request where request header contains  something like `Key - tracestate | value - dd=s:1;o:synthetics;t.dm:--128` logs a message

```
WARN datadog.trace.agent.core.propagation.DatadogTagsFactory - Invalid datadog tags header value: '_dd.p.dm=--128' invalid tag value at 9
```

I'm struggling to identify how the `t.dm` or `_dd.p.dm` value is actually computed and under which circumstances it could have `--`.  I would assume any request with `t.dm:--XXXX` could be invalid.

**Comment by bantonsson** [comment]
Hi @ivankatliarchuk, the `dm=--128`, is the internal value _external override_ `0x80` escaping into a header, which shouldn't happen. Could you provide a little bit more information about:
* The version(s) of the tracer library you are using
* The propagation style(s) enabled (looks like `tracecontext` at least)
* If there are any other languages/runtimes, i.e. node, python, et.c., calling this service.

**Comment by ivankatliarchuk** [comment]
Hi @bantonsson . Thanks for looking at it
1. Java applications affected
```
The versions of the java tracer library of these apps are:

* 1.20.0~6308c0048e
* 1.2.0~a26b8ca0ff
* 1.20.1~70cd67ce90
* 1.19.0~b023c07015
* 1.18.2~0a1d7c2013
```
and configuration
```
{"version":"1.2.0~a26b8ca0ff","os_name":"Linux","os_version":"5.10.186-179.751.amzn2.x86_64","architecture":"amd64","lang":"jvm","lang_version":"17.0.5","jvm_vendor":"Amazon.com Inc.","jvm_version":"17.0.5+8-LTS","java_class_version":"61.0","http_nonProxyHosts":"null","http_proxyHost":"null","enabled":true,"service":"offer-orchestrator","agent_url":"http://10.1.208.123:8126","agent_error":false,"debug":false,"analytics_enabled":true,"sampling_rules":[{},{}],"priority_sampling_enabled":true,"logs_correlation_enabled":true,"profiling_enabled":false,"remote_config_enabled":false,"debugger_enabled":false,"appsec_enabled":"ENABLED_INACTIVE","telemetry_enabled":true,"dd_version":"0.53.0","health_checks_enabled":true,"configuration_file":"no config file present","runtime_id":"d527765f-94b9-4891-b7cd-892e1389e8f5","logging_settings":{"levelInBrackets":false,"dateTimeFormat":"'[dd.trace 'yyyy-MM-dd HH:mm:ss:SSS Z']'","logFile":"System.err","configurationFile":"simplelogger.properties","showShortLogName":false,"showDateTime":true,"showLogName":true,"showThreadName":true,"defaultLogLevel":"INFO","warnLevelString":"WARN","embedException":false},"cws_enabled":false,"cws_tls_refresh":5000}
```

2. I may need more information e.g. how to capture `tracecontext`
![Screenshot 2023-09-22 at 08 08 49](https://github.com/DataDog/dd-trace-java/assets/5395690/b4a0b63a-8377-419c-ac00-e143a88b5f73)

3. Yes, `.NET` applications making calls to Java applications

.Net version is `package Datadog.Trace --version 2.20.0`


We created a ticket in DD Support as well. The possible suggested fix is to update .Net tracer library.  [DD Support Request](https://help.datadoghq.com/hc/en-us/requests/1363755). 

Let's say we do not have a significant controll over our clients. Is there is a way to fix it in Java library e.g. reject incorrect tracer or smth?

**Comment by bantonsson** [comment]
@ivankatliarchuk The Java tracer will ignore this part of the trace information, but continue the rest of the trace. The logging is just very noisy and we probably need to fix that going forward.

As for the `tracecontext` part, since you referenced a header named `tracestate` I assumed that you had enabled `tracecontext` style propagation as well as `datadog` style propagation, but if the service that logs the warnings is running `1.2.0` then that can not be the case. There is probably a header in the requests named `x-datadog-tags` as well with `_dd.p.dm=--128` in it.

**Comment by ivankatliarchuk** [comment]
I do not think we are planning to turn off logging and only trace ERRORs. My understanding, some traces are not sent to datadog due to unsupported headers. Is there a way to actually fix it or the only way is to supress message with ERROR log level?

**Comment by bantonsson** [comment]
That logger level is only for the internal Java Tracer logging, and it was a suggestion if the logging is a problem for your service. Unfortunately right now, there is no other way to get rid of those log messages.

As for traces not being sent, the warning you see only means that a part of extra information about the trace is discarded since it is invalid. The rest of the trace will continue to propagate as normal.

**Comment by ivankatliarchuk** [comment]
Cool. I let the team now.

**Comment by beardpapa** [comment]
We've also observed this error starting to populate our java app logs.  This is on a vanilla installation using the auto-implementation libraries.  Versions are as follows:

`$agent_repo = 'https://yum.datadoghq.com/stable/7/x86_64/',
  $agent_version = '7.46.0-1', # datadog-agent-7.46.0-1.x86_64.rpm
  $apm_inject_version = '0.10.7-1', # datadog-apm-inject-0.10.7-1.x86_64
  $apm_java_version = '1.18.1-1', # datadog-apm-library-java-1.18.1-1.x86_64
  $apm_js_version = '4.1.0-1', # datadog-apm-library-js-4.1.0-1.x86_64.rpm`

**Comment by gaston-haro** [comment]
Similar issue here but after latest release. After https://github.com/DataDog/dd-trace-java/commit/30eeaf518512eb258b19dea41a5ea91e4c515561 we see a lot of **new** WARN level logs from the agent:

```
[dd.trace yyyy-MM-dd HH:mm:ss:SSS
 0000] [*
] WARN datadog.trace.agent.core.propagation.ptags.W3CPTagsCodec - Invalid datadog tags header value: 'dd=t.dm:3;s:[-1-2]
' invalid tag value at 8
```

**Comment by ahmed-envoy** [comment]
> Similar issue here but after latest release. After [30eeaf5](https://github.com/DataDog/dd-trace-java/commit/30eeaf518512eb258b19dea41a5ea91e4c515561) we see a lot of **new** WARN level logs from the agent:
> 
> ```
> [dd.trace yyyy-MM-dd HH:mm:ss:SSS
>  0000] [*
> ] WARN datadog.trace.agent.core.propagation.ptags.W3CPTagsCodec - Invalid datadog tags header value: 'dd=t.dm:3;s:[-1-2]
> ' invalid tag value at 8
> ```

We're experiencing the same issue, on version https://github.com/DataDog/dd-trace-java/releases/tag/v1.23.0

**Comment by ahmed-envoy** [comment]
> Similar issue here but after latest release. After [30eeaf5](https://github.com/DataDog/dd-trace-java/commit/30eeaf518512eb258b19dea41a5ea91e4c515561) we see a lot of **new** WARN level logs from the agent:
> 
> ```
> [dd.trace yyyy-MM-dd HH:mm:ss:SSS
>  0000] [*
> ] WARN datadog.trace.agent.core.propagation.ptags.W3CPTagsCodec - Invalid datadog tags header value: 'dd=t.dm:3;s:[-1-2]
> ' invalid tag value at 8
> ```

We started experiencing this same issue starting with [v1.24.1](https://github.com/DataDog/dd-trace-java/releases/tag/v1.24.1), previously we were using [v1.23.0](https://github.com/DataDog/dd-trace-java/releases/tag/v1.23.0)

**Comment by AdrianGnlz** [comment]
> > Similar issue here but after latest release. After [30eeaf5](https://github.com/DataDog/dd-trace-java/commit/30eeaf518512eb258b19dea41a5ea91e4c515561) we see a lot of **new** WARN level logs from the agent:
> > ```
> > [dd.trace yyyy-MM-dd HH:mm:ss:SSS
> >  0000] [*
> > ] WARN datadog.trace.agent.core.propagation.ptags.W3CPTagsCodec - Invalid datadog tags header value: 'dd=t.dm:3;s:[-1-2]
> > ' invalid tag value at 8
> > ```
> 
> We started experiencing this same issue starting with [v1.24.1](https://github.com/DataDog/dd-trace-java/releases/tag/v1.24.1), previously we were using [v1.23.0](https://github.com/DataDog/dd-trace-java/releases/tag/v1.23.0)

Same here, is there any workaround to fix this issue?

**Comment by ademar59** [comment]
We begin to have a big number of errror too with agent 1.25.1
Is it something plan?

**Comment by kwazii1231** [comment]
we also met same issue.
just to much error with latest agent jar

**Comment by bantonsson** [comment]
Hi, sorry for not getting back to you all earlier. The reason that this is happening more now, is because the Java Datadog Tracer since version 1.24+ is now parsing the W3C `tracecontext` headers by default, and there is some Datadog tracer in your system sending out those headers with illegal sample values (that's the `s:[-1-2]`).

We will implement log throttling for this, but it would be great if you could tell us  which **language** tracers and **versions** you have in your system.

**Comment by eliebleton-manomano** [comment]
> there is some Datadog tracer in your system sending out those headers with illegal sample values (that's the s:[-1-2])

We do not believe the -1 and 2 values to illegal priorities:

They're in use in existing dd-tracers:

[dd-trace-py // propagation/http.py](https://github.com/DataDog/dd-trace-py/blob/main/ddtrace/propagation/http.py#L142)
~~~
      - ``x-datadog-sampling-priority`` integer representing the sampling decision.
        ``<= 0`` (Reject) or ``> 1`` (Keep)
~~~        

[dd-trace-js // ext/priority.js](https://github.com/DataDog/dd-trace-js/blob/master/ext/priority.js)
~~~
  USER_REJECT: -1,
  AUTO_REJECT: 0,
  AUTO_KEEP: 1,
  USER_KEEP: 2
~~~

(And most likely more)

Such priorities also have dedicated logic in the trace-agent,code is [here](https://github.com/DataDog/datadog-agent/blob/77336caf87eee833a9e872b21ea30040ee0d1cc7/pkg/trace/sampler/prioritysampler.go#L114). 

I hope that the above elements are sufficient to demonstrate that support of -1 and 2 would be beneficial to dd-trace-java.

The word "illegal" you used is normative wording - I'm not aware of any public specification for dd-trace headers. The world would certainly benefit from having a specification - not for lack of alternatives, but for clarity and interop.

Cheers,

PS: Furthermore, I believe -2 or 3 should be legal as well, but it has various glitches from trace-agent to tracers that prevent their use. (i.e. who is "USER"? we run systems, we have developers, they're all being confused as "USER" today. It'd be clearer if I could say "-2/3" is from INTAKE_SYSTEM_A, "-3/4" is from COSTCONTROL_SYSTEM_A  and keep -2/1 for USER/OPERATOR/DEVELOPER/HUMAN decisions)

**Comment by bantonsson** [comment]
Hi @eliebleton-manomano, the problem is not the sampling priority `-1` or `2` or any other actual number, but the fact that the `tracestate` contains the sampling priority `[-1-2]` which is definitely *not* the string representation of an integer, and an *illegal* sampling priority.

**Comment by eliebleton-manomano** [comment]
Hi @bantonsson! Thanks for the quick reply and sorry for the misunderstanding. `[-1-2]` is definitely an illegal representation of an integer :) 

We are running into issues with this parser this morning and I was too quick to assume this was one and the same problem - turns out it isn't.  I'll go on and open a new issue describing what we ran into to reduce confusion.

**Comment by eliebleton-manomano** [comment]
> turns out it isn't. I'll go on and open a new issue describing what we ran into to reduce confusion.

That was also said too quick ...

We are seing a variant that has not yet been reported in this thread, but it does look quite similar:
~~~
WARN datadog.trace.agent.core.propagation.ptags.W3CPTagsCodec - Invalid datadog tags header value: 'dd=t.dm:4;s:-1' invalid tag value at 8
~~~

The only possibly helpful thing I can add with any confidence is that the calling system is running `dd-trace-js` .

I have yet to find out the original system that sent W3C propagation headers in the first place.

**Comment by bantonsson** [comment]
@eliebleton-manomano The `dm` part of the tag can consist of `{hash}-{mechanism}` and if there is no `hash` then the `mechanism` should be proceeded by a `-` sign. I would assume that `dd-trace-js` is encoding it in a bad way for some reason. Please reach out to them.

**Comment by wavermartijn** [comment]
@eliebleton-manomano Have you gotten any success on fixing the issue? We bumped into the same thing when we udated the DataDog agent

**Comment by eliebleton-manomano** [comment]
I have not and I have yet to report this in due form to the `dd-trace-j`s folks :sweat:
