### ISSUE TITLE
Create New Trace Always 

### ISSUE THREAD

**Issue by sonus21** [DataDog/dd-trace-java#6002]
I'm utilizing the Datadog tracer within a Java 8 environment, and my integration involves a Spring Boot application. In numerous instances, we wish to generate a new span using the `@Trace` annotation. Regrettably, this approach doesn't function as expected when applied to a method called from an executor. Similar to the Spring `Transactional` annotation, is there a method to consistently create a trace in specific scenarios?

```java
@Component
public class OrderAggregationsEventSubscriber extends EventSubscriber {
   ...
    @Override
    @Trace(operationName = "event.bus", resourceName="order-aggregator.process-order")
    public void processOrderEvent(Event event) {
    // logic
    }
}   
```

The issue here lies in the fact that `processOrderEvent` is a method called from the Guava event bus executor, but Datadog currently only generates a separate span for this method. However, what I desire is for it to create a new trace instead.

Current Flame Graph
<img width="1035" alt="Screenshot 2023-10-06 at 5 14 08 PM" src="https://github.com/DataDog/dd-agent/assets/11817278/38d16f4f-9fb8-422b-a2b4-e04942399232">

My expectation is that these spans (`*event.bus`) should remain independent of the original trace.

Java-dd-agent version: 0.90 => I know its too old, but we can't upgrade now, we do have to upgrade it. 
Datadog-api version=0.32 

How can we fix this issue?

**Comment by devinsba** [comment]
Moved the issue to the correct repo

**Comment by sonus21** [comment]
@devinsba is there anyway to fix it?

**Comment by sonus21** [comment]
@devinsba is there anyway to fix it?

**Comment by mcculls** [comment]
Hi @sonus21 - the default behaviour of `@Trace` has always been that it inherits the surrounding trace context if one exists. We can't change this default behaviour because many users rely on it, but we could look at adding an option to `@Trace` to explicitly force a new trace. This would be considered as a feature request.

As a temporary workaround, if you don't want the trace to propagate over a Guava executor then you could try turning off that integration:
```
-Ddd.integration.guava.enabled=false
```

If that doesn't help then you could turn off trace propagation over all executors:
```
-Ddd.integration.java_concurrent.enabled=false
```
however that would likely lead to a lot of disconnected traces so is not really recommended.

**Comment by sonus21** [comment]
Thanks, @mcculls . `-Ddd.integration.guava.enabled=false` did not work, I would propose to add a new feature to create custom trace based on the `Trace` parameter. 

We can't use `-Ddd.integration.java_concurrent.enabled=false` as we use Hystrix and others to deal with outgoing calls.

**Comment by mcculls** [comment]
Hi @sonus21 - FYI, we've implemented a new feature to help with this in https://github.com/DataDog/dd-trace-java/pull/6032 which will be available in the next release (1.22.0)

Note: to use it you would need to upgrade both `dd-java-agent` and `dd-trace-api` to 1.22.0

**Comment by sonus21** [comment]
@mcculls  let me know once its released, still I can't find this on Maven central.

**Comment by mcculls** [comment]
Hi @sonus21 - I should have been more clear that 1.22.0 will be released in the next week or so.

**Comment by mwisnicki** [comment]
How to do the same programmatically rather than through annotation?
