### ISSUE TITLE
Trace propagation not working with Reactor Netty clients using HTTP/2

### ISSUE THREAD

**Issue by louis-jaris** [DataDog/dd-trace-java#6081]
Hey folks, first of all thank you for your work, and for making observabilty fun and accessible; monitoring infrastructure, services, runtimes and so on never have been that easy.

--- 

## Bug
`dd-trace-java` is not propagating the current trace to downstream services (usually done thanks to `x-datadog*` header injection in the HTTP client request), because DataDog headers are not injected in the headers of the HTTP/2 request being sent to the downstream server.

## Setup
Standard Spring Boot application, using 3.1.X release (staying up to date).
As of Spring Boot 3.1.4, the version used of `reactor-netty-http` is `1.1.11`.

`dd-trace-java` latest version (installation done in `Dockerfile` using `https://dtdg.co/latest-java-tracer`)

JVM : Amazon Corretto 20

The HTTP service receiving requests sits behind an ALB. The HTTP client is configured to do HTTP/2 (c.f. code block below).

## To reproduce
Using Spring Boot 3.1.4, with the code below:

```java
public static void main(String[] args) {

        var connectionProvider = ConnectionProvider.builder("pool")
                .maxConnections(500)
                // AWS NAT Gateway will close the connection after 350 secs, and API's provider using AWS Global Accelerator after 30 seconds
                .maxIdleTime(Duration.ofSeconds(25))
                .pendingAcquireTimeout(Duration.ofSeconds(20))
                .evictInBackground(Duration.ofSeconds(20))
                .build();
        
        var client = HttpClient.create(connectionProvider)
                // Enable TLS verification with default context
                .secure()
                .protocol(HttpProtocol.HTTP11, HttpProtocol.H2)
                .compress(true)
                .responseTimeout(Duration.ofSeconds(10))
                .option(ChannelOption.CONNECT_TIMEOUT_MILLIS, 10000); // 10 sec

        // Configure TCP Keep Alive
        var tcpKeepIdleSec = 20;
        var tcpKeepIntervalSec = 20;
        var tcpKeepCount = 8;
        client.doOnChannelInit((observer, channel, address) -> {
            // Enable TCP Keep-Alive based on the channel used
            // c.f. https://projectreactor.io/docs/netty/release/reference/index.html#_tcp_level_configuration_2
            if (channel instanceof NioSocketChannel nioSocketChannel) {
                nioSocketChannel.config().setKeepAlive(true);
                nioSocketChannel.config().setOptions(Map.of(
                        NioChannelOption.of(ExtendedSocketOptions.TCP_KEEPIDLE), tcpKeepIdleSec,
                        NioChannelOption.of(ExtendedSocketOptions.TCP_KEEPINTERVAL), tcpKeepIntervalSec,
                        NioChannelOption.of(ExtendedSocketOptions.TCP_KEEPCOUNT), tcpKeepCount));
            }
            else if (channel instanceof EpollSocketChannel epollChannel) {
                epollChannel.config().setKeepAlive(true);
                epollChannel.config().setOptions(Map.of(
                        EpollChannelOption.TCP_KEEPIDLE, tcpKeepIdleSec,
                        EpollChannelOption.TCP_KEEPINTVL, tcpKeepIntervalSec,
                        EpollChannelOption.TCP_KEEPCNT, tcpKeepCount));
            }
        });
        
        var webClient = WebClient.builder()
                // The target must have to accept and negotiate for HTTP/2
                .baseUrl("https://example.com")
                .clientConnector(new ReactorClientHttpConnector(client))
                .defaultHeader(MediaType.APPLICATION_JSON_VALUE, MediaType.APPLICATION_JSON_VALUE)
                .build();
        
        // DataDog headers (starting with `x-datadog-`) are not propagated
        webClient.get()
                .uri("/v1/foo/{id}/bar", "123")
                .retrieve()
                .bodyToMono(String.class)
                .block();
    }
```

## Appendix

Example of headers received by a service being called using HTTP/2:
![Screenshot 2023-10-23 at 12 39 05](https://github.com/DataDog/dd-trace-java/assets/44304811/09cd4609-4dc7-44d5-aa34-774c970f3161)

Example of headers received by a service being called using HTTP/1.1:
![Screenshot 2023-10-23 at 12 45 26](https://github.com/DataDog/dd-trace-java/assets/44304811/f7b8f157-d09f-4a6f-a48a-9c8d3a2ce7a3)

**Comment by amarziali** [comment]
Thanks for having filed a so detailed issue. I can confirm that the http2 pipeline is not properly supporting at that time inject/extract propagation headers because its pipeline differs from the http 1.1 one that we are currently instrumenting.
I'm working on a fix for it

**Comment by louis-jaris** [comment]
I've spotted this PR https://github.com/DataDog/dd-trace-java/pull/6226 👀

**Comment by amarziali** [comment]
> I've spotted this PR #6226 👀
> 
> Thank you for the work ! 🙏

Hello, yes it's related to this ticket and normally it should mitigate also this issue. That PR is a broader work providing support for netty-reactor-http2. You can test an early build by using this [CI build](https://output.circle-artifacts.com/output/job/91c4e829-7adb-4b36-8d1c-b614caed8d3a/artifacts/0/libs/dd-java-agent-1.25.0-SNAPSHOT.jar). In this case please do not hesitate to add a feedback to know if there are regressions on your environment

**Comment by louis-jaris** [comment]
Unfortunately, I had to rollback my changes for internal H2 communication, so I cannot test in our environments (we put more value in trace linking than into internal H2 coms).

I hack a quick setup locally however if you want me to check - just let me know ✌️

**Comment by amarziali** [comment]
> Unfortunately, I had to rollback my changes for internal H2 communication, so I cannot test in our environments (we put more value in trace linking than into internal H2 coms).
> 
> I hack a quick setup locally however if you want me to check - just let me know ✌️

👋 thanks for the quick reply. If you would not mind a quick check (even local) is always welcome!

**Comment by louis-jaris** [comment]
I tested locally with the artefact you gave, and the header injection now works in H2! 🙌 

![Screenshot 2023-11-17 at 12 13 47](https://github.com/DataDog/dd-trace-java/assets/44304811/3ba8a079-da3d-4a25-aa4e-15035c423a0a)

Also, do you have some documentation or code to direct me to so that I can understand how these headers are generated and what these values means?

Especially `x-datadog-tags` values, and `x-datadog-sampling-priority` (I know that `0` will not trigger span generation while `1` does, but what `2` does precisely?)

---

Thanks again for this work and looking now for the release that contains this fix 👀

**Comment by amarziali** [comment]
👋 Sorry the late answer. Those tags are used internally and are related to sampling and distributed tracing. I cannot find public documentation I can point to. For the sampling priority, if you are curious about meaning of values, you can relate to https://github.com/DataDog/dd-trace-java/blob/master/dd-trace-api/src/main/java/datadog/trace/api/sampling/PrioritySampling.java

I closed the issue since the related fix is now on master waiting for the next release.

Cheers

Andrea
