### ISSUE TITLE
Spring WebClient tracing issue

### ISSUE THREAD

**Issue by cbuleandra** [DataDog/dd-trace-java#614]
Hi! I am trying to set-up tracing for a stateless GraphQL api-gateway (simple HttpServlet), which accepts requests at `POST /graphql`. The gateway makes use of [WebClient](https://github.com/spring-projects/spring-framework/blob/master/spring-webflux/src/main/java/org/springframework/web/reactive/function/client/WebClient.java) in order to call another service for retrieving data.

The problem I am facing is that both the `/graphql`, as well as the endpoints the api-gateway is calling are showing up in the resource list displayed in Datadog.

I have extracted the information on the traces below:
```
DDSpan [ t_id=6496705132716908527, s_id=3252327453084076151, p_id=0] trace=api-gateway/servlet.request/POST /graphql metrics={} tags={component=java-web-servlet, http.method=POST, http.url=http://localhost:9090/graphql, runtime-id=6407f4f3-21b7-4314-8b4e-6c50e1125e82, span.kind=server, span.origin.type=org.apache.catalina.core.ApplicationFilterChain, thread.id=63, thread.name=http-nio-9090-exec-10}, duration_ns=0

DDSpan [ t_id=7417067946456931379, s_id=5348444464491720869, p_id=0] trace=api-gateway/netty.client.request/GET /books/?/author metrics={} tags={component=netty-client, http.method=GET, http.status_code=200, http.url=http://localhost:8060/books/12345/author, peer.hostname=localhost, peer.port=8060, runtime-id=6407f4f3-21b7-4314-8b4e-6c50e1125e82, span.kind=client, thread.id=28, thread.name=reactor-http-nio-4}, duration_ns=50383986
```

It seems that the async `WebClient` request is not properly linked to the initial request.

The issue I am experiencing seems very similar to the one described here: https://github.com/htmldoug/datadog-netty4-failing/pull/1.

**Comment by tylerbenson** [comment]
@cbuleandra Thanks for the report.  I believe we currently only instrument the webflux server and don't have instrumentation for the client.  I will add a feature request for instrumentation for the client.  Meanwhile, you can try switching to a different supported client, or manually instrumenting it using the OpenTracing API.

**Comment by tylerbenson** [comment]
You will need to call
```java
GlobalTracer.get().inject(...)
```
to inject the trace and span ID headers into the client request.

You can look at how are netty client instrumentation works: https://github.com/DataDog/dd-trace-java/tree/master/dd-java-agent/instrumentation/netty-4.1/src/main/java/datadog/trace/instrumentation/netty41/client

You might be able to get the span to pass to inject using:
```java
GlobalTracer.get().activeSpan()
```
from inside your controller.

If so, the main effort would then be writing the TextMapAdapter.

**Comment by cbuleandra** [comment]
@tylerbenson Thanks for the hints. I was able to try it out, however I could not make it work. I did some debugging, trying to figure out what is going on, and I see these lines in the logs:
```
[reactor-http-nio-1] DEBUG datadog.trace.agent.ot.PendingTrace - traceId: 1258267499508995916 -- Expired reference. count = 2
[reactor-http-nio-1] DEBUG datadog.trace.agent.ot.PendingTrace - traceId: 1258267499508995916 -- Expired reference. count = 1
[reactor-http-nio-1] DEBUG datadog.trace.agent.ot.scopemanager.ContinuableScope - Failed to activate continuation. Reusing a continuation not allowed.  Returning a new scope. Spans will not be linked.
[reactor-http-nio-1] DEBUG datadog.trace.agent.ot.scopemanager.ContinuableScope - Failed to activate continuation. Reusing a continuation not allowed.  Returning a new scope. Spans will not be linked.
```
I will try to make some time and dig deeper into the agent, but in the meantime, is there something you can think of that might be causing this behaviour (i.e. spans will not be linked messages)?

**Comment by cbuleandra** [comment]
Never mind, I updated the agent version to a SNAPSHOT built locally from the current state of the repo, and these messages are no longer logged. Sorry for my previous message 🤦‍♂️ .
The span is still not propagated though, will keep digging.

**Comment by scdevops** [comment]
I created PR #831 to add support for WebClient. It's still rough around the edges but it's a start. Hope this is enough to speed things up.

**Comment by johanvandeweerd** [comment]
I created PR #831 to add support for WebClient. It's still rough around the edges but it's a start. Hope this is enough to speed things up.

**Comment by tylerbenson** [comment]
This is included in https://github.com/DataDog/dd-trace-java/releases/tag/v0.31.0
