### ISSUE TITLE
Upgrade integrations-core to 7.49.0 to fix embedded JMX metrics for Tomcat

### ISSUE THREAD

**Issue by michelzanini** [DataDog/dd-trace-java#6206]
This repository has a Git sub-module to integrations core pointing to version 7.47.0.
Can you please point it to the latest 7.49.0 release?

There's a fix I added there to support JMX metrics for Tomcat on Spring Boot (embedded tomcat):

https://github.com/DataDog/integrations-core/pull/15761
See file now:
https://github.com/DataDog/integrations-core/blob/7.49.0/tomcat/datadog_checks/tomcat/data/metrics.yaml

I can create a PR myself in case you want that.

Thanks.

**Comment by mcculls** [comment]
Hi @michelzanini - I've opened #6207 to address this, it will be in the next release (1.24.0)

**Comment by michelzanini** [comment]
Thank you!
