### ISSUE TITLE
Spans' parents in Opentelemetry

### ISSUE THREAD

**Issue by fokot** [DataDog/dd-trace-java#6253]
Hi we use datadog java agent to instrument the code automatically and Opentelemetry api to add custom attributes for spans.
This works great and I can add attributes to current span
```
Span span = Span.current();
if (span != null) {
  span.setAttribute("userId", userId);
  span.setAttribute("farmId", farmId);
```
But when I create a new span and start it, it is under the jdbc span i datadog dashboard
```
Span span = defaultTracer.spanBuilder(name).startSpan();
```
or probably both jdbc span and my custom span have the same parent. Is it posible that the jdbc span will have as parent the span created by otel?
![image](https://github.com/DataDog/dd-trace-java/assets/1210852/581c8e0b-972f-43c5-9079-f0e67f370413)
On this image you see that both spans have the same parent. But purple ones `postgresql.query` is from auto instrumentation. The blue one `reports.kpi.calculators..` is custom one and both have same parent even though the custom is longer and from that code the db is called.

**Comment by PerfectSlayer** [comment]
Hi @fokot 

If you want to have a trace looking like this:
```
[--- request GET ---------------------]
    [--- reports.kpi.calculators. ----]
        [--- postgresql.query ---]
```

You will need to activate your custom span using `span.makeCurrent()`:
```java
try (Scope scope = span.makeCurrent()) {
    // Anything related to the "calculator" processing, like the PostgreSQL call
}
```
Then, any child span will be the parent of the active span.
Don’t forget to close the created `Scope` when activating the span.

Best,
Bruce

**Comment by fokot** [comment]
I can not find this method `span.makeCurrent()`. Is it in `opentelemetry-api` or `dd-trace-api`?

**Comment by fokot** [comment]
Thanks a lot it works. The problem was I didn't understood Opentelemetry api. Here it is in more details https://opentelemetry.io/docs/instrumentation/java/manual/#create-nested-spans I need to do both `span.end()` as well as `scope.close()`
