### ISSUE TITLE
JDBC tracing misses batch statements executed through jOOQ

### ISSUE THREAD

**Issue by frommeyerc** [DataDog/dd-trace-java#6288]
Looking at our tracing I realised some traces where missing from the datadog flame graph. While jdbc interaction was in general recorded in the graph, some statements didn't show up. After making sure this is not related to retention of spans I identified that only batch statements were missing.
Looking at the agents source code, it appears that the instrumentation has a gap here. At least there is no specific handling of batches.

**Comment by nayeem-kamal** [comment]
Hi @frommeyerc thanks for sharing your issue. This is not unexpected as the tracer does not handle batch statements currently. We currently have an open feature request for handling batch statements for jdbc and this encompasses the issue you have brought up.
