### ISSUE TITLE
How to exclude a part of request in trace.span ?

### ISSUE THREAD

**Issue by sangyongchoi** [DataDog/dd-trace-java#6323]
Hi, i am using datadog.
I write a message because have a question.
How to exclude a part of request in trace.span ?
I hope exclude a part of app.request.grpc.params in traces.
Can you tell me how do?

thank you 😄

**Comment by bm1549** [comment]
Hi @sangyongchoi :wave: thanks for reaching out

Just so I know how to best help you, can you clarify what your goal is by excluding parts of a request? Do you want to limit your bandwidth, spend, simplify the UI, or something else?

**Comment by sangyongchoi** [comment]
Hi, @bm1549 
My purpose is exclude sensitive information (like private information) when send to trace.
thanks for answer.

**Comment by bm1549** [comment]
@sangyongchoi just so we know exactly which tag you'd like to exclude, could you create a Datadog support ticket with a link to a trace you'd like to exclude sensitive data from? That would help us identify exactly which code path you're referring to

https://www.datadoghq.com/support/

**Comment by bm1549** [comment]
Closing this out assuming a support ticket was created

**Comment by bantonsson** [comment]
Hi @sangyongchoi if you got to the [Datadog Support Platform](https://help.datadoghq.com/), which is the thing on the left, then you will find a link at the bottom to create a new ticket.

**Comment by sangyongchoi** [comment]
@bantonsson I confirmed and submmited.
thank you 😄
