### ISSUE TITLE
JBDC CallableStatement missing statement string

### ISSUE THREAD

**Issue by jwilt** [DataDog/dd-trace-java#633]
Hi

My application makes use of both PreparedStatements and CallableStatements, spans on PreparedStatements show the actual statement but for CallableStatements it shows "DB Query". Is it possible to see the actual statement? This also causes an issue with statistics because all CallableStatements get collected under the one resource name DB Query. 

Java 1.8.0_171
Server Wildfly 10.1.0
Oracle JDBC driver 11.2.0.3

**Comment by jwilt** [comment]
Here is a simple example

`
  public Map<Long,String> getOffices(long companyid) throws SQLException
  {
    Connection conn = null;
    CallableStatement stmt = null;
    ResultSet rset = null;
    Map<Long,String> lm = new LinkedHashMap<Long,String>();

    try
    {
      conn = ds.getConnection();
      stmt = conn.prepareCall( "{call BrandingAdminWebApp.getOffices(?,?)}");
      stmt.setLong(1,companyid);
      stmt.registerOutParameter( 2, OracleTypes.CURSOR );
      stmt.execute();
      rset = (ResultSet) stmt.getObject(2);
      while( rset.next())
        lm.put( rset.getLong("OFFICE_ID"), rset.getString("OFFICE_NAME"));
      return lm;
    }
    finally
    {
      try { rset.close(); } catch(Exception e) { ; }
      try { stmt.close(); } catch(Exception e) { ; }
      try { conn.close(); } catch(Exception e) { ; }
    }
  }
`

**Comment by jwilt** [comment]
Sorry forgot to include this is using v0.20.0

**Comment by tylerbenson** [comment]
@jwilt Thanks for that sample.  I think I was able to solve the problem.  Can you try [the build](https://14733-89221572-gh.circle-artifacts.com/0/home/circleci/dd-trace-java/libs/dd-java-agent-0.21.0-SNAPSHOT.jar) from the PR to confirm?

**Comment by jwilt** [comment]
Ah, was just getting ready to log off for the day. Thanks for the quick response but it is still not working correctly now the resource name is "?".

**Comment by tylerbenson** [comment]
@jwilt hmm... It might be helpful to get some debug logs from your application.  Would you mind opening a support ticket? (next week is fine, no rush.)

**Comment by tylerbenson** [comment]
Thanks for opening that ticket.  I'm going to call the original issue of `DB Query` as resource name resolved and close this issue and continue troubleshooting the `?` resource name there since I think that's a different problem.

**Comment by realark** [comment]
Fix shipped in tracer 0.21.0
