### ISSUE TITLE
Potential ClassCastException in AwsSdkClientDecorator

### ISSUE THREAD

**Issue by L-Applin** [DataDog/dd-trace-java#6528]
The `AwsSdkClientDecorator` class calls the [getValueForField("Key", String.class)](https://github.com/DataDog/dd-trace-java/blob/master/dd-java-agent/instrumentation/aws-java-sdk-2.2/src/main/java/datadog/trace/instrumentation/aws/v2/AwsSdkClientDecorator.java#L109) on the `SdkRequest` instance (from the AWS SDK for Java 2.x). It seems to be making the assumption that for s3, it is OK to call this method with `String.class`, which it is for s3. But the Java SDK has other `SdkRequest` class that have a "Key" field which are not a strings, especially in dynamo-db. For example, the `GetItemRequest` in dynamo-db has a "Key" field which is a map type, not String.

I cant link the source code of the `getValueForField` doing the cast because it is code-generated from a model source, but in the generated code the SDK tries to cast the field to the provided type, and will throw `java.lang.ClassCastException: Cannot cast java.util.Collections$UnmodifiableMap to java.lang.String`  in the cases where the "Key" field is not a String. Here is the generated code from the SDK:

```java
public final <T> Optional<T> getValueForField(String fieldName, Class<T> clazz) {
    switch (fieldName) {
    ...
    case "Key":
        return Optional.ofNullable(clazz.cast(key())); // <<< key() will return a Map, but clazz is String
    ...
```

This seems to prevent anyone from using Datadog Java APM with the AWS SDK for Java 2.x when dealing with AWS services, like dynamo-db, that have "Key" field which are not strings.

**Comment by L-Applin** [comment]
I notice this seems to be the root cause of #6524 and, like mentioned in that issue, was probably introduced in #6311

**Comment by bm1549** [comment]
Thank you for your patience and detailed report.
Our Java Engineering team was able to use this information to isolate the root cause and immediately roll back a change.
Can your team upgrade to the latest tracer [1.28.0-RC3](https://github.com/DataDog/dd-trace-java/releases/tag/v1.28.0-RC3) and confirm that it resolves the issue?

**Comment by L-Applin** [comment]
I believe the affected team was able to pin an older version which resolved the issue.
