### ISSUE TITLE
WARN com.datadog.appsec.powerwaf.PowerWAFModule 

### ISSUE THREAD

**Issue by dkirrane** [DataDog/dd-trace-java#6552]
I've followed the docs but I'm getting the following warning in our application logs. What does it mean?

`[dd.trace 2024-01-25 11:58:11:568 +0000] [main] WARN com.datadog.appsec.powerwaf.PowerWAFModule - WAF has rule against unknown address grpc.server.request.metadata`

**Comment by smola** [comment]
@dkirrane Application Security Management's WAF (i.e. `DD_APPSEC_ENABLED=true`) analyzes a number of request and response attributes internally called _addresses_. The warning means the tracer loaded a WAF rule (possibly through remote config) using an address that is not known or supported by the current tracer version. The warning is harmless and can be ignored.

This warning was removed in dd-trace-java v1.18.0 ([PR](https://github.com/DataDog/dd-trace-java/pull/5491)).
