### ISSUE TITLE
[Question] Passing tags from a parent span to a child span

### ISSUE THREAD

**Issue by delebota** [DataDog/dd-trace-java#6572]
I am doing some tracing on graphql code, and I'm struggling to find a way to pass some tags from a parent span down to child spans. I would like the clientId and queryIdentifier to be passed into the child spans.

```
final String clientId = requestParser.parseClientId( context.request() );
final String queryIdentifier = input.getOperationName() != null ?
		input.getOperationName().toLowerCase() : UNNAMED_GQL_METHOD;

Span span = Tracer.buildSpan( "REDACTED.graphql.query" );
span.setTag( DDTags.RESOURCE_NAME, queryIdentifier );
span.setTag( "query_identifier", queryIdentifier );
span.setTag( "client_id", clientId );
span.setTag( Tags.SPAN_KIND, Tags.SPAN_KIND_SERVER );
span.setTag( DDTags.SPAN_TYPE, DDSpanTypes.HTTP_SERVER );
```

![Screenshot 2024-01-26 at 3 28 01 PM](https://github.com/DataDog/dd-trace-java/assets/3606917/340929fd-4bd2-4842-9337-85ef6752ab4b)

**Comment by randomanderson** [comment]
The api method you're looking for is `setBaggageItem(String key, String value)` . Baggage is propagated forward to all child spans and reported to Datadog as tags

**Comment by delebota** [comment]
@randomanderson Thanks, exactly what I was looking for!
