### ISSUE TITLE
Missing statement and operation from JDBCDecorator

### ISSUE THREAD

**Issue by schmidti159** [DataDog/dd-trace-java#6630]
Hi,
we use dd-java-agent to instrument our Spring Boot services. We use Postgresql as DB.

We noticed the following problem: 
- Most of the time the spans created by JDBCDecorator contain `db.operation` and the prepared statement as `db.statement`:
![image](https://github.com/DataDog/dd-trace-java/assets/403598/435aa65c-594a-44e7-bbd0-5762e60022fd)
So it works as expected.
- But sometimes the `operation` is missing and the `statement` is only `postgresql.query`:
![image](https://github.com/DataDog/dd-trace-java/assets/403598/4e57cc6c-701f-42b5-937d-bec71a08f569)
- The error seems to always occur when we also have a parent-span from `java-jdbc-connection`
![image](https://github.com/DataDog/dd-trace-java/assets/403598/cc5d3c81-da9b-4c15-98b0-1192c0f9004d)
![image](https://github.com/DataDog/dd-trace-java/assets/403598/18bf3f91-a2bc-4fb1-adfb-81d26bc92f46)
For the spans with the correct data we do not see this parent span.

Any idea why this might happen and how we can get the correct statement in all the traces?

**Comment by amarziali** [comment]
Hello, 

that is usually linked to connection validation. Hikari, after opening a connection should validate it. This generates an empty statement: https://github.com/pgjdbc/pgjdbc/blob/6ab2fbadc09bbbf42c7c2f9abdc1789c48c8c5b5/pgjdbc/src/main/java/org/postgresql/jdbc/PgConnection.java#L1543
