### ISSUE TITLE
'Failed to retrieve remote configuration' − please allow to disable remote configuration

### ISSUE THREAD

**Issue by JeanFred** [DataDog/dd-trace-java#6640]
The logs of my Java applications have a lot of `Failed to retrieve remote configuration` which is noisy.
```
Failed to retrieve remote configuration: unexpected response code Internal Server Error 500 rpc error: code = Unknown desc = remote configuration service not initialized
```

I have not found any way to disable remote configuration in the java trace agent. [Docs](https://docs.datadoghq.com/agent/remote_config/?tab=environmentvariable#enabling-remote-configuration)  mention the `DD_REMOTE_CONFIGURATION_ENABLED` environment variable, but I did not find any reference to such an environment variable anywhere in the dd-trace-java code (contrary to the dd-trace-py code, see eg https://github.com/DataDog/dd-trace-py/issues/5212)

Please provide a way to disable this warning.

(as for why we the remote-configuration endpoint is not reachable − it’s because we exclusively use [Datadog PrivateLink](https://docs.datadoghq.com/agent/guide/private-link/) which unfortunately does not include that endpoint.)

**Comment by PerfectSlayer** [comment]
Hi @JeanFred 

If you would like to disable remove configuration on the tracer, you can set the `DD_REMOTE_CONFIG_ENABLED` environment to `false`.

**Comment by JeanFred** [comment]
Thanks for the answer  @PerfectSlayer 

> If you would like to disable remove configuration on the tracer, you can set the `DD_REMOTE_CONFIG_ENABLED` environment to `false`.

Right, per #6642 the env var name was different, that’s probably I could not find it :)

We have standardised on using [Java Configuration options](https://docs.datadoghq.com/tracing/trace_collection/library_config/java/#configuration-options) (the `-dDD_xyz` flags) − per  #4037 I see this would be `-Ddd.remote_config.enabled=false`.

You may want to document all this to https://docs.datadoghq.com/tracing/trace_collection/library_config/java/

> About having remote config works with private link, is that something you would like to get help with our support team?

We talked to Support about that already ; the answer was « we are working on getting more of our products including the domains you mentioned to use with PrivateLink. ». That was 8 months ago :-)

**Comment by PerfectSlayer** [comment]
Oh damned, sorry to hear that 😞 

In the meantime, I updated the tracer behavior to respect the `DD_REMOTE_CONFIGURATION_ENABLED` flag you found in the next version (`DD_REMOTE_CONFIG_ENABLED` will still work but be deprecated).
