### ISSUE TITLE
Support Unix Domain Sockets for JMX metrics reporting

### ISSUE THREAD

**Issue by mattdrees** [DataDog/dd-trace-java#665]
We'd like to use unix domain sockets for sending jmx metrics from our dockerized java apps. However, the currently-included version of java-dogstatsd-client doesn't support this. (It includes 2.1.0, and UDS support seems to have been added in 2.6.)

https://github.com/DataDog/jmxfetch/pull/207 may be helpful.

**Comment by tylerbenson** [comment]
We can upgrade when a new version of jmx fetch is released.  Is that all we will need to do?

**Comment by mattdrees** [comment]
Seems like it to me, yeah.

**Comment by mattdrees** [comment]
JMXFetch 2.27.0 was released last week with support for unix domain sockets. (Thanks to @arbll !)

**Comment by mattdrees** [comment]
awesome, thanks!

**Comment by tylerbenson** [comment]
This is included in the latest release: https://github.com/DataDog/dd-trace-java/releases/tag/v0.25.0
