### ISSUE TITLE
Why there is no trace.kafka.produce.* metrics?

### ISSUE THREAD

**Issue by endertunc** [DataDog/dd-trace-java#680]
After enabling datadog agent on one of our kafka streams applications, we started to see `trace.kafka.consume.*` metrics. I was also expecting to see `trace.kafka.produce.*` metrics since kafka streams application is also producing messages.

It would be nice if someone can help me to understand why we don't have `trace.kafka.produce.*` metrics.

dd-agent version: 0.17.0

Thanks in advance!

**Comment by endertunc** [comment]
Hi @tylerbenson thanks for the reply!  Hope you guys can add this feature in the near future!

**Comment by tylerbenson** [comment]
Since that will be a backend thing (not really tied to the trace client), do you mind if I close this issue?

**Comment by endertunc** [comment]
I just wanted to make sure that I am not missing anything. Please close the issue. Thanks for the support again!
