### ISSUE TITLE
Failed to inject helper classes

### ISSUE THREAD

**Issue by yomangg** [DataDog/dd-trace-java#6844]
Hi, my team recently updated from java 17 to 21. We started getting a lot of errors like this 
 ERROR datadog.trace.agent.tooling.HelperInjector - Failed to inject helper classes - instrumentation.class=ResponseInstrumentation instrumentation.target.classloader=org.springframework.boot.loader.launch.LaunchedClassLoader@15fb7a32 instrumentation.target.class=class org.apache.catalina.connector.Response
java.lang.UnsupportedOperationException: Cannot get defined package using reflection: Unable to make protected java.lang.Package java.lang.ClassLoader.getPackage(java.lang.String) accessible: module java.base does not "opens java.lang" to unnamed module @3aa9e816

Is this a misconfiguration issue? I couldn't find anything  in issues or readme related to it.
version:v1.31.2

**Comment by mcculls** [comment]
Hi @yomangg, is your application using JPMS? Are you able to provide a cut-down app/test that demonstrates the issue?

**Comment by yomangg** [comment]
We had issue with pipeline and it was using old version v1.10.1 instead of new one v1.31.2.  
Sorry for trouble
