### ISSUE TITLE
JVM metrics not starting when using resin container

### ISSUE THREAD

**Issue by brentm5** [DataDog/dd-trace-java#685]
When starting resin on version 0.22.0 we are seeing that the JMXFetch process never starts.  Upon digging in it seems to be related to #657 .  The [resin](https://caucho.com/) server itself depends on jboss-logging however we never call out to `java.util.logging.LogManager` so the hook to start jmxfetch never actually happens.

**Comment by tylerbenson** [comment]
Thanks for reporting.  This should be fixed by #684.

**Comment by brentm5** [comment]
#684 does not full resolve this issue.  We do have a possible workaround by providing the following:

```
-Ddd.app.customlogmanager=false
```

Long term we would definitely want to have a better story around configuring our services with JMX metrics.

**Comment by tylerbenson** [comment]
This should be fixed now by #714.  Sorry for the back and forth on this.  Thanks for your patience.

**Comment by tylerbenson** [comment]
This fix has been published: https://github.com/DataDog/dd-trace-java/releases/tag/v0.24.0
Thanks for your patience.
