### ISSUE TITLE
Trace id in logs are different from datadog trace id in web

### ISSUE THREAD

**Issue by lokesh1729** [DataDog/dd-trace-java#6896]
Hi,

I am using dd-trace-java in a spring boot project. I have added dd trace id and span id, in my logs like this
```
%d{yyyy-MM-dd HH:mm:ss} %-5p %c{1}:%L -
%X{dd.trace_id:-0} %X{ dd.span_id:-0} - %m%n"
```
I have observed that the trace id generated is an integer but when I see the trace id in datadog web console, it is alphanumeric. Why is that so? can't these two be same?

**Comment by amarziali** [comment]
Hello,

it looks like the logging is not by default printing the full traceid/spanid that are now 128 bit identifier.

You can try activating full 128 bit logging with:
* The env `DD_TRACE_128_BIT_TRACEID_LOGGING_ENABLED`
* The system property `-Dtrace.128.bit.traceid.logging.enabled=true`

Cheers

Andrea

**Comment by lokesh1729** [comment]
Thanks, it works. Closing the issue

**Comment by michaz** [comment]
It's not only in the logs. When I get the trace id programmatically through `dd-trace-api`, I also get the wrong id:

```
String traceId = GlobalTracer.get().getTraceId();
```
