### ISSUE TITLE
Logging confusion

### ISSUE THREAD

**Issue by sattvik** [DataDog/dd-trace-java#693]
Hello,

My application uses logback for logging.  Ideally, I'd like the dd-java-agent and instrumentations to use my application's preferences for logging.  Unfortuantely:

1. This is not the case.
2. The logging that does occur is not parsed by the default Java integration.

It seems like there's at least two different logging formats being used.  The first, which appears to come from the JMX integration and produces logs like:

```
2019-02-04 23:34:35,941 | INFO | App | Instance jmxfetch-config is sending 18 metrics to the metrics reporter during collection #110
2019-02-04 23:37:05,956 | INFO | App | Instance jmxfetch-config is sending 18 metrics to the metrics reporter during collection #120
2019-02-04 23:38:05,962 | INFO | Instance | Refreshing bean list
2019-02-04 23:38:05,978 | INFO | Instance | Found 12 matching attributes
```

The second appears to come from the agent itself and seems to be using the simple slf4j log format:

```
[main] INFO datadog.trace.agent.ot.DDTraceOTInfo - dd-trace - version: 0.23.0-SNAPSHOT~4953a6c4
[main] INFO datadog.trace.agent.ot.DDTracer - New instance: DDTracer-109f5dd8{ serviceName=auth-service, writer=DDAgentWriter { api=DDApi { tracesEndpoint=http://datadog-agent:8126/v0.3/traces } }, sampler=datadog.trace.agent.common.sampling.RateByServiceSampler@67fe380b, defaultSpanTags={}}
[main] INFO datadog.trace.agent.tooling.VersionLogger - dd-trace-ot - version: 0.23.0-SNAPSHOT~4953a6c4
[main] INFO datadog.trace.agent.tooling.VersionLogger - dd-trace-api - version: 0.23.0-SNAPSHOT~4953a6c4
[main] INFO datadog.trace.agent.tooling.VersionLogger - dd-java-agent - version: 0.23.0-SNAPSHOT~4953a6c4
[main] ERROR datadog.trace.agent.jmxfetch.JMXFetch - JMXFetch config: [datadog/trace/agent/jmxfetch/metricconfigs/activemq.yaml, datadog/trace/agent/jmxfetch/metricconfigs/solr.yaml, datadog/trace/agent/jmxfetch/metricconfigs/kafka.yaml, datadog/trace/agent/jmxfetch/metricconfigs/tomcat.yaml, datadog/trace/agent/jmxfetch/metricconfigs/cassandra.yaml] [] null null {runtime-id=cc0c90b3-dd58-4891-b94c-bc13e5203571, language=jvm, service=auth-service} statsd:datadog-agent:8125 System.err INFO
[dd-agent-writer] WARN datadog.trace.agent.common.writer.DDApi - Error while sending 5 of 5 traces to the DD agent. java.net.UnknownHostException: datadog-agent (going silent for 5 minutes)
```

Is there any guidance on how to manage this?

**Comment by tylerbenson** [comment]
You're correct.  Internally `dd-java-agent` uses [SimpleLogger](https://www.slf4j.org/api/org/slf4j/impl/SimpleLogger.html), but to avoid conflicting with other slf4j providers we remap the package at build time.  You can still use the system properties in that javadoc to reconfigure the log level, format, and output location.

Since you're asking about jmxfetch, I assume that means you've manually enabled it (it should be off by default right now).  You are correct though.  It has it's own logging system using [log4j](https://github.com/DataDog/jmxfetch/blob/master/pom.xml#L124-L126).  Even though we aren't remapping the package name, it is still confined to an isolated classloader, so it shouldn't conflict with what you're using.  I believe it should also be picking up the [config from within the classloader](https://github.com/DataDog/jmxfetch/blob/master/src/main/resources/log4j.properties)  We should investigate migrating it over to slf4j so it's consistent with the javaagent, any chance that would solve your concern.

**Comment by sattvik** [comment]
I appreciate your explanation.  I suppose there are a couple of ideas:

1. I agree that it would be nice to have both the dd-java-agent and jmxfetch log the same way.
2. Additionally, it'd be great if the logging format be one that is picked up automatically by the default Java log processor.  The formats the it seems to pick up include:

```
java_default (%{_date_ms}|%{_duration})\s+\[%{_thread_name}\]\s+%{_status}\s+%{_logger_name}\s*(%{_context}\s*)?- (?>%{word:dd.trace_id} %{word:dd.span_id} - )?%{data:message}((\n|\t)%{data:error.stack})?

java_slf4j %{_date_slf4j}\s+\[%{_thread_name}\]\s+%{_status}\s+%{_logger_name}\s*(%{_context}\s*)?- (?>%{word:dd.trace_id} %{word:dd.span_id} - )?%{data:message}((\n|\t)%{data:error.stack})?

java_log4j %{_date} %{_status}\s+%{_logger_name}:%{_line}\s+- (?>%{word:dd.trace_id} %{word:dd.span_id} - )?%{data:message}((\n|\t)%{data:error.stack})?

java_fallback (%{_date}|%{_date_ms}) %{_status}\s+(?>%{word:dd.trace_id} %{word:dd.span_id} )?%{data:message}((\n|\t)%{data:error.stack})?
```

**Comment by tylerbenson** [comment]
JMXFetch logging is being improved in the next release with #838, but I don't think we'll be changing the default log format.  I think you can override it though via a [SimpleLogger](https://www.slf4j.org/api/org/slf4j/impl/SimpleLogger.html) system property. (replacing `org` with `datadog` in the package name)

**Comment by tylerbenson** [comment]
This should be fixed in this release: https://github.com/DataDog/dd-trace-java/releases/tag/v0.29.0
Let us know if you see further issues.

**Comment by raj-saxena** [comment]
For someone coming here in future, the logs can be parsed by adding a grok parser to the pipeline with the following expression:
```
java_dd_tracer \[dd.trace %{_date}\] \[%{_thread_name}\] %{_status} %{_logger_name} - %{data:message}((\n|\t)%{data:error.stack})?
```
and helper rules:
```
_date %{date("yyyy-MM-dd HH:mm:ss:SSS Z"):timestamp}
_thread_name %{notSpace:logger.thread_name}
_status %{word:level}
_logger_name %{notSpace:logger.name}
```

<img width="1147" alt="Bildschirmfoto 2020-07-23 um 16 33 37" src="https://user-images.githubusercontent.com/6253803/88299175-5f41d500-cd02-11ea-9024-1f2e2aa554a1.png">
