### ISSUE TITLE
Hystrix Instrumented needs to register as a Service to allow creation of Monitors

### ISSUE THREAD

**Issue by blockmar** [DataDog/dd-trace-java#708]
The Hystrix Instumentation is not setup in a way to allow us to create monitors based on Hystrix health nor performance. (This is a problem for more instrumentations than Hystrix too)

There is currently no way of setting up Monitors based on Instrumentation metrics except for http resources? Hystrix in it self provides an excellent way to monitor the health of integrations. This should be leveraged to APM based monitors.

This we would like to monitor:
- Fail rates
- Open circuits (see Circuit Breaker in link below)
- Response times

Like to basic concepts of Hystrix https://github.com/Netflix/Hystrix/wiki/How-it-Works

I have tried doing this by monitoring `trace.hystrix.cmd` but that will only provide a generic `hits` count.

It seems like the solution to this would be to register Hystrix as a "service" in the same way you today register eg `java-aws-sdk`, `okhttp` or `redis`.

**Comment by tylerbenson** [comment]
It sounds like you're suggesting all `hystrix` spans should be reported to a common service of `hystrix`.  This would mean that all hystrix calls would be lumped together across all your applications.  I'm not sure that is a behavior most people will want.

You can do this manually by setting the service name for the current span while inside your hystrix calls.

**Comment by blockmar** [comment]
@tylerbenson This is kind of what I am suggesting. For me it does not make more sense to group all call to eg the AWS SDK compared to all calls to Hystrix so I don't really see the difference.

Is there another way of making APM based monitors that do not require a Service?

Please direct me to the documentation on how I set a custom Service scope and I will try it out.

**Comment by tylerbenson** [comment]
The general documentation is here: https://docs.datadoghq.com/tracing/advanced_usage/?tab=java#opentracing

You'll want to do something like this inside your hystrix command:

```java
Span span = GlobalTracer.get().activeSpan();
if(span != null) span.setTag(DDTags.SERVICE_NAME, "hystrix");
```

**Comment by blockmar** [comment]
OK, then I have a new problem for you. A lot of our hystrix command are created using Spring Annotations. So the classes are written by the people in the Spring Boot community and then use by use activated by Spring based configuration annotations. Thus we can not change them.

**Comment by tylerbenson** [comment]
Ah, I see.  I have an idea for a future config option that might solve this, but it's not implemented yet.  Perhaps the next best option is to consider using a `TraceInterceptor` to manually modify the traces after they finish. This isn't well documented, but you can find it in `dd-trace-api`.

**Comment by blockmar** [comment]
Maybe this is an Issue for the Dashboard and Monitor team and not the DD Agent. But the problem is that I can not base Monitors on `components` (`hystrix`) nor `operation name` (`hystrix.cmd`) only on _Service_ or Resource. Ant the resource is unique for every hystrix call.

As a result I have no way of creating a monitor for over all health of Hystrix within a Service (nor globally) (Not even at a command group level)

![screenshot 2019-02-26 at 10 13 14](https://user-images.githubusercontent.com/1249685/53401476-2936df00-39b0-11e9-9fb5-e84d26a8478f.png)

**Comment by andrewsouthard1** [comment]
@blockmar Thanks again for submitting this! In terms of your question in regards to monitoring, you can set a metric monitor based on the operation name `trace.hystrix.cmd` and then monitor by `resource_name`. [Metric monitor](https://app.datadoghq.com/monitors#create/metric). https://cl.ly/424f069bf890

**Comment by randomanderson** [comment]
I believe this issue has been solved by above.  Please reopen if this is not the case.
