### ISSUE TITLE
Question: When will the next release happen?

### ISSUE THREAD

**Issue by lcaproni-pp** [DataDog/dd-trace-java#7088]
Hey, 

I want to use the features added by JMXFetch that are detailed in [this](https://github.com/DataDog/dd-trace-java/pull/6935) PR, i'm just wondering when the next release will take place?  

I seen that the datadog agent itself has been updated to support [this](https://github.com/DataDog/datadog-agent/releases/tag/7.54.0) so just checking about release time frame for this library.

Thanks!

**Comment by nayeem-kamal** [comment]
Hi @lcaproni-pp , releases usually happen in the first full week of every month.

**Comment by lcaproni-pp** [comment]
Thanks @nayeem-kamal looking forward to it!

**Comment by bm1549** [comment]
Closing this out - please re-open if you need any additional clarification!

**Comment by jamesbassett** [comment]
I'm hoping for the jmxfetch update as well (for ZGC support) - so 🤞 that can make the next release
