### ISSUE TITLE
Graphql-java 22 support

### ISSUE THREAD

**Issue by jrogers** [DataDog/dd-trace-java#7153]
We upgraded to Spring Boot 3.3 and with DD agent version 1.34, we do not see graphql related spans at all. We noticed a couple things that could be at play here - first off https://github.com/DataDog/dd-trace-java/blob/b7b9e6991e522c9b348c7531d6d449071b97fb5d/dd-java-agent/instrumentation/graphql-java-14.0/build.gradle#L6 - so I assume it hasn't been tested yet with it. Also there were changes in graphql-java 22 around how `Instrumentation` functions that could be related - https://github.com/graphql-java/graphql-java/releases/tag/v22.0

**Comment by esfomeado** [comment]
The GraphQL spans still don't show up for me. Using 1.36 and GraphQL 22

**Comment by AlexRiedler** [comment]
@amarziali it seems the issue still persists using 1.36 ; confirm the same as above.
