### ISSUE TITLE
Compatibility issue with Guava 27+

### ISSUE THREAD

**Issue by milanvdm** [DataDog/dd-trace-java#716]
If you use Cassandra 3.6.0 (which uses Guava 27+), `dd-trace-java` will throw an `UnknownMethodException` due to a change of the method `.transform`.

A similar issue can be found here: https://datastax-oss.atlassian.net/browse/JAVA-1328

**Comment by milanvdm** [comment]
We were using an sbt plugin for datadog.
This plugin was defaulting to v0.10.0 of `dd-trace-java`.
Upgrading this solved the issue.

**Comment by milanvdm** [comment]
I can make it work but that means I need to update Guava to 27 for the dd-java-agent.
This means that there is no compatibility with Java 7 anymore.

But in the current state, datastax.cassandra 3.6.0 uses Guava 27+, so the agent does not work with that version.

**Comment by tylerbenson** [comment]
Thanks for the report.  Does this mean that the agent is actively breaking things or the instrumentation just isn't working on that version?

**Comment by milanvdm** [comment]
@tylerbenson The agent is actively breaking things. Because it runs the `TracingSession` it throws the `MethodNotFound` exception and therefore crashes our app.
Meaning that if you have an external dependency using Guava 27+, you cannot use dd-agent in your project.

**Comment by tylerbenson** [comment]
Ok, thanks for confirming that.  Until we get this fixed, please disable the cassandra instrumentation:

```
-Ddd.integration.cassandra.enabled=true
```

This will allow you to still use the rest of the instrumentation.

**Comment by tylerbenson** [comment]
This should be fixed in 0.27.0 with #786.  Thanks for the report.

**Comment by tylerbenson** [comment]
0.27.0 has been released: https://github.com/DataDog/dd-trace-java/releases/tag/v0.27.0
