### ISSUE TITLE
Missing @http.status_code in Play

### ISSUE THREAD

**Issue by mwisnicki** [DataDog/dd-trace-java#7164]
I've just updated DD agent from 0.77 to 1.35.0 and am seeing a lot more new information in request level spans from Play framework (2.8.16) however one notable attribute is now gone - the http.status_code which is pretty important.

**Comment by mwisnicki** [comment]
I found this was originally disabled in https://github.com/DataDog/dd-trace-java/pull/2804

Is there a plan to address this?

**Comment by nayeem-kamal** [comment]
We do not currently have plans to address this issue with Play framework however we will track this as an item to look into. For now, you can reenable the functionality by adding `-Ddd.trace.play.report-http-status=true` to your command line arguments when starting the tracer.

**Comment by mwisnicki** [comment]
Gotcha. If you have any information about what specific situations can trigger the original issue (wrong status codes - #2804 is pretty light on details), I would be grateful if you could share it.
