### ISSUE TITLE
Add Support for Custom Propagation Headers

### ISSUE THREAD

**Issue by aantono** [DataDog/dd-trace-java#717]
Allow ability to configure different header names to use for the following propagation headers: https://github.com/DataDog/dd-trace-java/blob/master/dd-trace-ot/src/main/java/datadog/opentracing/propagation/DatadogHttpCodec.java#L24-L27

```
"ot-baggage-"
"x-datadog-trace-id"
"x-datadog-parent-id"
"x-datadog-sampling-priority"
```

Alternatively would be ok to add support for aliases, in a priority order, for example have `x-datadog-trace-id` being the primary header, but also support alternative names for each, i.e. `TraceID`, `Trace-ID`, etc. for both `inject` and `extract` functions.

This will allow for better interop with requests originating in other tracing systems outside of the control domain, while allowing use of DataDog internally and still maintain complete Trace cross outer and inner systems.

If the feature is agreed upon, I would be willing to submit a PR for consideration.

**Comment by tylerbenson** [comment]
Thanks for submitting the suggestion.  Will need to discuss internally to decide on the correct corse of action on this.

**Comment by tylerbenson** [comment]
I assume you were asking this to be able to support B3.  We've decided to implement that instead: #756 
If I misunderstood, please explain your use-case.

**Comment by aantono** [comment]
I was actually looking to be able to integrate with traces originating from Haystack, they use a different header names - 
https://github.com/ExpediaDotCom/haystack-client-java/blob/master/core/src/main/java/com/expedia/www/haystack/client/propagation/DefaultKeyConvention.java#L25:L31

There is also Jaeger, which has their own propagation codec names as well, so I thought it would be beneficial to allow configuring those names via -d arguments. 😜

**Comment by randomanderson** [comment]
Released
