### ISSUE TITLE
Graphql-java 22 Support Still Not Working

### ISSUE THREAD

**Issue by surecloud-meason** [DataDog/dd-trace-java#7291]
We are running the latest spring boot 3.3.1 & graphql 22. We have upgraded to the latest Datadog agent 1.36 and still we are unable to view GraphQL spans.

Issue was apparently fixed here https://github.com/DataDog/dd-trace-java/issues/7153 but it isnt working.

**Comment by amarziali** [comment]
👋  @surecloud-meason thanks for having reported the issue and sorry for that. I opened another PR to fix it.

**Comment by amarziali** [comment]
The PR fixing the issue has been merged into master. The target date for the next release should be beginning of August. In the meanwhile, if you'd like to have an early testing, I can provide the link of a CI build. Just let me know

**Comment by surecloud-meason** [comment]
@amarziali please can you provide a CI build / docker image.

**Comment by amarziali** [comment]
You can use the circle CI build of the PR [here](https://output.circle-artifacts.com/output/job/3f37fd25-d936-427f-a6bc-792d6797ab25/artifacts/0/libs/dd-java-agent-1.38.0-SNAPSHOT.jar)

Please do not hesitate to share a feedback
