### ISSUE TITLE
startManual's fate

### ISSUE THREAD

**Issue by devn** [DataDog/dd-trace-java#740]
[The docs](https://github.com/DataDog/dd-trace-java/blob/7f74fb51d37acbb1793a288863bb757353787c11/dd-trace-ot/docs/opentracing-api.md#L60) mention using `startManual`, but I found that it is marked as deprecated [here](https://github.com/DataDog/dd-trace-java/blob/0cdc80aa149e6fa588a1f19ee792b42a59017450/dd-trace-ot/src/main/java/datadog/opentracing/DDTracer.java#L493). It looks like the example in the docs is up to date, but `startManual` should be removed in favor of simply calling `start`, yes?

**Comment by tylerbenson** [comment]
Yeah, `start` is the better option since that is what OpenTracing is moving to: https://github.com/opentracing/opentracing-java/blob/master/opentracing-api/src/main/java/io/opentracing/Tracer.java#L207
Would you be interested in submitting a PR to the docs site to update that?
