### ISSUE TITLE
Enabling profiling randomly

### ISSUE THREAD

**Issue by Laith-jalal** [DataDog/dd-trace-java#7491]
I'm running my jvm app on AWS ECS, and with the current setup using `-javaagent` and the `DD_PROFILING_ENABLED` environment variable, profiling is enabled for all containers. Is there any configuration or option that allows enabling profiling for only a specific percentage of containers?

**Comment by jbachorik** [comment]
Hi @Laith-jalal - no, there is no such option. That would require supporting remote configuration and we don't do that for profiler yet.
