### ISSUE TITLE
[redis] Redisson instrumentation only covers synchronous part of async `RedisConnection.send`.

### ISSUE THREAD

**Issue by mstyura** [DataDog/dd-trace-java#7510]
Currently instrumentation of Redisson's `RedisConnection` only tracks the [synchronous part of send](https://github.com/DataDog/dd-trace-java/blob/074bc9bc4efa7f71d1c9705e20620b5412271d0e/dd-java-agent/instrumentation/redisson-2.0.0/src/main/java/datadog/trace/instrumentation/redisson/RedissonInstrumentation.java#L61-L81) which leads to wrong command execution time reported (it also seems to miss any error which might be returned by response from Redis). Possibly the proper instrumentation must instrument return value of `RedissonInstrumentation.send` which is netty's `ChannelFuture`. Such approach is implemented by [open telemetry instrumentation](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/3fc1bbec8c36ebf808a9717198555d78c9f33499/instrumentation/redisson/redisson-3.0/javaagent/src/main/java/io/opentelemetry/javaagent/instrumentation/redisson/v3_0/RedisConnectionInstrumentation.java#L42-L63) for Redisson.

**Comment by amarziali** [comment]
Will be fixed in `1.40.0`
