### ISSUE TITLE
ClassNotFoundException with Hibernate instrumentation in Datadog APM Agent v0.25.0

### ISSUE THREAD

**Issue by accurate-dev** [DataDog/dd-trace-java#771]
We are currently using Tomcat v7.0.90 with Hibernate v3.1.3 and dd-java-agent-**0.25.0**.jar is throwing the following exception in our application:

java.lang.ClassNotFoundException: datadog.trace.bootstrap.instrumentation.context.FieldBackedProvider$ContextAccessor$org$hibernate$Query$datadog$trace$instrumentation$hibernate$v4_0$SessionState

This is only an issue starting with the latest 0.25.0 release from 3/15/19. Prior to this release, we did not experience any errors related to ClassNotFoundException from datadog agent.

**Comment by tylerbenson** [comment]
Hibernate instrumentation was only added in `0.25.0`, so this is why you haven't seen it before.  The instrumentation should only be activated on v4+, so I'm surprised you're seeing it with that version. Perhaps you could somehow confirm what version of `hibernate-core` is being loaded?

You can disable the instrumentation using `-Ddd.integration.hibernate.enabled=false`.

**Comment by accurate-dev** [comment]
Hi @tylerbenson, thanks for the quick response! If this is a potential bug that affects applications with hibernate v3 (I have confirmed we are using v3.13), is there any plans to provide a fix? I understand we can manually disable the instrumentation with the java opts argument, but we'd prefer to wait for a fix while we temporarily use v0.24.0 in the meantime.

**Comment by willgittoes-dd** [comment]
This is a bug, I can reproduce it with Hibernate 3.3.0.GA. I am looking into a fix now.

**Comment by tylerbenson** [comment]
This fix will be included in our next release.  If necessary you can test the [latest snapshot](https://oss.jfrog.org/artifactory/oss-snapshot-local/com/datadoghq/dd-java-agent/0.26.0-SNAPSHOT/dd-java-agent-0.26.0-SNAPSHOT.jar).

**Comment by tylerbenson** [comment]
Additional fixes are included in #777.

**Comment by tylerbenson** [comment]
This fix is included in the latest release.
