### ISSUE TITLE
Twilio SDK Support

### ISSUE THREAD

**Issue by darylrobbins** [DataDog/dd-trace-java#774]
I would like to add first-class instrumentation support for the Twilio SDK. Ideally, Twilio API calls should show up under their own service, say java-twilio-sdk. This would be similar to how the aws-sdk instrumentation works today. From reviewing the Twilio source code, [com.twilio.http. HttpClient.reliableRequest()](https://github.com/twilio/twilio-java/blob/master/src/main/java/com/twilio/http/HttpClient.java#L37) seems to be the best place to instrument the SDK. This method orchestrates the retry logic for making Twilio API calls.

**Comment by tylerbenson** [comment]
Allow me to clarify...
> I would like to add first-class instrumentation support 
Are you offering to provide a pull request?  If that's something you'd be comfortable with, that would probably be the most expedient option.

**Comment by darylrobbins** [comment]
Yes, your contribution guide said to raise an issue prior to adding new features.

**Comment by tylerbenson** [comment]
Great! Thanks for asking.  I just wanted to make sure it was an offer and not a request.

I'm not familiar with Twilio's API, but I'm happy to answer questions on how to instrument.  If you want to ping me on https://chat.datadoghq.com that might be the fastest way to answer questions.

**Comment by tylerbenson** [comment]
This has been released: https://github.com/DataDog/dd-trace-java/releases/tag/v0.27.0.  
@darylrobbins thanks again for the PR!
