### ISSUE TITLE
JVM Crashes on C  [libjavaProfiler5380372605108795391.so+0x3c640]  SafeAccess::load(void**)+0x0

### ISSUE THREAD

**Issue by wayoubi** [DataDog/dd-trace-java#7910]
A fatal error has been detected by the Java Runtime Environment:

  SIGSEGV (0xb) at pc=0x00007fb888d16640, pid=4539, tid=6050

 JRE version: OpenJDK Runtime Environment Corretto-21.0.5.11.1 (21.0.5+11) (build 21.0.5+11-LTS)
 Java VM: OpenJDK 64-Bit Server VM Corretto-21.0.5.11.1 (21.0.5+11-LTS, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, linux-amd64)
 Problematic frame:
 C  [libjavaProfiler5380372605108795391.so+0x3c640]  SafeAccess::load(void**)+0x0

 No core dump will be written. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again

 JFR recording file will be written. Location: //hs_err_pid4539.jfr

 If you would like to submit a bug report, please visit:
   https://github.com/corretto/corretto-21/issues/

---------------  T H R E A D  ---------------

Current thread (0x00007fb78aa90970):  JavaThread "http-nio-8095-exec-14" daemon [_thread_in_vm, id=6050, stack(0x00007fb768ae5000,0x00007fb768be6000) (1028K)]

Stack: [0x00007fb768ae5000,0x00007fb768be6000],  sp=0x00007fb768bde4c8,  free space=997k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  [libjavaProfiler5380372605108795391.so+0x3c640]  SafeAccess::load(void**)+0x0
C  [libjavaProfiler5380372605108795391.so+0x3d497]  Profiler::getNativeTrace(void*, ASGCT_CallFrame*, int, int, StackContext*, bool*)+0x97
C  [libjavaProfiler5380372605108795391.so+0x3e641]  Profiler::recordSample(void*, unsigned long long, int, int, unsigned int, Event*)+0x101
C  [libjavaProfiler5380372605108795391.so+0x4c225]  WallClockASGCT::signalHandler(int, siginfo_t*, void*, unsigned long long)+0x175
C  [libpthread.so.0+0x118e0]
C  [libc.so.6+0x72fd0]  vsnprintf+0x90

.
.
.
.

**Comment by jbachorik** [comment]
Hi @wayoubi - this is addressed in https://github.com/DataDog/java-profiler/pull/150 and will become a part of the upcoming patch release 1.42.1

**Comment by wayoubi** [comment]
A significant alteration in our code, which aligns with when the crash began, is the usage of this class:  
[Customizer (spring-security-docs 6.3.4 API)](https://docs.spring.io/spring-security/site/docs/current/api/org/springframework/security/config/Customizer.html) 

Do you think that incorporating this class could have led to the problem during the instrumentation with the DD agent?

**Comment by wayoubi** [comment]
> Hey Wasim, thanks for letting us know. We'll look into this crash, do you have the full error log that this came from?

FYI, I shared the flare on the support ticket #1918562
