### ISSUE TITLE
Disable logging

### ISSUE THREAD

**Issue by guzmo** [DataDog/dd-trace-java#793]
Hello there! :)

Sorry if this information exists somewhere, but I couldn't find anything obvious.

Currently we are getting a lot of these logs below.
```
Instance jmxfetch-config is sending 18 metrics to the metrics reporter during collection #120
```
We would only like to know when something goes wrong, but not that it keeps sending metrics all the time. Is it possible to disable these logs?

Cheers!

**Comment by johanvandeweerd** [comment]
You can set the log level to warn:
`-Ddatadog.slf4j.simpleLogger.defaultLogLevel=warn`

**Comment by brentm5** [comment]
Pretty sure this was fixed with https://github.com/DataDog/dd-trace-java/pull/796

**Comment by johanvandeweerd** [comment]
@brentm5 that issue only changed the log level from error to info for log statements starting with `JMXFetch config:`

**Comment by tylerbenson** [comment]
Ultimately the best way to fix this is to migrate [JMXFetch](https://github.com/DataDog/jmxfetch) over to SLF4J which will then allow it to use the same logging system.  Anyone want to offer a PR?

**Comment by tylerbenson** [comment]
This will be improved in #838 as I've done the work to migrate JMXFetch to SLF4J in https://github.com/DataDog/jmxfetch/pull/223

**Comment by tylerbenson** [comment]
This should be fixed in this release: https://github.com/DataDog/dd-trace-java/releases/tag/v0.29.0
