### ISSUE TITLE
Spring Integration is not instrumented at all

### ISSUE THREAD

**Issue by alfredosc8** [DataDog/dd-trace-java#801]
Spring Integration is not instrumented at all

**Comment by tylerbenson** [comment]
@alfredosc8 I am not familiar at all with https://spring.io/projects/spring-integration.  Could you please elaborate what you think would be useful to instrument?  Would you be interested in writing the instrumentation and submitting a PR?

**Comment by alfredosc8** [comment]
yes i’m

**Comment by alfredosc8** [comment]
Ok I will

**Comment by ricktg** [comment]
Spring itself is a set of tens of components. To name a few:
 * spring-data
 * spring-security
 * spring-ws
 * spring-core

I'd recommend phase it out so there is no mixup.

**Comment by alfredosc8** [comment]
Ricardo, spring integration is the integration project of spring, with channels, gateways, pipelines.
in any case i have been able to trace in it but adding interceptors. i also discovered the httpurlconnection instrumentation is not working properly when part of complex trace. it it not continuing the current trace.

**Comment by sreekesh93** [comment]
Is there any updates on this issue?

**Comment by dajulia3** [comment]
We would really like this as well.

**Comment by AbstractBike** [comment]
This would be really useful

**Comment by tylerbenson** [comment]
You might be able to use the OpenTelemetry instrumentation:
https://github.com/open-telemetry/opentelemetry-java-instrumentation/tree/main/instrumentation/spring/spring-integration-4.1
I'm not sure what level of support Datadog has for OpenTelemetry's Java API though.

**Comment by AbstractBike** [comment]
Thanks @tylerbenson ! It works

**Comment by bm1549** [comment]
Datadog has introduced support for many spring libraries over the past few months. Check them out in the latest version of the tracer!

https://docs.datadoghq.com/tracing/trace_collection/compatibility/java/
