### ISSUE TITLE
Build is not working

### ISSUE THREAD

**Issue by alfredosc8** [DataDog/dd-trace-java#802]
Running ./gradlew build is not working , on Mac, with this error:
* What went wrong:
Could not determine the dependencies of task ':dd-java-agent:instrumentation:shadowJar'.
> Could not resolve all files for configuration ':dd-java-agent:instrumentation:runtimeClasspath'.
   > Could not find jffi-native.jar (com.github.jnr:jffi:1.2.17).
     Searched in the following locations:
         file:/Users/ascotto/.m2/repository/com/github/jnr/jffi/1.2.17/jffi-1.2.17-native.jar

**Comment by tylerbenson** [comment]
if you're trying to build the javaagent, try running just `./gradlew :dd-java-agent:shadowJar`.

**Comment by alfredosc8** [comment]
i found the issue, jffi is not coming when building on mac, i built it and i’m ok now

**Comment by ratcashdev** [comment]
@alfredosc8 what do you mean by 'not coming'? I have a similar problem with gradle (on windows), although in a different project.

**Comment by alfredosc8** [comment]
i solved, thanks

**Comment by jo-al-ra** [comment]
I am also facing the same error on a different project. Can you please tell us how you solved it exactly?


This page is one of the first results when searching for the error. It is regrettable when some devs have the same problem but are not sharing the solution or elaborating on the issue to help others.
