### ISSUE TITLE
Instrumenting javax.servlet.http.HttpServlet emits stack map frame.

### ISSUE THREAD

**Issue by raphw** [DataDog/dd-trace-java#813]
I was looking into a corrupted class file and found that the corruption came from the instrumentation of the Data Dog agent. Since this is probably a problem in Byte Buddy, I am eager to find out about it, of course.

The class file in question is `javax.servlet.http.HttpServlet` in Java version two which contained a *StackMapFrame* attribute for the `service(HttpServletRequest, HttpServletResponse)` method. For Java 2, this attribute should not exist and also seems broken and I wonder how it ended up there.

Could you look into how you instrument the servlet class and maybe set a breakpoint in `MethodWriter.visitFrame` to see if it is triggered during the instrumetation of the service class. If so, could you give me a stack trace of this call to see where it is coming from?

Also: are you using any manual ASM in your agent?

PS: This corruption has no consequence for loading the corrupted class file. The JVM ignores the class file attribute for stack map frames for Java 2 classes, no error will be raised, but class file parsing tools (in this case, another Byte Buddy-based agent) struggle with processing the class file.

PPS: I can reproduce it using your agent, I will look into it.

**Comment by raphw** [comment]
Alright, it is your ASM code. The class file gets corrupted here: https://github.com/DataDog/dd-trace-java/blob/9988c8775f6c50115ba26458a191945ec98a7afb/dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/ExceptionHandlers.java#L70

**Comment by raphw** [comment]
I added an argument in Byte Buddy for the next version to include the class file version in the error handler resolver. Ideally, you register a wrapper for the class file version to suppress all calls to `visitFrame`.

**Comment by raphw** [comment]
I recommend you to only emit frames for Java 6 and higher. The stack manipulation provides an implementation.context object for this purpose.

**Comment by tylerbenson** [comment]
Hey Raph, I really appreciate you looking into this.

I seem to recall us using some byte buddy code somewhere that converts java class files to a newer version.  Since it sounds like this applies to classes compiled for older JVM's, wouldn't that help solve this problem?

**Comment by raphw** [comment]
You could register a visitor that removes all frames.
