### ISSUE TITLE
How do I add my own ScopeManager with dd-trace-ot 0.27.0?

### ISSUE THREAD

**Issue by slisaasquatch** [DataDog/dd-trace-java#820]
Before 0.27.0, we had our own `ScopeManager` with our own `ThreadLocal<Scope>`, and we rely on our custom `Executor` to pass along the `Scope`, and `addScopeContext` seems deprecated now.
How do I achieve the same thing in 0.27.0?

**Comment by tylerbenson** [comment]
Interesting.  I wasn't aware of anyone actually using this API.  Would you mind sharing more details about your implementation?
Are you using `dd-java-agent` or just `dd-trace-ot`?

**Comment by slisaasquatch** [comment]
I'm using `dd-trace-ot`. We use opentracing API in our code and we try to be implementation agnostic, since we switch between `dd-trace-ot` and Jaeger. Our app is async across the board, so we have to use our own implementation of `ScopeManager` with our own `ThreadLocal<Scope>` and pass it along with our own `Executor.

**Comment by tylerbenson** [comment]
I'm impressed that you're able to manage the async state correctly by using that and a custom `Executor`.  Do you have any suggestions for ways we can simplify and/or make it more standard?

**Comment by slisaasquatch** [comment]
My suggestion would be add the ability of using my own implementation of `ScopeManager`, which you could do before 0.27.0. It doesn't necessarily have to be the exact same way, and that's what Jaeger supports as well.

**Comment by tylerbenson** [comment]
Ok, I will investigate that option before removing this method.  Thanks for bringing up the issue.

**Comment by cemelo** [comment]
@tylerbenson another use case for this is people using Scala FP effect abstraction libraries (eg. monix, zio, cats-effect). They're async and act like green threads/fibers, and usually have their own scheduling rules. Because of this, a single operation might be executed by different threads.

**Comment by tylerbenson** [comment]
FYI I'm adding the ability to provide a custom `ScopeManager` in #1177.
