### ISSUE TITLE
Link to documentation broken

### ISSUE THREAD

**Issue by valenterry** [DataDog/dd-trace-java#826]
Hope that's the right place for the issue. In the Datadog APM Service UI, the Link for how to set JVM metrics is broken. It links to https://docs.datadoghq.com/tracing/advanced_usage/?tab=java#runtime-metrics but should probably link to https://docs.datadoghq.com/tracing/advanced/runtime_metrics/?tab=java

**Comment by labbati** [comment]
Hey thanks for noticing that. We notified the UI team in order to get that fixed, I will update this issue once it gets done.

**Comment by andrewsouthard1** [comment]
Thanks for flagging @valenterry we've ensured this has been updated.
