### ISSUE TITLE
PendingTraces leak to old gen space

### ISSUE THREAD

**Issue by sean-madden** [DataDog/dd-trace-java#847]
Hello,

Since enabling datadog APM (v0.26.2) in production for one of our services, we've noticed that the old gen size starts growing:
<img width="617" alt="Screen Shot 2019-05-20 at 2 50 30 PM" src="https://user-images.githubusercontent.com/30605997/58054207-ba7ca400-7b0e-11e9-812b-25d01d17d6b5.png">

This correlates with ECS terminating the container task and replacing it with a new one because the container tries to run a lot of Full GCs but cannot reclaim all of this space, causing the CPU to spike.

The purple spikes on this graph are indications of full GC running, which also correlate with the growth in old gen size:
<img width="1007" alt="Screen Shot 2019-05-20 at 2 52 57 PM" src="https://user-images.githubusercontent.com/30605997/58054324-12b3a600-7b0f-11e9-89cf-b2f4feaba071.png">

(note: these pictures do not show the same time period)

I was able to catch with a profiler before ECS restarted one of the containers, and I found that half of the strings in the application were made up of pending traces:
<img width="1502" alt="Screen Shot 2019-05-17 at 1 48 24 PM" src="https://user-images.githubusercontent.com/30605997/58054384-4db5d980-7b0f-11e9-963a-59c1269988e7.png">

Another odd behavior I've observed that happens sometimes, though not all the time, is that APM metrics will stop showing up in Datadog. Typically when this happens the containers will roll in about an hour. I didn't find any relevant errors in the agent or the application.

<img width="622" alt="Screen Shot 2019-05-13 at 5 21 21 PM" src="https://user-images.githubusercontent.com/30605997/58054471-82c22c00-7b0f-11e9-9be5-cd78997f5396.png">

It sounds an awful lot like: https://github.com/DataDog/dd-trace-java/issues/437 - and we do use a jax-rs client in our software, but we don't have that many jax-rs exceptions. It also seems like it would be resolved by 0.26.2.

Other integrations we're using: elasticsearch, hibernate, postgres, redis, aws-java-sdk, rabbitmq

**Comment by tylerbenson** [comment]
@sean-madden Thanks for the report. It would probably be best to contact support@datadoghq.com as they'll be able to dig in and get more details.

My guess is that you have a scope somewhere that isn't getting closed properly for some reason.  One thing that might help is setting `dd.trace.partial.flush.min.spans` (added in [0.22.0](https://github.com/DataDog/dd-trace-java/pull/662)).  If you upgrade to 0.27.0+ we [set the default to 1k](https://github.com/DataDog/dd-trace-java/pull/804).  This should be a good safeguard to prevent the "memory leak", but you will still have unrelated traces being clumped up under a single trace.  To solve that, it would help if you could provide steps to reproduce.

**Comment by sean-madden** [comment]
@tylerbenson I've opened a ticket with support, and they have given me a list of things to gather. I'm going to work on updating this package to 0.27.0+ in prod and also try to narrow down some steps to reproduce this issue.

**Comment by tylerbenson** [comment]
Great, thanks!  I'm going to close this issue and we can reopen later if necessary.  Feel free to continue adding details though.
