### ISSUE TITLE
Upgrade OpenTracing dependencies

### ISSUE THREAD

**Issue by nielsvn92** [DataDog/dd-trace-java#848]
Currently, OpenTracing v0.31.0 is being used which was released on 2018-01-12.
The most recent version is v0.33.0, which was released 2019-05-06.

In our application we (of course) use the latest stable versio, in which a few methods are dropped, specifically on the ScopeManager. This causes us to not be able to use the latest OpenTracing version in combination with DataDog.

We'd really appreciate if this dependency can be updated, and the resulting issues be fixed.

**Comment by tylerbenson** [comment]
I understand the concern.  We are trying to remove the OpenTracing dependency in dd-java-agent before we upgrade, to ensure we don't cause additional problems.  Thanks for your patience and for bringing this to our attention.

**Comment by RayzorFlash** [comment]
@tylerbenson Is there a linked issue we can follow to keep up to date with the progress of the above change? Thanks!

**Comment by Noxaro** [comment]
Are there any updates on this issue?
I wanted to use => https://github.com/opentracing-contrib/java-redis-client to instrument redisson for tracing. But currently it's impossible as all the newer versions are using the opentracing api 0.32+.

**Comment by randomanderson** [comment]
This is currently being worked on with #1020, #1026, #1034, and #1044

**Comment by tylerbenson** [comment]
This should actually be resolved with the 0.35.0 release where we updated our OT dependency to 0.32.0. We ended up doing this first.  Removing the OT dependency from dd-java-agent will come later.
