### ISSUE TITLE
OpenTracing document

### ISSUE THREAD

**Issue by yeluolei** [DataDog/dd-trace-java#851]
there is no ActiveSpan anymore and the document is still list it as a class.

https://github.com/DataDog/dd-trace-java/blob/master/dd-trace-ot/docs/opentracing-api.md

**Comment by MackenzieM** [comment]
+1 the documentation on how to set the MANUAL_KEEP flag for trace sampling seems to be out of date https://docs.datadoghq.com/tracing/guide/trace_sampling_and_storage/?tab=java
