### ISSUE TITLE
ContinuableScope with javaagent

### ISSUE THREAD

**Issue by yeluolei** [DataDog/dd-trace-java#852]
Hello,

I am trying to use the dd-java-agent when the Play framework started up, and it works fine. but when I try to use the `ContinuableScope`, something bad happened.

`ContinuableScope` is in `datadog.opentracing` package, and in java agent, it is relocated to `datadog.trace.agent.ot`. thus I can't cast and get the `ContinuableScope`, because I can't reference the package during compile time.
```
 ContinuableScope.Continuation continuation = ((ContinuableScope)GlobalTracer.get().scopeManager().active()).capture();
```

I have tried to include `dd-java-agent` as dependency during my compile time. but still not work, since everything else is packaged into a zip file.

without `Continuation`, I can't pass to another  thread. that's very sad.

is there any idea for this case?

thanks.

**Comment by tylerbenson** [comment]
You can cast it to a `TraceScope` available in the [public api](https://github.com/DataDog/dd-trace-java/blob/master/dd-trace-api/src/main/java/datadog/trace/context/TraceScope.java).  If you're trying to get tracing working with custom executors, you can try the new setting in [0.28.0](https://github.com/DataDog/dd-trace-java/releases/tag/v0.28.0) `dd.trace.executors`, which might solve your problem without requiring additional code.

**Comment by yeluolei** [comment]
got it, thanks! I will have a try. and after saw the new version config, it's awesome.

**Comment by yeluolei** [comment]
cast to TraceScope works, thanks!
