### ISSUE TITLE
okhttp3 error on start

### ISSUE THREAD

**Issue by williamscs** [DataDog/dd-trace-java#918]
I'm attempting to add the tracing libraries to my Spring Boot project.

I added these to my build.gradle:
```
compile "io.opentracing.contrib:opentracing-spring-cloud-starter:0.2.6"
compile "com.datadoghq:dd-trace-ot:0.30.0"
```

When the application starts, I get this error:

> ***************************
> APPLICATION FAILED TO START
> ***************************
> 
> Description:
> 
> An attempt was made to call a method that does not exist. The attempt was made from the following location:
> 
>     datadog.trace.common.writer.DDApi.<clinit>(DDApi.java:48)
> 
> The following method did not exist:
> 
>     okhttp3.MediaType.get(Ljava/lang/String;)Lokhttp3/MediaType;
> 
> The method's class, okhttp3.MediaType, is available from the following locations:
> 
>     jar:file:/Users/chris/.gradle/caches/modules-2/files-2.1/com.squareup.okhttp3/okhttp/3.8.1/4d060ca3190df0eda4dc13415532a12e15ca5f11/okhttp-3.8.1.jar!/okhttp3/MediaType.class
> 
> It was loaded from the following location:
> 
>     file:/Users/chris/.gradle/caches/modules-2/files-2.1/com.squareup.okhttp3/okhttp/3.8.1/4d060ca3190df0eda4dc13415532a12e15ca5f11/okhttp-3.8.1.jar
> 
> 
> Action:
> 
> Correct the classpath of your application so that it contains a single, compatible version of okhttp3.MediaType

If I change my imports to this:
```
    compile "io.opentracing.contrib:opentracing-spring-cloud-starter:0.2.6"
    compile "com.squareup.okhttp3:okhttp:4.0.0"
    compile "com.datadoghq:dd-trace-ot:0.30.0"
```
then error goes away. I've cleared my gradle cache, but it still occurs.

**Comment by williamscs** [comment]
I ran `$ gradle -q dependencyInsight --dependency okhttp3` and got this:
```
com.squareup.okhttp3:okhttp:3.8.1 (selected by rule)
   variant "runtime" [
      org.gradle.status = release (not requested)
      Requested attributes not found in the selected variant:
         org.gradle.usage  = java-api
   ]

com.squareup.okhttp3:okhttp:3.11.0 -> 3.8.1
\--- com.datadoghq:dd-trace-ot:0.30.0
     \--- compileClasspath
```

I have no idea what rule would enforce this. It doesn't look like there's another dependency asking for that version.

**Comment by Xyaren** [comment]
I experience a similar issue. Why are there no tests failing ?

**Comment by randomanderson** [comment]
There's a transient dependency from that version of `opentracing-spring-cloud-starter` TO `openfeign-feign-okhttp` TO an older version of okhttp.  Your options are:

- Manually set the okhttp dependency in your gradle file

OR

- Exclude the transitive dependency

**Comment by williamscs** [comment]
Thanks so much. We're definitely using openfeign.
