### ISSUE TITLE
0.31.0 release?

### ISSUE THREAD

**Issue by dpratt** [DataDog/dd-trace-java#929]
Forgive me if this is not the appropriate communication channel - I can't find a discussion board, mailing list or gitter channel anywhere.

What's the plan/timeframe for the 0.31.0 release? It's been over a month since the previous release, and I suspect there are quite a few people waiting for some of the changes introduced since then.

**Comment by tylerbenson** [comment]
Generally, our slack channel would be the better forum for this kind of stuff.  Sorry for the delay. I am starting the release process now.  It should be public later today.

**Comment by dpratt** [comment]
I'll be damned - I had no idea there was one. Can I get access to it?

**Comment by tylerbenson** [comment]
https://chat.datadoghq.com/

**Comment by dpratt** [comment]
I just joined - which channel do you guys typically hang out on?

**Comment by tylerbenson** [comment]
`#apm` is the best place to ask questions for APM.
