### ISSUE TITLE
OpenTracing API 0.33 support / intent

### ISSUE THREAD

**Issue by nhoughto** [DataDog/dd-trace-java#946]
Dropped this in slack last week but got nothing, so putting here so i don't have to keep checking slack for an answer (slack not a great medium for this kind of thing i find!).

Having a great time getting things instrumented, was interested to know about the roadmap for releasing against opentracing-api versions? Specifically the Java SDK. It seems that the opentracing-contrib projects like AWS SDK etc roughly support the latest stable version (current 0.33) and you guys are on 0.31, which means a bunch of community libraries don't work, or fail subtly. We are not using the instrumenting agent, as the agent doesn't support read-only filesystems (https://github.com/DataDog/dd-trace-java/issues/429) so we have to instrument everything ourselves, which means grabbing community libraries to get the job done, but the lack of latest opentracing api support really slows things down.tl;dr when is 0.33 support coming for java sdk?

https://datadoghq.slack.com/archives/C3SH3KCQG/p1565309116173500

**Comment by andrewsouthard1** [comment]
Hey @nhoughto - that's accurate and we're working on removing the dependency from the Java Tracer. This is a large effort but we're targeting by end of the year - any updates and we'll keep you posted on it.

**Comment by changjiang2016** [comment]
I found the problem too.The 0.32 version of opentracing is compatible with 0.31. Therefore, you can make corresponding changes when temporarily using the source code locally to override the method that 0.31 does not implement, and you can temporarily return null. I did this locally,and it works.Of course this is a temporary way, if you need to upgrade opentracing.

**Comment by tylerbenson** [comment]
We upgraded our OT version to 0.32.0 in version 0.35.0.  Closing this issue.
