### ISSUE TITLE
Couchbase integration dropping trace

### ISSUE THREAD

**Issue by aarya123** [DataDog/dd-trace-java#965]
We are currently using the couchbase java client version 2.7.9 and our calls to the buckets seem to be dropping the trace. After digging into the code a bit, I believe the source of the errors are from the fact that the base couchbase client pulls in netty into a different package, which is preventing the netty event loop integration from working: https://github.com/couchbase/couchbase-jvm-core/blob/cb9126f/pom.xml#L342,L345.
@tylerbenson has also pointed out that the couchbase integration doesn't current check the callback for the trace, which could possibly be why this issue went undetected: https://github.com/DataDog/dd-trace-java/blob/50279d6/dd-java-agent/instrumentation/couchbase-2.0/src/test/groovy/CouchbaseClientTest.groovy

**Comment by randomanderson** [comment]
PR had to be reverted for this release

**Comment by tylerbenson** [comment]
@aarya123 This is fixed in 0.34.0.
