### ISSUE TITLE
Grpc server interceptor error taging differs from client behavior

### ISSUE THREAD

**Issue by marcoferrer** [DataDog/dd-trace-java#981]
At the moment there is a discrepancy with how spans are tagged in the client interceptor vs the server interceptor. Any status other than `Status.OK` is tagged as an error, yet the server will only tag spans with error if service method invocation throws an exception. 

This makes it difficult to visualize service errors in the APM dashboard. Particularly when clients are external and not instrumented.

I started PR #980 related to this, which contains the proposed changes. I wanted to discuss this first before updating the unit tests.

**Comment by tylerbenson** [comment]
Thanks for the PR!  I'll continue discussion over there.

**Comment by randomanderson** [comment]
Released
